# Plugins/certificate_select.py
certificate_select_strings = {
    "en": {
        "cert_loading_error": "⚠️ Could not load certificate information.",
        "certificate_prompt": "📃 Please select a certificate.\nCurrently selected: {selected}",
        "certificate_selected": "📌 Certificate selected: {selected}",
        "cert_saved": "📌 Certificate saved: {cert_name}",
        "already_selected": "⚠️ This certificate is already selected.",
        "no_selection": "None",
        "back_button": "🔙 Go Back",
        "saving_error": "A database error occurred. Please try again.",
        "callback_error": "⚠️ An unexpected error occurred.",
    },
    "tr": {
        "cert_loading_error": "⚠️ Sertifika bilgileri yüklenemedi.",
        "certificate_prompt": "📃 Lütfen bir sertifika seçin.\nMevcut seçim: {selected}",
        "certificate_selected": "📌 Sertifika seçildi: {selected}",
        "cert_saved": "📌 Sertifika kaydedildi: {cert_name}",
        "already_selected": "⚠️ Bu sertifika zaten seçili.",
        "no_selection": "Hiçbiri",
        "back_button": "🔙 Geri Dön",
        "saving_error": "Bir veritabanı hatası oluştu. Lütfen tekrar deneyin.",
        "callback_error": "⚠️ Beklenmedik bir hata oluştu.",
    },
    "ru": {
        "cert_loading_error": "⚠️ Не удалось загрузить информацию о сертификате.",
        "certificate_prompt": "📃 Пожалуйста, выберите сертификат.\nТекущий выбор: {selected}",
        "certificate_selected": "📌 Сертификат выбран: {selected}",
        "cert_saved": "📌 Сертификат сохранен: {cert_name}",
        "already_selected": "⚠️ Этот сертификат уже выбран.",
        "no_selection": "Не выбрано",
        "back_button": "🔙 Назад",
        "saving_error": "Произошла ошибка базы данных. Пожалуйста, попробуйте еще раз.",
        "callback_error": "⚠️ Произошла непредвиденная ошибка.",
    },
    "de": {
        "cert_loading_error": "⚠️ Zertifikatinformationen konnten nicht geladen werden.",
        "certificate_prompt": "📃 Bitte wähle ein Zertifikat aus.\nAktuell ausgewählt: {selected}",
        "certificate_selected": "📌 Zertifikat ausgewählt: {selected}",
        "cert_saved": "📌 Zertifikat gespeichert: {cert_name}",
        "already_selected": "⚠️ Dieses Zertifikat ist bereits ausgewählt.",
        "no_selection": "Keines",
        "back_button": "🔙 Zurück",
        "saving_error": "Ein Datenbankfehler ist aufgetreten. Bitte versuche es erneut.",
        "callback_error": "⚠️ Ein unerwarteter Fehler ist aufgetreten."
    },
    "es": {
        "cert_loading_error": "⚠️ No se pudo cargar la información del certificado.",
        "certificate_prompt": "📃 Por favor, selecciona un certificado.\nSeleccionado actualmente: {selected}",
        "certificate_selected": "📌 Certificado seleccionado: {selected}",
        "cert_saved": "📌 Certificado guardado: {cert_name}",
        "already_selected": "⚠️ Este certificado ya está seleccionado.",
        "no_selection": "Ninguno",
        "back_button": "🔙 Volver",
        "saving_error": "Ocurrió un error en la base de datos. Por favor, inténtalo de nuevo.",
        "callback_error": "⚠️ Ocurrió un error inesperado."
    },
    "fr": {
        "cert_loading_error": "⚠️ Impossible de charger les informations du certificat.",
        "certificate_prompt": "📃 Veuillez sélectionner un certificat.\nActuellement sélectionné: {selected}",
        "certificate_selected": "📌 Certificat sélectionné: {selected}",
        "cert_saved": "📌 Certificat enregistré: {cert_name}",
        "already_selected": "⚠️ Ce certificat est déjà sélectionné.",
        "no_selection": "Aucun",
        "back_button": "🔙 Retour",
        "saving_error": "Une erreur de base de données est survenue. Veuillez réessayer.",
        "callback_error": "⚠️ Une erreur inattendue est survenue."
    },
    "zh": {
        "cert_loading_error": "⚠️ 无法加载证书信息.",
        "certificate_prompt": "📃 请选择一个证书.\n当前选择: {selected}",
        "certificate_selected": "📌 已选择证书: {selected}",
        "cert_saved": "📌 证书已保存: {cert_name}",
        "already_selected": "⚠️ 此证书已被选中.",
        "no_selection": "无",
        "back_button": "🔙 返回",
        "saving_error": "发生数据库错误. 请重试.",
        "callback_error": "⚠️ 发生未知错误."
    },
    "ar": {
        "cert_loading_error": "⚠️ تعذر تحميل معلومات الشهادة.",
        "certificate_prompt": "📃 الرجاء تحديد شهادة.\nالمحدد حاليا: {selected}",
        "certificate_selected": "📌 تم تحديد الشهادة: {selected}",
        "cert_saved": "📌 تم حفظ الشهادة: {cert_name}",
        "already_selected": "⚠️ هذه الشهادة محددة بالفعل.",
        "no_selection": "لا يوجد",
        "back_button": "🔙 رجوع",
        "saving_error": "حدث خطأ في قاعدة البيانات. الرجاء المحاولة مرة أخرى.",
        "callback_error": "⚠️ حدث خطأ غير متوقع."
    },
    "pt": {
        "cert_loading_error": "⚠️ Não foi possível carregar as informações do certificado.",
        "certificate_prompt": "📃 Por favor, selecione um certificado.\nAtualmente selecionado: {selected}",
        "certificate_selected": "📌 Certificado selecionado: {selected}",
        "cert_saved": "📌 Certificado salvo: {cert_name}",
        "already_selected": "⚠️ Este certificado já está selecionado.",
        "no_selection": "Nenhum",
        "back_button": "🔙 Voltar",
        "saving_error": "Ocorreu um erro no banco de dados. Por favor, tente novamente.",
        "callback_error": "⚠️ Ocorreu um erro inesperado."
    },
    "it": {
        "cert_loading_error": "⚠️ Impossibile caricare le informazioni del certificato.",
        "certificate_prompt": "📃 Si prega di selezionare un certificato.\nAttualmente selezionato: {selected}",
        "certificate_selected": "📌 Certificato selezionato: {selected}",
        "cert_saved": "📌 Certificato salvato: {cert_name}",
        "already_selected": "⚠️ Questo certificato è già selezionato.",
        "no_selection": "Nessuno",
        "back_button": "🔙 Indietro",
        "saving_error": "Si è verificato un errore nel database. Si prega di riprovare.",
        "callback_error": "⚠️ Si è verificato un errore imprevisto."
    },
    "ja": {
        "cert_loading_error": "⚠️ 証明書情報を読み込めませんでした。",
        "certificate_prompt": "📃 証明書を選択してください。\n現在選択中: {selected}",
        "certificate_selected": "📌 証明書が選択されました: {selected}",
        "cert_saved": "📌 証明書が保存されました: {cert_name}",
        "already_selected": "⚠️ この証明書はすでに選択されています。",
        "no_selection": "なし",
        "back_button": "🔙 戻る",
        "saving_error": "データベースエラーが発生しました。もう一度お試しください。",
        "callback_error": "⚠️ 予期せぬエラーが発生しました。"
    },
    "ko": {
        "cert_loading_error": "⚠️ 인증서 정보를 로드할 수 없습니다.",
        "certificate_prompt": "📃 인증서를 선택하십시오.\n현재 선택됨: {selected}",
        "certificate_selected": "📌 인증서 선택됨: {selected}",
        "cert_saved": "📌 인증서 저장됨: {cert_name}",
        "already_selected": "⚠️ 이 인증서는 이미 선택되었습니다.",
        "no_selection": "없음",
        "back_button": "🔙 뒤로",
        "saving_error": "데이터베이스 오류가 발생했습니다. 다시 시도하십시오.",
        "callback_error": "⚠️ 예기치 않은 오류가 발생했습니다."
    },
    "hi": {
        "cert_loading_error": "⚠️ प्रमाणपत्र जानकारी लोड नहीं की जा सकी।",
        "certificate_prompt": "📃 कृपया एक प्रमाणपत्र चुनें।\nवर्तमान में चयनित: {selected}",
        "certificate_selected": "📌 प्रमाणपत्र चयनित: {selected}",
        "cert_saved": "📌 प्रमाणपत्र सहेजा गया: {cert_name}",
        "already_selected": "⚠️ यह प्रमाणपत्र पहले से ही चयनित है।",
        "no_selection": "कोई नहीं",
        "back_button": "🔙 वापस जाएं",
        "saving_error": "एक डेटाबेस त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "callback_error": "⚠️ एक अप्रत्याशित त्रुटि हुई।"
    },
    "vi": {
        "cert_loading_error": "⚠️ Không thể tải thông tin chứng chỉ.",
        "certificate_prompt": "📃 Vui lòng chọn một chứng chỉ.\nHiện đang chọn: {selected}",
        "certificate_selected": "📌 Chứng chỉ đã chọn: {selected}",
        "cert_saved": "📌 Chứng chỉ đã lưu: {cert_name}",
        "already_selected": "⚠️ Chứng chỉ này đã được chọn.",
        "no_selection": "Không có",
        "back_button": "🔙 Quay lại",
        "saving_error": "Đã xảy ra lỗi cơ sở dữ liệu. Vui lòng thử lại.",
        "callback_error": "⚠️ Đã xảy ra lỗi không mong muốn."
    },
    "id": {
        "cert_loading_error": "⚠️ Tidak dapat memuat informasi sertifikat.",
        "certificate_prompt": "📃 Silakan pilih sertifikat.\nSaat ini dipilih: {selected}",
        "certificate_selected": "📌 Sertifikat dipilih: {selected}",
        "cert_saved": "📌 Sertifikat disimpan: {cert_name}",
        "already_selected": "⚠️ Sertifikat ini sudah dipilih.",
        "no_selection": "Tidak ada",
        "back_button": "🔙 Kembali",
        "saving_error": "Terjadi kesalahan database. Silakan coba lagi.",
        "callback_error": "⚠️ Terjadi kesalahan tak terduga."
    },
    "pl": {
        "cert_loading_error": "⚠️ Nie można załadować informacji o certyfikacie.",
        "certificate_prompt": "📃 Proszę wybrać certyfikat.\nAktualnie wybrany: {selected}",
        "certificate_selected": "📌 Wybrano certyfikat: {selected}",
        "cert_saved": "📌 Certyfikat zapisany: {cert_name}",
        "already_selected": "⚠️ Ten certyfikat jest już wybrany.",
        "no_selection": "Brak",
        "back_button": "🔙 Wróć",
        "saving_error": "Wystąpił błąd bazy danych. Proszę spróbować ponownie.",
        "callback_error": "⚠️ Wystąpił nieoczekiwany błąd."
    },
    "nl": {
        "cert_loading_error": "⚠️ Kon certificaatinformatie niet laden.",
        "certificate_prompt": "📃 Selecteer een certificaat.\nMomenteel geselecteerd: {selected}",
        "certificate_selected": "📌 Certificaat geselecteerd: {selected}",
        "cert_saved": "📌 Certificaat opgeslagen: {cert_name}",
        "already_selected": "⚠️ Dit certificaat is al geselecteerd.",
        "no_selection": "Geen",
        "back_button": "🔙 Terug",
        "saving_error": "Er is een databasefout opgetreden. Probeer het opnieuw.",
        "callback_error": "⚠️ Er is een onverwachte fout opgetreden."
    }
}
