# Plugins/download.py
download_strings = {
    "en": {
        "download_failed_message": "❌ Download failed for {file_name}.",
        "download_attempt_failed_message": "⚠️ Error downloading {file_name}, retrying... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} downloaded successfully!",
        "download_error_detected": "An error was detected during download.",
        "httpnot200": "The requested URL is not available.",
        "httpnotfile": "The URL does not point to a downloadable file.",
        "connection_error": "Could not establish a connection.",
        "unexpected_response_error": "Received an unexpected response from the server.",
        "invalid_url_error": "The provided URL is invalid.",
        "too_many_redirects_error": "Exceeded maximum number of redirects.",
        "ssl_error": "An SSL connection error occurred.",
        "payload_error": "Received invalid or incomplete data.",
        "server_disconnected_error": "The server connection was unexpectedly closed.",
        "general_download_error": "An error occurred while downloading the file.",
        "file_not_found_error": "The requested file could not be found.",
        "file_corrupted_error": "The downloaded file is corrupted.",
        "unknown_exception_error": "An unexpected error occurred.",
        "retrying_message": "Retrying download... ({current}/{limit})"
    },
    "tr": {
        "download_failed_message": "❌ {file_name} indirilemedi.",
        "download_attempt_failed_message": "⚠️ {file_name} indirilirken hata oluştu, yeniden deneniyor... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} başarıyla indirildi!",
        "download_error_detected": "İndirme sırasında bir hata algılandı.",
        "httpnot200": "İstenen URL mevcut değil.",
        "httpnotfile": "URL indirilebilir bir dosyayı göstermiyor.",
        "connection_error": "Bağlantı kurulamadı.",
        "unexpected_response_error": "Sunucudan beklenmedik bir yanıt alındı.",
        "invalid_url_error": "Geçersiz bir URL sağlandı.",
        "too_many_redirects_error": "Maksimum yönlendirme sayısını aştı.",
        "ssl_error": "Bir SSL bağlantı hatası oluştu.",
        "payload_error": "Geçersiz veya eksik veri alındı.",
        "server_disconnected_error": "Sunucu bağlantısı beklenmedik bir şekilde kesildi.",
        "general_download_error": "Dosya indirilirken bir hata oluştu.",
        "file_not_found_error": "İstenen dosya bulunamadı.",
        "file_corrupted_error": "İndirilen dosya bozuk.",
        "unknown_exception_error": "Beklenmedik bir hata oluştu.",
        "retrying_message": "İndirme yeniden deneniyor... ({current}/{limit})"
    },
    "ru": {
        "download_failed_message": "❌ Не удалось скачать {file_name}.",
        "download_attempt_failed_message": "⚠️ Ошибка при скачивании {file_name}, повторная попытка... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} успешно скачан!",
        "download_error_detected": "Во время загрузки была обнаружена ошибка.",
        "httpnot200": "Запрошенный URL недоступен.",
        "httpnotfile": "URL не указывает на скачиваемый файл.",
        "connection_error": "Не удалось установить соединение.",
        "unexpected_response_error": "Получен непредвиденный ответ от сервера.",
        "invalid_url_error": "Предоставлен неверный URL.",
        "too_many_redirects_error": "Превышено максимальное количество перенаправлений.",
        "ssl_error": "Произошла ошибка SSL-соединения.",
        "payload_error": "Получены неверные или неполные данные.",
        "server_disconnected_error": "Соединение с сервером было неожиданно прервано.",
        "general_download_error": "Произошла ошибка при скачивании файла.",
        "file_not_found_error": "Запрошенный файл не найден.",
        "file_corrupted_error": "Скачанный файл поврежден.",
        "unknown_exception_error": "Произошла непредвиденная ошибка.",
        "retrying_message": "Повторная попытка загрузки... ({current}/{limit})"
    },
    "de": {
        "download_failed_message": "❌ Download für {file_name} fehlgeschlagen.",
        "download_attempt_failed_message": "⚠️ Fehler beim Herunterladen von {file_name}, versuche erneut... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} erfolgreich heruntergeladen!",
        "download_error_detected": "Während des Downloads wurde ein Fehler festgestellt.",
        "httpnot200": "Die angeforderte URL ist nicht verfügbar.",
        "httpnotfile": "Die URL verweist nicht auf eine herunterladbare Datei.",
        "connection_error": "Es konnte keine Verbindung hergestellt werden.",
        "unexpected_response_error": "Unerwartete Antwort vom Server erhalten.",
        "invalid_url_error": "Die angegebene URL ist ungültig.",
        "too_many_redirects_error": "Maximale Anzahl von Weiterleitungen überschritten.",
        "ssl_error": "Ein SSL-Verbindungsfehler ist aufgetreten.",
        "payload_error": "Ungültige oder unvollständige Daten empfangen.",
        "server_disconnected_error": "Die Serververbindung wurde unerwartet geschlossen.",
        "general_download_error": "Beim Herunterladen der Datei ist ein Fehler aufgetreten.",
        "file_not_found_error": "Die angeforderte Datei konnte nicht gefunden werden.",
        "file_corrupted_error": "Die heruntergeladene Datei ist beschädigt.",
        "unknown_exception_error": "Ein unerwarteter Fehler ist aufgetreten.",
        "retrying_message": "Download wird erneut versucht... ({current}/{limit})"
    },
    "es": {
        "download_failed_message": "❌ Falló la descarga de {file_name}.",
        "download_attempt_failed_message": "⚠️ Error al descargar {file_name}, reintentando... ({current}/{limit})",
        "download_successful_message": "✅ ¡{file_name} descargado exitosamente!",
        "download_error_detected": "Se detectó un error durante la descarga.",
        "httpnot200": "La URL solicitada no está disponible.",
        "httpnotfile": "La URL no apunta a un archivo descargable.",
        "connection_error": "No se pudo establecer una conexión.",
        "unexpected_response_error": "Se recibió una respuesta inesperada del servidor.",
        "invalid_url_error": "La URL proporcionada no es válida.",
        "too_many_redirects_error": "Se excedió el número máximo de redirecciones.",
        "ssl_error": "Ocurrió un error de conexión SSL.",
        "payload_error": "Se recibieron datos inválidos o incompletos.",
        "server_disconnected_error": "La conexión del servidor se cerró inesperadamente.",
        "general_download_error": "Ocurrió un error al descargar el archivo.",
        "file_not_found_error": "No se pudo encontrar el archivo solicitado.",
        "file_corrupted_error": "El archivo descargado está corrupto.",
        "unknown_exception_error": "Ocurrió un error inesperado.",
        "retrying_message": "Reintentando descarga... ({current}/{limit})"
    },
    "fr": {
        "download_failed_message": "❌ Échec du téléchargement pour {file_name}.",
        "download_attempt_failed_message": "⚠️ Erreur lors du téléchargement de {file_name}, nouvelle tentative... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} téléchargé avec succès !",
        "download_error_detected": "Une erreur a été détectée pendant le téléchargement.",
        "httpnot200": "L'URL demandée n'est pas disponible.",
        "httpnotfile": "L'URL ne pointe pas vers un fichier téléchargeable.",
        "connection_error": "Impossible d'établir une connexion.",
        "unexpected_response_error": "Réponse inattendue reçue du serveur.",
        "invalid_url_error": "L'URL fournie est invalide.",
        "too_many_redirects_error": "Nombre maximal de redirections dépassé.",
        "ssl_error": "Une erreur de connexion SSL est survenue.",
        "payload_error": "Données invalides ou incomplètes reçues.",
        "server_disconnected_error": "La connexion au serveur a été fermée inopinément.",
        "general_download_error": "Une erreur est survenue lors du téléchargement du fichier.",
        "file_not_found_error": "Le fichier demandé n'a pas pu être trouvé.",
        "file_corrupted_error": "Le fichier téléchargé est corrompu.",
        "unknown_exception_error": "Une erreur inattendue est survenue.",
        "retrying_message": "Nouvelle tentative de téléchargement... ({current}/{limit})"
    },
    "zh-cn": {
        "download_failed_message": "❌ {file_name} 下载失败。",
        "download_attempt_failed_message": "⚠️ 下载 {file_name} 时出错，正在重试... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} 下载成功！",
        "download_error_detected": "下载过程中检测到错误。",
        "httpnot200": "请求的 URL 不可用。",
        "httpnotfile": "URL 未指向可下载文件。",
        "connection_error": "无法建立连接。",
        "unexpected_response_error": "收到来自服务器的意外响应。",
        "invalid_url_error": "提供的 URL 无效。",
        "too_many_redirects_error": "超出最大重定向次数。",
        "ssl_error": "发生 SSL 连接错误。",
        "payload_error": "收到无效或不完整的数据。",
        "server_disconnected_error": "服务器连接意外关闭。",
        "general_download_error": "下载文件时发生错误。",
        "file_not_found_error": "找不到请求的文件。",
        "file_corrupted_error": "下载的文件已损坏。",
        "unknown_exception_error": "发生未知错误。",
        "retrying_message": "正在重试下载... ({current}/{limit})"
    },
    "ar": {
        "download_failed_message": "❌ فشل تنزيل {file_name}.",
        "download_attempt_failed_message": "⚠️ خطأ في تنزيل {file_name}، إعادة المحاولة... ({current}/{limit})",
        "download_successful_message": "✅ تم تنزيل {file_name} بنجاح!",
        "download_error_detected": "تم اكتشاف خطأ أثناء التنزيل.",
        "httpnot200": "الرابط المطلوب غير متاح.",
        "httpnotfile": "الرابط لا يشير إلى ملف قابل للتنزيل.",
        "connection_error": "تعذر إنشاء اتصال.",
        "unexpected_response_error": "تم استلام استجابة غير متوقعة من الخادم.",
        "invalid_url_error": "الرابط المقدم غير صالح.",
        "too_many_redirects_error": "تجاوز الحد الأقصى لعدد عمليات إعادة التوجيه.",
        "ssl_error": "حدث خطأ في اتصال SSL.",
        "payload_error": "تم استلام بيانات غير صالحة أو غير مكتملة.",
        "server_disconnected_error": "تم إغلاق اتصال الخادم بشكل غير متوقع.",
        "general_download_error": "حدث خطأ أثناء تنزيل الملف.",
        "file_not_found_error": "تعذر العثور على الملف المطلوب.",
        "file_corrupted_error": "الملف الذي تم تنزيله تالف.",
        "unknown_exception_error": "حدث خطأ غير متوقع.",
        "retrying_message": "إعادة محاولة التنزيل... ({current}/{limit})"
    },
    "pt": {
        "download_failed_message": "❌ Falha no download de {file_name}.",
        "download_attempt_failed_message": "⚠️ Erro ao baixar {file_name}, tentando novamente... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} baixado com sucesso!",
        "download_error_detected": "Um erro foi detectado durante o download.",
        "httpnot200": "O URL solicitado não está disponível.",
        "httpnotfile": "O URL não aponta para um arquivo para download.",
        "connection_error": "Não foi possível estabelecer uma conexão.",
        "unexpected_response_error": "Recebida uma resposta inesperada do servidor.",
        "invalid_url_error": "O URL fornecido é inválido.",
        "too_many_redirects_error": "Excedido o número máximo de redirecionamentos.",
        "ssl_error": "Ocorreu um erro de conexão SSL.",
        "payload_error": "Dados inválidos ou incompletos recebidos.",
        "server_disconnected_error": "A conexão do servidor foi inesperadamente fechada.",
        "general_download_error": "Ocorreu um erro ao baixar o arquivo.",
        "file_not_found_error": "O arquivo solicitado não pôde ser encontrado.",
        "file_corrupted_error": "O arquivo baixado está corrompido.",
        "unknown_exception_error": "Ocorreu um erro inesperado.",
        "retrying_message": "Tentando novamente o download... ({current}/{limit})"
    },
    "it": {
        "download_failed_message": "❌ Download fallito per {file_name}.",
        "download_attempt_failed_message": "⚠️ Erro durante il download di {file_name}, riprovo... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} scaricato con successo!",
        "download_error_detected": "È stato rilevato un errore durante il download.",
        "httpnot200": "L'URL richiesto non è disponibile.",
        "httpnotfile": "L'URL non punta a un file scaricabile.",
        "connection_error": "Impossibile stabilire una connessione.",
        "unexpected_response_error": "Ricevuta una risposta inaspettata dal server.",
        "invalid_url_error": "L'URL fornito non è valido.",
        "too_many_redirects_error": "Superato il numero massimo di reindirizzamenti.",
        "ssl_error": "Si è verificato un errore di connessione SSL.",
        "payload_error": "Dati non validi o incompleti ricevuti.",
        "server_disconnected_error": "La connessione al server è stata chiusa inaspettatamente.",
        "general_download_error": "Si è verificato un errore durante il download del file.",
        "file_not_found_error": "Il file richiesto non è stato trovato.",
        "file_corrupted_error": "Il file scaricato è corrotto.",
        "unknown_exception_error": "Si è verificato un errore imprevisto.",
        "retrying_message": "Riprovo il download... ({current}/{limit})"
    },
    "ja": {
        "download_failed_message": "❌ {file_name} のダウンロードに失敗しました。",
        "download_attempt_failed_message": "⚠️ {file_name} のダウンロード中にエラーが発生しました。再試行中... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} が正常にダウンロードされました！",
        "download_error_detected": "ダウンロード中にエラーが検出されました。",
        "httpnot200": "要求されたURLは利用できません。",
        "httpnotfile": "URLはダウンロード可能なファイルを指していません。",
        "connection_error": "接続を確立できませんでした。",
        "unexpected_response_error": "サーバーから予期しない応答を受信しました。",
        "invalid_url_error": "提供されたURLは無効です。",
        "too_many_redirects_error": "リダイレクトの最大数を超えました。",
        "ssl_error": "SSL接続エラーが発生しました。",
        "payload_error": "無効または不完全なデータを受信しました。",
        "server_disconnected_error": "サーバー接続が予期せず閉じられました。",
        "general_download_error": "ファイルのダウンロード中にエラーが発生しました。",
        "file_not_found_error": "要求されたファイルが見つかりませんでした。",
        "file_corrupted_error": "ダウンロードしたファイルが破損しています。",
        "unknown_exception_error": "予期しないエラーが発生しました。",
        "retrying_message": "ダウンロードを再試行中... ({current}/{limit})"
    },
    "ko": {
        "download_failed_message": "❌ {file_name} 다운로드 실패.",
        "download_attempt_failed_message": "⚠️ {file_name} 다운로드 중 오류 발생, 재시도 중... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} 다운로드 성공!",
        "download_error_detected": "다운로드 중 오류가 감지되었습니다.",
        "httpnot200": "요청한 URL을 사용할 수 없습니다.",
        "httpnotfile": "URL이 다운로드 가능한 파일을 가리키지 않습니다.",
        "connection_error": "연결을 설정할 수 없습니다.",
        "unexpected_response_error": "서버로부터 예기치 않은 응답을 받았습니다.",
        "invalid_url_error": "제공된 URL이 유효하지 않습니다.",
        "too_many_redirects_error": "최대 리디렉션 수를 초과했습니다.",
        "ssl_error": "SSL 연결 오류가 발생했습니다.",
        "payload_error": "유효하지 않거나 불완전한 데이터를 받았습니다.",
        "server_disconnected_error": "서버 연결이 예기치 않게 닫혔습니다.",
        "general_download_error": "파일 다운로드 중 오류가 발생했습니다.",
        "file_not_found_error": "요청한 파일을 찾을 수 없습니다.",
        "file_corrupted_error": "다운로드한 파일이 손상되었습니다.",
        "unknown_exception_error": "예기치 않은 오류가 발생했습니다.",
        "retrying_message": "다운로드 재시도 중... ({current}/{limit})"
    },
    "hi": {
        "download_failed_message": "❌ {file_name} के लिए डाउनलोड विफल।",
        "download_attempt_failed_message": "⚠️ {file_name} डाउनलोड करने में त्रुटि, पुनः प्रयास कर रहा है... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} सफलतापूर्वक डाउनलोड हो गया!",
        "download_error_detected": "डाउनलोड के दौरान एक त्रुटि का पता चला था।",
        "httpnot200": "अनुरोधित URL उपलब्ध नहीं है।",
        "httpnotfile": "URL डाउनलोड करने योग्य फ़ाइल की ओर इशारा नहीं करता है।",
        "connection_error": "कनेक्शन स्थापित नहीं किया जा सका।",
        "unexpected_response_error": "सर्वर से एक अप्रत्याशित प्रतिक्रिया प्राप्त हुई।",
        "invalid_url_error": "प्रदान किया गया URL अमान्य है।",
        "too_many_redirects_error": "पुनर्निर्देशनों की अधिकतम संख्या पार हो गई।",
        "ssl_error": "एक SSL कनेक्शन त्रुटि हुई।",
        "payload_error": "अमान्य या अधूरी डेटा प्राप्त हुई।",
        "server_disconnected_error": "सर्वर कनेक्शन अप्रत्याशित रूप से बंद हो गया था।",
        "general_download_error": "फ़ाइल डाउनलोड करते समय एक त्रुटि हुई।",
        "file_not_found_error": "अनुरोधित फ़ाइल नहीं मिल सकी।",
        "file_corrupted_error": "डाउनलोड की गई फ़ाइल दूषित है।",
        "unknown_exception_error": "एक अप्रत्याशित त्रुटि हुई।",
        "retrying_message": "डाउनलोड पुनः प्रयास कर रहा है... ({current}/{limit})"
    },
    "vi": {
        "download_failed_message": "❌ Tải xuống {file_name} thất bại.",
        "download_attempt_failed_message": "⚠️ Lỗi khi tải xuống {file_name}, đang thử lại... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} đã tải xuống thành công!",
        "download_error_detected": "Đã phát hiện lỗi trong quá trình tải xuống.",
        "httpnot200": "URL được yêu cầu không khả dụng.",
        "httpnotfile": "URL không trỏ đến một tệp có thể tải xuống.",
        "connection_error": "Không thể thiết lập kết nối.",
        "unexpected_response_error": "Đã nhận được phản hồi không mong muốn từ máy chủ.",
        "invalid_url_error": "URL được cung cấp không hợp lệ.",
        "too_many_redirects_error": "Đã vượt quá số lượng chuyển hướng tối đa.",
        "ssl_error": "Đã xảy ra lỗi kết nối SSL.",
        "payload_error": "Đã nhận được dữ liệu không hợp lệ hoặc không đầy đủ.",
        "server_disconnected_error": "Kết nối máy chủ đã bị đóng bất ngờ.",
        "general_download_error": "Đã xảy ra lỗi khi tải xuống tệp.",
        "file_not_found_error": "Không tìm thấy tệp được yêu cầu.",
        "file_corrupted_error": "Tệp đã tải xuống bị hỏng.",
        "unknown_exception_error": "Đã xảy ra lỗi không mong muốn.",
        "retrying_message": "Đang thử lại tải xuống... ({current}/{limit})"
    },
    "id": {
        "download_failed_message": "❌ Unduhan gagal untuk {file_name}.",
        "download_attempt_failed_message": "⚠️ Kesalahan mengunduh {file_name}, mencoba lagi... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} berhasil diunduh!",
        "download_error_detected": "Terdeteksi kesalahan selama pengunduhan.",
        "httpnot200": "URL yang diminta tidak tersedia.",
        "httpnotfile": "URL tidak mengarah ke file yang dapat diunduh.",
        "connection_error": "Tidak dapat membuat koneksi.",
        "unexpected_response_error": "Menerima respons tak terduga dari server.",
        "invalid_url_error": "URL yang diberikan tidak valid.",
        "too_many_redirects_error": "Melebihi jumlah maksimum pengalihan.",
        "ssl_error": "Terjadi kesalahan koneksi SSL.",
        "payload_error": "Menerima data tidak valid atau tidak lengkap.",
        "server_disconnected_error": "Koneksi server ditutup secara tak terduga.",
        "general_download_error": "Terjadi kesalahan saat mengunduh file.",
        "file_not_found_error": "File yang diminta tidak dapat ditemukan.",
        "file_corrupted_error": "File yang diunduh rusak.",
        "unknown_exception_error": "Terjadi kesalahan tak terduga.",
        "retrying_message": "Mencoba lagi mengunduh... ({current}/{limit})"
    },
    "pl": {
        "download_failed_message": "❌ Pobieranie {file_name} nie powiodło się.",
        "download_attempt_failed_message": "⚠️ Błąd pobierania {file_name}, ponawianie... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} pobrano pomyślnie!",
        "download_error_detected": "Wykryto błąd podczas pobierania.",
        "httpnot200": "Żądany adres URL jest niedostępny.",
        "httpnotfile": "Adres URL nie wskazuje na plik do pobrania.",
        "connection_error": "Nie można nawiązać połączenia.",
        "unexpected_response_error": "Otrzymano nieoczekiwaną odpowiedź z serwera.",
        "invalid_url_error": "Podany adres URL jest nieprawidłowy.",
        "too_many_redirects_error": "Przekroczono maksymalną liczbę przekierowań.",
        "ssl_error": "Wystąpił błąd połączenia SSL.",
        "payload_error": "Otrzymano nieprawidłowe lub niekompletne dane.",
        "server_disconnected_error": "Połączenie z serwerem zostało nieoczekiwanie zamknięte.",
        "general_download_error": "Wystąpił błąd podczas pobierania pliku.",
        "file_not_found_error": "Nie można znaleźć żądanego pliku.",
        "file_corrupted_error": "Pobrany plik jest uszkodzony.",
        "unknown_exception_error": "Wystąpił nieoczekiwany błąd.",
        "retrying_message": "Ponawianie pobierania... ({current}/{limit})"
    },
    "nl": {
        "download_failed_message": "❌ Download mislukt voor {file_name}.",
        "download_attempt_failed_message": "⚠️ Fout bij downloaden {file_name}, opnieuw proberen... ({current}/{limit})",
        "download_successful_message": "✅ {file_name} succesvol gedownload!",
        "download_error_detected": "Er is een fout gedetecteerd tijdens het downloaden.",
        "httpnot200": "De aangevraagde URL is niet beschikbaar.",
        "httpnotfile": "De URL verwijst niet naar een downloadbaar bestand.",
        "connection_error": "Kon geen verbinding maken.",
        "unexpected_response_error": "Onverwachte reactie van de server ontvangen.",
        "invalid_url_error": "De opgegeven URL is ongeldig.",
        "too_many_redirects_error": "Maximum aantal omleidingen overschreden.",
        "ssl_error": "Er is een SSL-verbindingsfout opgetreden.",
        "payload_error": "Ongeldige of onvolledige gegevens ontvangen.",
        "server_disconnected_error": "De serververbinding is onverwacht gesloten.",
        "general_download_error": "Er is een fout opgetreden tijdens het downloaden van het bestand.",
        "file_not_found_error": "Het aangevraagde bestand kon niet worden gevonden.",
        "file_corrupted_error": "Het gedownloade bestand is beschadigd.",
        "unknown_exception_error": "Er is een onverwachte fout opgetreden.",
        "retrying_message": "Download opnieuw proberen... ({current}/{limit})"
    }
}
