# utils/gen_html.py
generate_html_strings = {
    "en": {
        "install_button": "Install",
        "installing": "Installing...",
        "download_button": "Download",
        "selected_certificate": "Selected Certificate",
        "unsupported_system": "Unsupported System",
        "credits": "Made with <i class=\"fa-solid fa-heart fa-beat\"></i> by AppleFavour",
        "system_info": "System Information",
        "requires_newer_OS": "Requires iOS {requiredOSVersion} or newer.",
    },
    "tr": {
        "title": "Favour Sign",
        "install_button": "Yükle",
        "installing": "Yükleniyor...",
        "download_button": "İndir",
        "selected_certificate": "Seçili Sertifika",
        "unsupported_system": "Desteklenmiyor",
        "credits": "<i class=\"fa-solid fa-heart fa-beat\"></i> ile AppleFavour tarafından yapıldı.",
        "system_info": "Sistem Bilgisi",
        "requires_newer_OS": "iOS {requiredOSVersion} veya daha yenisini gerektirir.",
    },
    "ru": {
        "install_button": "Установить",
        "installing": "Установка...",
        "download_button": "Скачать",
        "selected_certificate": "Выбранный сертификат",
        "unsupported_system": "Не поддерживается",
        "credits": "Сделано с <i class=\"fa-solid fa-heart fa-beat\"></i> от AppleFavour",
        "system_info": "Информация о системе",
        "requires_newer_OS": "Требуется iOS {requiredOSVersion} или новее.",
    },
    "de": {
        "install_button": "Installieren",
        "installing": "Installiere...",
        "download_button": "Herunterladen",
        "selected_certificate": "Ausgewähltes Zertifikat",
        "unsupported_system": "Nicht unterstützt",
        "credits": "Erstellt mit <i class=\"fa-solid fa-heart fa-beat\"></i> von AppleFavour",
        "system_info": "Systeminformationen",
        "requires_newer_OS": "Erfordert iOS {requiredOSVersion} oder neuer.",
    },
    "es": {
        "install_button": "Instalar",
        "installing": "Instalando...",
        "download_button": "Descargar",
        "selected_certificate": "Certificado seleccionado",
        "unsupported_system": "Sistema no compatible",
        "credits": "Hecho con <i class=\"fa-solid fa-heart fa-beat\"></i> por AppleFavour",
        "system_info": "Información del sistema",
        "requires_newer_OS": "Requiere iOS {requiredOSVersion} o superior."
    },
    "fr": {
        "install_button": "Installer",
        "installing": "Installation...",
        "download_button": "Télécharger",
        "selected_certificate": "Certificat sélectionné",
        "unsupported_system": "Système non pris en charge",
        "credits": "Fait avec <i class=\"fa-solid fa-heart fa-beat\"></i> par AppleFavour",
        "system_info": "Informations système",
        "requires_newer_OS": "Nécessite iOS {requiredOSVersion} ou plus récent."
    },
    "zh-cn": {
        "install_button": "安装",
        "installing": "正在安装...",
        "download_button": "下载",
        "selected_certificate": "已选证书",
        "unsupported_system": "不支持的系统",
        "credits": "由 AppleFavour 用 <i class=\"fa-solid fa-heart fa-beat\"></i> 制作",
        "system_info": "系统信息",
        "requires_newer_OS": "需要 iOS {requiredOSVersion} 或更高版本。"
    },
    "ar": {
        "install_button": "تثبيت",
        "installing": "جاري التثبيت...",
        "download_button": "تنزيل",
        "selected_certificate": "الشهادة المحددة",
        "unsupported_system": "نظام غير مدعوم",
        "credits": "صنع بـ <i class=\"fa-solid fa-heart fa-beat\"></i> بواسطة AppleFavour",
        "system_info": "معلومات النظام",
        "requires_newer_OS": "يتطلب iOS {requiredOSVersion} أو أحدث."
    },
    "pt": {
        "install_button": "Instalar",
        "installing": "Instalando...",
        "download_button": "Baixar",
        "selected_certificate": "Certificado Selecionado",
        "unsupported_system": "Sistema Não Suportado",
        "credits": "Feito com <i class=\"fa-solid fa-heart fa-beat\"></i> por AppleFavour",
        "system_info": "Informações do Sistema",
        "requires_newer_OS": "Requer iOS {requiredOSVersion} ou mais recente.",
    },
    "it": {
        "install_button": "Installa",
        "installing": "Installazione...",
        "download_button": "Scarica",
        "selected_certificate": "Certificato Selezionato",
        "unsupported_system": "Sistema non supportato",
        "credits": "Realizzato con <i class=\"fa-solid fa-heart fa-beat\"></i> da AppleFavour",
        "system_info": "Informazioni di Sistema",
        "requires_newer_OS": "Richiede iOS {requiredOSVersion} o versioni successive.",
    },
    "ja": {
        "install_button": "インストール",
        "installing": "インストール中...",
        "download_button": "ダウンロード",
        "selected_certificate": "選択された証明書",
        "unsupported_system": "サポートされていないシステム",
        "credits": "AppleFavourが<i class=\"fa-solid fa-heart fa-beat\"></i>を込めて作成",
        "system_info": "システム情報",
        "requires_newer_OS": "iOS {requiredOSVersion}以降が必要です。",
    },
    "ko": {
        "install_button": "설치",
        "installing": "설치 중...",
        "download_button": "다운로드",
        "selected_certificate": "선택된 인증서",
        "unsupported_system": "지원되지 않는 시스템",
        "credits": "AppleFavour가 <i class=\"fa-solid fa-heart fa-beat\"></i>로 제작",
        "system_info": "시스템 정보",
        "requires_newer_OS": "iOS {requiredOSVersion} 이상이 필요합니다.",
    },
    "hi": {
        "install_button": "इंस्टॉल करें",
        "installing": "इंस्टॉल हो रहा है...",
        "download_button": "डाउनलोड करें",
        "selected_certificate": "चयनित प्रमाणपत्र",
        "unsupported_system": "असमर्थित सिस्टम",
        "credits": "AppleFavour द्वारा <i class=\"fa-solid fa-heart fa-beat\"></i> के साथ बनाया गया",
        "system_info": "सिस्टम जानकारी",
        "requires_newer_OS": "iOS {requiredOSVersion} या नए की आवश्यकता है।",
    },
    "vi": {
        "install_button": "Cài đặt",
        "installing": "Đang cài đặt...",
        "download_button": "Tải xuống",
        "selected_certificate": "Chứng chỉ đã chọn",
        "unsupported_system": "Hệ thống không được hỗ trợ",
        "credits": "Được làm bằng <i class=\"fa-solid fa-heart fa-beat\"></i> bởi AppleFavour",
        "system_info": "Thông tin hệ thống",
        "requires_newer_OS": "Yêu cầu iOS {requiredOSVersion} trở lên.",
    },
    "id": {
        "install_button": "Instal",
        "installing": "Menginstal...",
        "download_button": "Unduh",
        "selected_certificate": "Sertifikat Terpilih",
        "unsupported_system": "Sistem Tidak Didukung",
        "credits": "Dibuat dengan <i class=\"fa-solid fa-heart fa-beat\"></i> oleh AppleFavour",
        "system_info": "Informasi Sistem",
        "requires_newer_OS": "Membutuhkan iOS {requiredOSVersion} atau yang lebih baru.",
    },
    "pl": {
        "install_button": "Zainstaluj",
        "installing": "Instalowanie...",
        "download_button": "Pobierz",
        "selected_certificate": "Wybrany certyfikat",
        "unsupported_system": "Nieobsługiwany system",
        "credits": "Wykonano z <i class=\"fa-solid fa-heart fa-beat\"></i> przez AppleFavour",
        "system_info": "Informacje o systemie",
        "requires_newer_OS": "Wymaga iOS {requiredOSVersion} lub nowszego."
    },
    "nl": {
        "install_button": "Installeren",
        "installing": "Installeren...",
        "download_button": "Downloaden",
        "selected_certificate": "Geselecteerd certificaat",
        "unsupported_system": "Niet-ondersteund systeem",
        "credits": "Gemaakt met <i class=\"fa-solid fa-heart fa-beat\"></i> door AppleFavour",
        "system_info": "Systeeminformatie",
        "requires_newer_OS": "Vereist iOS {requiredOSVersion} of nieuwer.",
    }
}
