# utils/helpers.py
helpers_strings = {
    "en": {
        "create_folder_error": "Error creating folder: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "The file seems to have disappeared during the process.",
        "file_format_error": "The IPA file format is invalid or corrupted.",
        "file_size_unexpected": "Downloaded file size ({downloaded}) does not match the expected size ({expected}).",
        "exception_context": "Error: {exception}"
    },
    "tr": {
        "create_folder_error": "Klasör oluşturulurken hata: {error}",
        "hour_ETA": "{remaining_time}s",
        "minute_ETA": "{remaining_time}d",
        "second_ETA": "{remaining_time}sn",
        "ETA": "Tahmini Süre: {estimated_remaining_download_time}",
        "file_is_lost": "Dosya işlem sırasında kaybolmuş gibi görünüyor.",
        "file_format_error": "IPA dosya formatı geçersiz veya bozuk.",
        "file_size_unexpected": "İndirilen dosya boyutu ({downloaded}), beklenen boyutla ({expected}) eşleşmiyor.",
        "exception_context": "Hata: {exception}",
    },
    "ru": {
        "create_folder_error": "Ошибка при создании папки: {error}",
        "hour_ETA": "{remaining_time}ч",
        "minute_ETA": "{remaining_time}м",
        "second_ETA": "{remaining_time}с",
        "ETA": "Примерное время: {estimated_remaining_download_time}",
        "file_is_lost": "Файл, кажется, исчез в процессе обработки.",
        "file_format_error": "Формат файла IPA недействителен или поврежден.",
        "file_size_unexpected": "Размер загруженного файла ({downloaded}) не соответствует ожидаемому размеру ({expected}).",
        "exception_context": "Ошибка: {exception}"
    },
    "de": {
        "create_folder_error": "Fehler beim Erstellen des Ordners: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "Die Datei scheint während des Vorgangs verschwunden zu sein.",
        "file_format_error": "Das IPA-Dateiformat ist ungültig oder beschädigt.",
        "file_size_unexpected": "Die heruntergeladene Dateigröße ({downloaded}) stimmt nicht mit der erwarteten Größe ({expected}) überein.",
        "exception_context": "Fehler: {exception}"
    },
    "es": {
        "create_folder_error": "Error al crear la carpeta: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "El archivo parece haber desaparecido durante el proceso.",
        "file_format_error": "El formato del archivo IPA no es válido o está corrupto.",
        "file_size_unexpected": "El tamaño del archivo descargado ({downloaded}) no coincide con el tamaño esperado ({expected}).",
        "exception_context": "Error: {exception}"
    },
    "fr": {
        "create_folder_error": "Erreur lors de la création du dossier: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "Le fichier semble avoir disparu pendant le processus.",
        "file_format_error": "Le format du fichier IPA est invalide ou corrompu.",
        "file_size_unexpected": "La taille du fichier téléchargé ({downloaded}) ne correspond pas à la taille attendue ({expected}).",
        "exception_context": "Erreur: {exception}"
    },
    "zh-cn": {
        "create_folder_error": "创建文件夹时出错: {error}",
        "hour_ETA": "{remaining_time}小时",
        "minute_ETA": "{remaining_time}分钟",
        "second_ETA": "{remaining_time}秒",
        "ETA": "预计到达时间: {estimated_remaining_download_time}",
        "file_is_lost": "文件在处理过程中似乎已丢失。",
        "file_format_error": "IPA 文件格式无效或已损坏。",
        "file_size_unexpected": "下载文件大小 ({downloaded}) 与预期大小 ({expected}) 不匹配。",
        "exception_context": "错误: {exception}"
    },
    "ar": {
        "create_folder_error": "خطأ في إنشاء المجلد: {error}",
        "hour_ETA": "{remaining_time} ساعة",
        "minute_ETA": "{remaining_time} دقيقة",
        "second_ETA": "{remaining_time} ثانية",
        "ETA": "الوقت المقدر: {estimated_remaining_download_time}",
        "file_is_lost": "يبدو أن الملف قد اختفى أثناء العملية.",
        "file_format_error": "تنسيق ملف IPA غير صالح أو تالف.",
        "file_size_unexpected": "حجم الملف الذي تم تنزيله ({downloaded}) لا يتطابق مع الحجم المتوقع ({expected}).",
        "exception_context": "خطأ: {exception}"
    },
    "pt": {
        "create_folder_error": "Erro ao criar pasta: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "O arquivo parece ter desaparecido durante o processo.",
        "file_format_error": "O formato do arquivo IPA é inválido ou corrompido.",
        "file_size_unexpected": "O tamanho do arquivo baixado ({downloaded}) não corresponde ao tamanho esperado ({expected}).",
        "exception_context": "Erro: {exception}"
    },
    "it": {
        "create_folder_error": "Errore durante la creazione della cartella: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "Il file sembra essere scomparso durante il processo.",
        "file_format_error": "Il formato del file IPA non è valido o è corrotto.",
        "file_size_unexpected": "La dimensione del file scaricato ({downloaded}) non corrisponde alla dimensione prevista ({expected}).",
        "exception_context": "Errore: {exception}"
    },
    "ja": {
        "create_folder_error": "フォルダ作成エラー: {error}",
        "hour_ETA": "{remaining_time}時間",
        "minute_ETA": "{remaining_time}分",
        "second_ETA": "{remaining_time}秒",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "ファイルが処理中に消えたようです。",
        "file_format_error": "IPAファイル形式が無効または破損しています。",
        "file_size_unexpected": "ダウンロードされたファイルサイズ ({downloaded}) が予期されたサイズ ({expected}) と一致しません。",
        "exception_context": "エラー: {exception}"
    },
    "ko": {
        "create_folder_error": "폴더 생성 오류: {error}",
        "hour_ETA": "{remaining_time}시간",
        "minute_ETA": "{remaining_time}분",
        "second_ETA": "{remaining_time}초",
        "ETA": "예상 시간: {estimated_remaining_download_time}",
        "file_is_lost": "파일이 처리 중에 사라진 것 같습니다.",
        "file_format_error": "IPA 파일 형식이 유효하지 않거나 손상되었습니다.",
        "file_size_unexpected": "다운로드된 파일 크기 ({downloaded})가 예상 크기 ({expected})와 일치하지 않습니다.",
        "exception_context": "오류: {exception}"
    },
    "hi": {
        "create_folder_error": "फ़ोल्डर बनाने में त्रुटि: {error}",
        "hour_ETA": "{remaining_time}घंटे",
        "minute_ETA": "{remaining_time}मिनट",
        "second_ETA": "{remaining_time}सेकंड",
        "ETA": "अनुमानित समय: {estimated_remaining_download_time}",
        "file_is_lost": "फ़ाइल प्रक्रिया के दौरान गायब हो गई लगती है।",
        "file_format_error": "IPA फ़ाइल स्वरूप अमान्य या दूषित है।",
        "file_size_unexpected": "डाउनलोड की गई फ़ाइल का आकार ({downloaded}) अपेक्षित आकार ({expected}) से मेल नहीं खाता।",
        "exception_context": "त्रुटि: {exception}"
    },
    "vi": {
        "create_folder_error": "Lỗi tạo thư mục: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "Tệp dường như đã biến mất trong quá trình xử lý.",
        "file_format_error": "Định dạng tệp IPA không hợp lệ hoặc bị hỏng.",
        "file_size_unexpected": "Kích thước tệp đã tải xuống ({downloaded}) không khớp với kích thước dự kiến ({expected}).",
        "exception_context": "Lỗi: {exception}"
    },
    "id": {
        "create_folder_error": "Kesalahan membuat folder: {error}",
        "hour_ETA": "{remaining_time}j",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}d",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "File tampaknya hilang selama proses.",
        "file_format_error": "Format file IPA tidak valid atau rusak.",
        "file_size_unexpected": "Ukuran file yang diunduh ({downloaded}) tidak cocok dengan ukuran yang diharapkan ({expected}).",
        "exception_context": "Kesalahan: {exception}"
    },
    "pl": {
        "create_folder_error": "Błąd tworzenia folderu: {error}",
        "hour_ETA": "{remaining_time}h",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "Plik zaginął podczas procesu.",
        "file_format_error": "Format pliku IPA jest nieprawidłowy lub uszkodzony.",
        "file_size_unexpected": "Rozmiar pobranego pliku ({downloaded}) nie odpowiada oczekiwanemu rozmiarowi ({expected}).",
        "exception_context": "Błąd: {exception}"
    },
    "nl": {
        "create_folder_error": "Fout bij het maken van map: {error}",
        "hour_ETA": "{remaining_time}u",
        "minute_ETA": "{remaining_time}m",
        "second_ETA": "{remaining_time}s",
        "ETA": "ETA: {estimated_remaining_download_time}",
        "file_is_lost": "Het bestand lijkt te zijn verdwenen tijdens het proces.",
        "file_format_error": "Het IPA-bestandsformaat is ongeldig of beschadigd.",
        "file_size_unexpected": "Gedownloade bestandsgrootte ({downloaded}) komt niet overeen met de verwachte grootte ({expected}).",
        "exception_context": "Fout: {exception}"
    }
}
