# Plugins/help.py
help_strings = {
    "en": {
        "user_not_registered": "You are not registered to use this bot.",
        "available_cmds": "**Available Commands**",
        "user_cmds": "**User Commands**",
        "cmd_prefixes": "Active command prefixes: {prefixes}",
        "admin_cmds": "**Admin Commands**",
        "help_cmd": "Shows this help message.",
        "speedtest_cmd": "Measures the connection speed.",
        "info_cmd": "Displays information about the bot.",
        "sign_cmd": "Signs the replied IPA file.",
        "clear_cmd": "Resets all modification options.",
        "profile_cmd": "Removes the embedded mobile provision file.",
        "minos_cmd": "Sets the minimum OS version required.",
        "id_cmd": "Changes the application's bundle ID.",
        "version_cmd": "Changes the application's version.",
        "name_cmd": "Changes the application's name.",
        "update_cmd": "Updates the bot from the repository.",
        "duyur_cmd": "Sends an announcement to all users.",
        "exec_cmd": "Executes a shell command.",
        "restart_cmd": "Restarts the bot.",
        "shutdown_cmd": "Shuts down the bot.",
        "user_cmd": "Manages user registrations.",
        "premium_cmd": "Manages premium user status.",
        "unknown_exception": "An error occurred while processing the help request from @{username} ({userID}): {error}"
    },
    "tr": {
        "user_not_registered": "Bu botu kullanmak için kayıtlı değilsiniz.",
        "available_cmds": "**Mevcut Komutlar**",
        "user_cmds": "**Kullanıcı Komutları**",
        "cmd_prefixes": "Aktif komut önekleri: {prefixes}",
        "admin_cmds": "**Yönetici Komutları**",
        "help_cmd": "Bu yardım mesajını gösterir.",
        "speedtest_cmd": "Bağlantı hızını ölçer.",
        "info_cmd": "Bot hakkında bilgi görüntüler.",
        "sign_cmd": "Yanıtlanan IPA dosyasını imzalar.",
        "clear_cmd": "Tüm düzenleme seçeneklerini sıfırlar.",
        "profile_cmd": "Gömülü mobil provizyon dosyasını kaldırır.",
        "minos_cmd": "Gerekli minimum işletim sistemi sürümünü ayarlar.",
        "id_cmd": "Uygulamanın paket kimliğini değiştirir.",
        "version_cmd": "Uygulamanın sürümünü değiştirir.",
        "name_cmd": "Uygulamanın adını değiştirir.",
        "update_cmd": "Botu depodan günceller.",
        "duyur_cmd": "Tüm kullanıcılara bir duyuru gönderir.",
        "exec_cmd": "Bir kabuk komutu çalıştırır.",
        "restart_cmd": "Botu yeniden başlatır.",
        "shutdown_cmd": "Botu kapatır.",
        "user_cmd": "Kullanıcı kayıtlarını yönetir.",
        "premium_cmd": "Premium kullanıcı durumunu yönetir.",
        "unknown_exception": "@{username} ({userID}) kullanıcısından yardım isteği işlenirken bir hata oluştu: {error}"
    },
    "ru": {
        "user_not_registered": "Вы не зарегистрированы для использования этого бота.",
        "available_cmds": "**Доступные команды**",
        "user_cmds": "**Пользовательские команды**",
        "cmd_prefixes": "Активные префиксы команд: {prefixes}",
        "admin_cmds": "**Команды администратора**",
        "help_cmd": "Показывает это справочное сообщение.",
        "speedtest_cmd": "Измеряет скорость соединения.",
        "info_cmd": "Отображает информацию о боте.",
        "sign_cmd": "Подписывает отвеченный IPA-файл.",
        "clear_cmd": "Сбрасывает все параметры модификации.",
        "profile_cmd": "Удаляет встроенный мобильный профиль.",
        "minos_cmd": "Устанавливает минимальную требуемую версию ОС.",
        "id_cmd": "Изменяет идентификатор пакета приложения.",
        "version_cmd": "Изменяет версию приложения.",
        "name_cmd": "Изменяет название приложения.",
        "update_cmd": "Обновляет бота из репозитория.",
        "duyur_cmd": "Отправляет объявление всем пользователям.",
        "exec_cmd": "Выполняет команду оболочки.",
        "restart_cmd": "Перезапускает бота.",
        "shutdown_cmd": "Выключает бота.",
        "user_cmd": "Управляет регистрацией пользователей.",
        "premium_cmd": "Управляет статусом премиум-пользователей.",
        "unknown_exception": "Произошла ошибка при обработке запроса помощи от @{username} ({userID}): {error}"
    },
    "de": {
        "user_not_registered": "Du bist nicht registriert, um diesen Bot zu verwenden.",
        "available_cmds": "**Verfügbare Befehle**",
        "user_cmds": "**Benutzerbefehle**",
        "cmd_prefixes": "Aktive Befehlspräfixe: {prefixes}",
        "admin_cmds": "**Admin-Befehle**",
        "help_cmd": "Zeigt diese Hilfenachricht an.",
        "speedtest_cmd": "Misst die Verbindungsgeschwindigkeit.",
        "info_cmd": "Zeigt Informationen über den Bot an.",
        "sign_cmd": "Signiert die beantwortete IPA-Datei.",
        "clear_cmd": "Setzt alle Änderungsoptionen zurück.",
        "profile_cmd": "Entfernt die eingebettete mobile Bereitstellungsdatei.",
        "minos_cmd": "Legt die erforderliche Mindest-Betriebssystemversion fest.",
        "id_cmd": "Ändert die Bundle-ID der Anwendung.",
        "version_cmd": "Ändert die Version der Anwendung.",
        "name_cmd": "Ändert den Namen der Anwendung.",
        "update_cmd": "Aktualisiert den Bot aus dem Repository.",
        "duyur_cmd": "Sendet eine Ankündigung an alle Benutzer.",
        "exec_cmd": "Führt einen Shell-Befehl aus.",
        "restart_cmd": "Startet den Bot neu.",
        "shutdown_cmd": "Fährt den Bot herunter.",
        "user_cmd": "Verwaltet Benutzerregistrierungen.",
        "premium_cmd": "Verwaltet den Premium-Benutzerstatus.",
        "unknown_exception": "Bei der Verarbeitung der Hilfeanfrage von @{username} ({userID}) ist ein Fehler aufgetreten: {error}"
    },
    "es": {
        "user_not_registered": "No estás registrado para usar este bot.",
        "available_cmds": "**Comandos disponibles**",
        "user_cmds": "**Comandos de usuario**",
        "cmd_prefixes": "Prefijos de comando activos: {prefixes}",
        "admin_cmds": "**Comandos de administrador**",
        "help_cmd": "Muestra este mensaje de ayuda.",
        "speedtest_cmd": "Mide la velocidad de conexión.",
        "info_cmd": "Muestra información sobre el bot.",
        "sign_cmd": "Firma el archivo IPA respondido.",
        "clear_cmd": "Restablece todas las opciones de modificación.",
        "profile_cmd": "Elimina el archivo de aprovisionamiento móvil incrustado.",
        "minos_cmd": "Establece la versión mínima de SO requerida.",
        "id_cmd": "Cambia el ID de paquete de la aplicación.",
        "version_cmd": "Cambia la versión de la aplicación.",
        "name_cmd": "Cambia el nombre de la aplicación.",
        "update_cmd": "Actualiza el bot desde el repositorio.",
        "duyur_cmd": "Envía un anuncio a todos los usuarios.",
        "exec_cmd": "Ejecuta un comando de shell.",
        "restart_cmd": "Reinicia el bot.",
        "shutdown_cmd": "Apaga el bot.",
        "user_cmd": "Gestiona los registros de usuarios.",
        "premium_cmd": "Gestiona el estado de usuario premium.",
        "unknown_exception": "Ocurrió un error al procesar la solicitud de ayuda de @{username} ({userID}): {error}"
    },
    "fr": {
        "user_not_registered": "Vous n'êtes pas enregistré pour utiliser ce bot.",
        "available_cmds": "**Commandes disponibles**",
        "user_cmds": "**Commandes utilisateur**",
        "cmd_prefixes": "Préfixes de commande actifs: {prefixes}",
        "admin_cmds": "**Commandes administrateur**",
        "help_cmd": "Affiche ce message d'aide.",
        "speedtest_cmd": "Mesure la vitesse de connexion.",
        "info_cmd": "Affiche des informations sur le bot.",
        "sign_cmd": "Signe le fichier IPA répondu.",
        "clear_cmd": "Réinitialise toutes les options de modification.",
        "profile_cmd": "Supprime le fichier de provisionnement mobile intégré.",
        "minos_cmd": "Définit la version minimale du système d'exploitation requise.",
        "id_cmd": "Modifie l'ID de bundle de l'application.",
        "version_cmd": "Modifie la version de l'application.",
        "name_cmd": "Modifie le nom de l'application.",
        "update_cmd": "Met à jour le bot depuis le dépôt.",
        "duyur_cmd": "Envoie une annonce à tous les utilisateurs.",
        "exec_cmd": "Exécute une commande shell.",
        "restart_cmd": "Redémarre le bot.",
        "shutdown_cmd": "Arrête le bot.",
        "user_cmd": "Gère les enregistrements d'utilisateurs.",
        "premium_cmd": "Gère le statut d'utilisateur premium.",
        "unknown_exception": "Une erreur est survenue lors du traitement de la demande d'aide de @{username} ({userID}): {error}"
    },
    "zh-cn": {
        "user_not_registered": "您未注册使用此机器人。",
        "available_cmds": "**可用命令**",
        "user_cmds": "**用户命令**",
        "cmd_prefixes": "活动命令前缀: {prefixes}",
        "admin_cmds": "**管理员命令**",
        "help_cmd": "显示此帮助消息。",
        "speedtest_cmd": "测量连接速度。",
        "info_cmd": "显示有关机器人的信息。",
        "sign_cmd": "签名回复的 IPA 文件。",
        "clear_cmd": "重置所有修改选项。",
        "profile_cmd": "删除嵌入式移动配置文件。",
        "minos_cmd": "设置所需的最低操作系统版本。",
        "id_cmd": "更改应用程序的 Bundle ID。",
        "version_cmd": "更改应用程序的版本。",
        "name_cmd": "更改应用程序的名称。",
        "update_cmd": "从仓库更新机器人。",
        "duyur_cmd": "向所有用户发送公告。",
        "exec_cmd": "执行 shell 命令。",
        "restart_cmd": "重启机器人。",
        "shutdown_cmd": "关闭机器人。",
        "user_cmd": "管理用户注册。",
        "premium_cmd": "管理高级用户状态。",
        "unknown_exception": "处理来自 @{username} ({userID}) 的帮助请求时发生错误: {error}"
    },
    "ar": {
        "user_not_registered": "أنت غير مسجل لاستخدام هذا البوت.",
        "available_cmds": "**الأوامر المتاحة**",
        "user_cmds": "**أوامر المستخدم**",
        "cmd_prefixes": "بادئات الأوامر النشطة: {prefixes}",
        "admin_cmds": "**أوامر المسؤول**",
        "help_cmd": "يعرض رسالة المساعدة هذه.",
        "speedtest_cmd": "يقيس سرعة الاتصال.",
        "info_cmd": "يعرض معلومات حول البوت.",
        "sign_cmd": "يوقع ملف IPA الذي تم الرد عليه.",
        "clear_cmd": "يعيد تعيين جميع خيارات التعديل.",
        "profile_cmd": "يزيل ملف التزويد المحمول المضمن.",
        "minos_cmd": "يحدد الحد الأدنى لإصدار نظام التشغيل المطلوب.",
        "id_cmd": "يغير معرف حزمة التطبيق.",
        "version_cmd": "يغير إصدار التطبيق.",
        "name_cmd": "يغير اسم التطبيق.",
        "update_cmd": "يحدث البوت من المستودع.",
        "duyur_cmd": "يرسل إعلانًا لجميع المستخدمين.",
        "exec_cmd": "ينفذ أمر shell.",
        "restart_cmd": "يعيد تشغيل البوت.",
        "shutdown_cmd": "يغلق البوت.",
        "user_cmd": "يدير تسجيلات المستخدمين.",
        "premium_cmd": "يدير حالة المستخدم المميز.",
        "unknown_exception": "حدث خطأ أثناء معالجة طلب المساعدة من @{username} ({userID}): {error}"
    },
    "pt": {
        "user_not_registered": "You are not registered to use this bot.",
        "available_cmds": "**Available Commands**",
        "user_cmds": "**User Commands**",
        "cmd_prefixes": "Active command prefixes: {prefixes}",
        "admin_cmds": "**Admin Commands**",
        "help_cmd": "Shows this help message.",
        "speedtest_cmd": "Measures the connection speed.",
        "info_cmd": "Displays information about the bot.",
        "sign_cmd": "Signs the replied IPA file.",
        "clear_cmd": "Resets all modification options.",
        "profile_cmd": "Removes the embedded mobile provision file.",
        "minos_cmd": "Sets the minimum OS version required.",
        "id_cmd": "Changes the application's bundle ID.",
        "version_cmd": "Changes the application's version.",
        "name_cmd": "Changes the application's name.",
        "update_cmd": "Updates the bot from the repository.",
        "duyur_cmd": "Sends an announcement to all users.",
        "exec_cmd": "Executes a shell command.",
        "restart_cmd": "Restarts the bot.",
        "shutdown_cmd": "Shuts down the bot.",
        "user_cmd": "Manages user registrations.",
        "premium_cmd": "Manages premium user status.",
        "unknown_exception": "An error occurred while processing the help request from @{username} ({userID}): {error}"
    },
    "it": {
        "user_not_registered": "You are not registered to use this bot.",
        "available_cmds": "**Available Commands**",
        "user_cmds": "**User Commands**",
        "cmd_prefixes": "Active command prefixes: {prefixes}",
        "admin_cmds": "**Admin Commands**",
        "help_cmd": "Shows this help message.",
        "speedtest_cmd": "Measures the connection speed.",
        "info_cmd": "Displays information about the bot.",
        "sign_cmd": "Signs the replied IPA file.",
        "clear_cmd": "Resets all modification options.",
        "profile_cmd": "Removes the embedded mobile provision file.",
        "minos_cmd": "Sets the minimum OS version required.",
        "id_cmd": "Changes the application's bundle ID.",
        "version_cmd": "Changes the application's version.",
        "name_cmd": "Changes the application's name.",
        "update_cmd": "Updates the bot from the repository.",
        "duyur_cmd": "Sends an announcement to all users.",
        "exec_cmd": "Executes a shell command.",
        "restart_cmd": "Restarts the bot.",
        "shutdown_cmd": "Shuts down the bot.",
        "user_cmd": "Manages user registrations.",
        "premium_cmd": "Manages premium user status.",
        "unknown_exception": "An error occurred while processing the help request from @{username} ({userID}): {error}"
    },
    "ja": {
        "user_not_registered": "You are not registered to use this bot.",
        "available_cmds": "**Available Commands**",
        "user_cmds": "**User Commands**",
        "cmd_prefixes": "Active command prefixes: {prefixes}",
        "admin_cmds": "**Admin Commands**",
        "help_cmd": "Shows this help message.",
        "speedtest_cmd": "Measures the connection speed.",
        "info_cmd": "Displays information about the bot.",
        "sign_cmd": "Signs the replied IPA file.",
        "clear_cmd": "Resets all modification options.",
        "profile_cmd": "Removes the embedded mobile provision file.",
        "minos_cmd": "Sets the minimum OS version required.",
        "id_cmd": "Changes the application's bundle ID.",
        "version_cmd": "Changes the application's version.",
        "name_cmd": "Changes the application's name.",
        "update_cmd": "Updates the bot from the repository.",
        "duyur_cmd": "Sends an announcement to all users.",
        "exec_cmd": "Executes a shell command.",
        "restart_cmd": "Restarts the bot.",
        "shutdown_cmd": "Shuts down the bot.",
        "user_cmd": "Manages user registrations.",
        "premium_cmd": "Manages premium user status.",
        "unknown_exception": "An error occurred while processing the help request from @{username} ({userID}): {error}"
    },
    "ko": {
        "user_not_registered": "이 봇을 사용할 권한이 없습니다.",
        "available_cmds": "**사용 가능한 명령**",
        "user_cmds": "**사용자 명령**",
        "cmd_prefixes": "활성 명령 접두사: {prefixes}",
        "admin_cmds": "**관리자 명령**",
        "help_cmd": "이 도움말 메시지를 표시합니다.",
        "speedtest_cmd": "연결 속도를 측정합니다.",
        "info_cmd": "봇에 대한 정보를 표시합니다.",
        "sign_cmd": "회신된 IPA 파일에 서명합니다.",
        "clear_cmd": "모든 수정 옵션을 재설정합니다.",
        "profile_cmd": "내장된 모바일 프로비저닝 파일을 제거합니다.",
        "minos_cmd": "필요한 최소 OS 버전을 설정합니다.",
        "id_cmd": "애플리케이션의 번들 ID를 변경합니다.",
        "version_cmd": "애플리케이션의 버전을 변경합니다.",
        "name_cmd": "애플리케이션의 이름을 변경합니다.",
        "update_cmd": "저장소에서 봇을 업데이트합니다.",
        "duyur_cmd": "모든 사용자에게 공지를 보냅니다.",
        "exec_cmd": "셸 명령을 실행합니다.",
        "restart_cmd": "봇을 다시 시작합니다.",
        "shutdown_cmd": "봇을 종료합니다.",
        "user_cmd": "사용자 등록을 관리합니다.",
        "premium_cmd": "프리미엄 사용자 상태를 관리합니다.",
        "unknown_exception": "@{username} ({userID})의 도움말 요청을 처리하는 동안 오류가 발생했습니다: {error}"
    },
    "hi": {
        "user_not_registered": "आप इस बॉट का उपयोग करने के लिए पंजीकृत नहीं हैं।",
        "available_cmds": "**उपलब्ध कमांड**",
        "user_cmds": "**उपयोगकर्ता कमांड**",
        "cmd_prefixes": "सक्रिय कमांड उपसर्ग: {prefixes}",
        "admin_cmds": "**व्यवस्थापक कमांड**",
        "help_cmd": "यह सहायता संदेश दिखाता है।",
        "speedtest_cmd": "कनेक्शन की गति मापता है।",
        "info_cmd": "बॉट के बारे में जानकारी प्रदर्शित करता है।",
        "sign_cmd": "जवाब दिए गए IPA फ़ाइल पर हस्ताक्षर करता है।",
        "clear_cmd": "सभी संशोधन विकल्पों को रीसेट करता है।",
        "profile_cmd": "एम्बेडेड मोबाइल प्रोविजन फ़ाइल को हटाता है।",
        "minos_cmd": "आवश्यक न्यूनतम OS संस्करण सेट करता है।",
        "id_cmd": "एप्लिकेशन का बंडल आईडी बदलता है।",
        "version_cmd": "एप्लिकेशन का संस्करण बदलता है।",
        "name_cmd": "एप्लिकेशन का नाम बदलता है।",
        "update_cmd": "रिपॉजिटरी से बॉट को अपडेट करता है।",
        "duyur_cmd": "सभी उपयोगकर्ताओं को एक घोषणा भेजता है।",
        "exec_cmd": "एक शेल कमांड निष्पादित करता है।",
        "restart_cmd": "बॉट को पुनरारंभ करता है।",
        "shutdown_cmd": "बॉट को बंद करता है।",
        "user_cmd": "उपयोगकर्ता पंजीकरण का प्रबंधन करता है।",
        "premium_cmd": "प्रीमियम उपयोगकर्ता स्थिति का प्रबंधन करता है।",
        "unknown_exception": "@{username} ({userID}) से सहायता अनुरोध संसाधित करते समय एक त्रुटि हुई: {error}"
    },
    "vi": {
        "user_not_registered": "Bạn chưa đăng ký để sử dụng bot này.",
        "available_cmds": "**Các lệnh có sẵn**",
        "user_cmds": "**Lệnh người dùng**",
        "cmd_prefixes": "Tiền tố lệnh hoạt động: {prefixes}",
        "admin_cmds": "**Lệnh quản trị**",
        "help_cmd": "Hiển thị thông báo trợ giúp này.",
        "speedtest_cmd": "Đo tốc độ kết nối.",
        "info_cmd": "Hiển thị thông tin về bot.",
        "sign_cmd": "Ký tệp IPA đã trả lời.",
        "clear_cmd": "Đặt lại tất cả các tùy chọn sửa đổi.",
        "profile_cmd": "Xóa tệp cấu hình di động được nhúng.",
        "minos_cmd": "Đặt phiên bản OS tối thiểu được yêu cầu.",
        "id_cmd": "Thay đổi ID gói của ứng dụng.",
        "version_cmd": "Thay đổi phiên bản của ứng dụng.",
        "name_cmd": "Thay đổi tên của ứng dụng.",
        "update_cmd": "Cập nhật bot từ kho lưu trữ.",
        "duyur_cmd": "Gửi thông báo cho tất cả người dùng.",
        "exec_cmd": "Thực thi lệnh shell.",
        "restart_cmd": "Khởi động lại bot.",
        "shutdown_cmd": "Tắt bot.",
        "user_cmd": "Quản lý đăng ký người dùng.",
        "premium_cmd": "Quản lý trạng thái người dùng cao cấp.",
        "unknown_exception": "Đã xảy ra lỗi khi xử lý yêu cầu trợ giúp từ @{username} ({userID}): {error}"
    },
    "id": {
        "user_not_registered": "Anda belum terdaftar untuk menggunakan bot ini.",
        "available_cmds": "**Perintah yang Tersedia**",
        "user_cmds": "**Perintah Pengguna**",
        "cmd_prefixes": "Awalan perintah aktif: {prefixes}",
        "admin_cmds": "**Perintah Admin**",
        "help_cmd": "Menampilkan pesan bantuan ini.",
        "speedtest_cmd": "Mengukur kecepatan koneksi.",
        "info_cmd": "Menampilkan informasi tentang bot.",
        "sign_cmd": "Menandatangani file IPA yang dibalas.",
        "clear_cmd": "Mengatur ulang semua opsi modifikasi.",
        "profile_cmd": "Menghapus file provisi seluler yang disematkan.",
        "minos_cmd": "Mengatur versi OS minimum yang diperlukan.",
        "id_cmd": "Mengubah ID bundel aplikasi.",
        "version_cmd": "Mengubah versi aplikasi.",
        "name_cmd": "Mengubah nama aplikasi.",
        "update_cmd": "Memperbarui bot dari repositori.",
        "duyur_cmd": "Mengirim pengumuman ke semua pengguna.",
        "exec_cmd": "Mengeksekusi perintah shell.",
        "restart_cmd": "Memulai ulang bot.",
        "shutdown_cmd": "Mematikan bot.",
        "user_cmd": "Mengelola pendaftaran pengguna.",
        "premium_cmd": "Mengelola status pengguna premium.",
        "unknown_exception": "Terjadi kesalahan saat memproses permintaan bantuan dari @{username} ({userID}): {error}"
    },
    "pl": {
        "user_not_registered": "Nie jesteś zarejestrowany, aby korzystać z tego bota.",
        "available_cmds": "**Dostępne polecenia**",
        "user_cmds": "**Polecenia użytkownika**",
        "cmd_prefixes": "Aktywne prefiksy poleceń: {prefixes}",
        "admin_cmds": "**Polecenia administratora**",
        "help_cmd": "Wyświetla tę wiadomość pomocy.",
        "speedtest_cmd": "Mierzy prędkość połączenia.",
        "info_cmd": "Wyświetla informacje o bocie.",
        "sign_cmd": "Podpisuje odpowiedni plik IPA.",
        "clear_cmd": "Resetuje wszystkie opcje modyfikacji.",
        "profile_cmd": "Usuwa osadzony plik profilu mobilnego.",
        "minos_cmd": "Ustawia minimalną wymaganą wersję systemu operacyjnego.",
        "id_cmd": "Zmienia identyfikator pakietu aplikacji.",
        "version_cmd": "Zmienia wersję aplikacji.",
        "name_cmd": "Zmienia nazwę aplikacji.",
        "update_cmd": "Aktualizuje bota z repozytorium.",
        "duyur_cmd": "Wysyła ogłoszenie do wszystkich użytkowników.",
        "exec_cmd": "Wykonuje polecenie powłoki.",
        "restart_cmd": "Ponownie uruchamia bota.",
        "shutdown_cmd": "Wyłącza bota.",
        "user_cmd": "Zarządza rejestracjami użytkowników.",
        "premium_cmd": "Zarządza statusem użytkownika premium.",
        "unknown_exception": "Wystąpił błąd podczas przetwarzania żądania pomocy od @{username} ({userID}): {error}"
    },
    "nl": {
        "user_not_registered": "U bent niet geregistreerd om deze bot te gebruiken.",
        "available_cmds": "**Beschikbare commando's**",
        "user_cmds": "**Gebruikerscommando's**",
        "cmd_prefixes": "Actieve commandoprefixen: {prefixes}",
        "admin_cmds": "**Admin commando's**",
        "help_cmd": "Toont dit helpbericht.",
        "speedtest_cmd": "Meet de verbindingssnelheid.",
        "info_cmd": "Toont informatie over de bot.",
        "sign_cmd": "Ondertekent het beantwoorde IPA-bestand.",
        "clear_cmd": "Reset alle modificatie-opties.",
        "profile_cmd": "Verwijdert het ingebedde mobiele provisioneringsbestand.",
        "minos_cmd": "Stelt de minimaal vereiste OS-versie in.",
        "id_cmd": "Wijzigt de bundel-ID van de applicatie.",
        "version_cmd": "Wijzigt de versie van de applicatie.",
        "name_cmd": "Wijzigt de naam van de applicatie.",
        "update_cmd": "Werkt de bot bij vanuit de repository.",
        "duyur_cmd": "Verzendt een aankondiging naar alle gebruikers.",
        "exec_cmd": "Voert een shell-commando uit.",
        "restart_cmd": "Herstart de bot.",
        "shutdown_cmd": "Sluit de bot af.",
        "user_cmd": "Beheert gebruikersregistraties.",
        "premium_cmd": "Beheert de premium gebruikersstatus.",
        "unknown_exception": "Er is een fout opgetreden bij het verwerken van het helpverzoek van @{username} ({userID}): {error}"
    }
}
