# Plugins/info.py
info_strings = {
    "en": {
        "greeting": "👋 Hello, {name}!",
        "system_info": "\n**System Information**\n",
        "bot_info": "\n**Bot Information**\n",
        "bot_stats": "Uptime: {uptime}\nUsage: {usage}",
        "total_users": "Total Users: {count}",
        "active_users": "Active Users: {count}",
    },
    "tr": {
        "greeting": "👋 Merhaba, {name}!",
        "system_info": "\n**Sistem Bilgileri**\n",
        "bot_info": "\n**Bot Bilgileri**\n",
        "bot_stats": "Çalışma Süresi: {uptime}\nKullanım: {usage}",
        "total_users": "Toplam Kullanıcı: {count}",
        "active_users": "Aktif Kullanıcı: {count}",
    },
    "ru": {
        "greeting": "👋 Здравствуйте, {name}!",
        "system_info": "\n**Информация о системе**\n",
        "bot_info": "\n**Информация о боте**\n",
        "bot_stats": "Время работы: {uptime}\nИспользование: {usage}",
        "total_users": "Всего пользователей: {count}",
        "active_users": "Активные пользователи: {count}",
    },
    "de": {
        "greeting": "👋 Hallo, {name}!",
        "system_info": "\n**Systeminformationen**\n",
        "bot_info": "\n**Bot-Informationen**\n",
        "bot_stats": "Betriebszeit: {uptime}\nNutzung: {usage}",
        "total_users": "Gesamte Benutzer: {count}",
        "active_users": "Aktive Benutzer: {count}",
    },
    "es": {
        "greeting": "👋 ¡Hola, {name}!",
        "system_info": "\n**Información del sistema**\n",
        "bot_info": "\n**Información del bot**\n",
        "bot_stats": "Tiempo de actividad: {uptime}\nUso: {usage}",
        "total_users": "Usuarios totales: {count}",
        "active_users": "Usuarios activos: {count}",
    },
    "fr": {
        "greeting": "👋 Bonjour, {name}!",
        "system_info": "\n**Informations système**\n",
        "bot_info": "\n**Informations sur le bot**\n",
        "bot_stats": "Temps de fonctionnement: {uptime}\nUtilisation: {usage}",
        "total_users": "Utilisateurs totaux: {count}",
        "active_users": "Utilisateurs actifs: {count}",
    },
    "zh-cn": {
        "greeting": "👋 你好, {name}!",
        "system_info": "\n**系统信息**\n",
        "bot_info": "\n**机器人信息**\n",
        "bot_stats": "运行时间: {uptime}\n使用情况: {usage}",
        "total_users": "总用户: {count}",
        "active_users": "活跃用户: {count}",
    },
    "ar": {
        "greeting": "👋 مرحبًا، {name}!",
        "system_info": "\n**معلومات النظام**\n",
        "bot_info": "\n**معلومات البوت**\n",
        "bot_stats": "وقت التشغيل: {uptime}\nالاستخدام: {usage}",
        "total_users": "إجمالي المستخدمين: {count}",
        "active_users": "المستخدمون النشطون: {count}",
    },
    "pt": {
        "greeting": "👋 Hello, {name}!",
        "system_info": "\n**System Information**\n",
        "bot_info": "\n**Bot Information**\n",
        "bot_stats": "Uptime: {uptime}\nUsage: {usage}",
        "total_users": "Total Users: {count}",
        "active_users": "Active Users: {count}",
    },
    "it": {
        "greeting": "👋 Hello, {name}!",
        "system_info": "\n**System Information**\n",
        "bot_info": "\n**Bot Information**\n",
        "bot_stats": "Uptime: {uptime}\nUsage: {usage}",
        "total_users": "Total Users: {count}",
        "active_users": "Active Users: {count}",
    },
    "ja": {
        "greeting": "👋 こんにちは、{name}さん!",
        "system_info": "\n**システム情報**\n",
        "bot_info": "\n**ボット情報**\n",
        "bot_stats": "稼働時間: {uptime}\n使用状況: {usage}",
        "total_users": "総ユーザー数: {count}",
        "active_users": "アクティブユーザー: {count}",
    },
    "ko": {
        "greeting": "👋 안녕하세요, {name}님!",
        "system_info": "\n**시스템 정보**\n",
        "bot_info": "\n**봇 정보**\n",
        "bot_stats": "업타임: {uptime}\n사용량: {usage}",
        "total_users": "총 사용자: {count}",
        "active_users": "활성 사용자: {count}",
    },
    "hi": {
        "greeting": "👋 नमस्ते, {name}!",
        "system_info": "\n**सिस्टम जानकारी**\n",
        "bot_info": "\n**बॉट जानकारी**\n",
        "bot_stats": "अपटाइम: {uptime}\nउपयोग: {usage}",
        "total_users": "कुल उपयोगकर्ता: {count}",
        "active_users": "सक्रिय उपयोगकर्ता: {count}",
    },
    "vi": {
        "greeting": "👋 Xin chào, {name}!",
        "system_info": "\n**Thông tin hệ thống**\n",
        "bot_info": "\n**Thông tin Bot**\n",
        "bot_stats": "Thời gian hoạt động: {uptime}\nSử dụng: {usage}",
        "total_users": "Tổng số người dùng: {count}",
        "active_users": "Người dùng hoạt động: {count}",
    },
    "id": {
        "greeting": "👋 Halo, {name}!",
        "system_info": "\n**Informasi Sistem**\n",
        "bot_info": "\n**Informasi Bot**\n",
        "bot_stats": "Waktu Aktif: {uptime}\nPenggunaan: {usage}",
        "total_users": "Total Pengguna: {count}",
        "active_users": "Pengguna Aktif: {count}",
    },
    "pl": {
        "greeting": "👋 Witaj, {name}!",
        "system_info": "\n**Informacje o systemie**\n",
        "bot_info": "\n**Informacje o bocie**\n",
        "bot_stats": "Czas działania: {uptime}\nUżycie: {usage}",
        "total_users": "Całkowita liczba użytkowników: {count}",
        "active_users": "Aktywni użytkownicy: {count}",
    },
    "nl": {
        "greeting": "👋 Hallo, {name}!",
        "system_info": "\n**Systeeminformatie**\n",
        "bot_info": "\n**Botinformatie**\n",
        "bot_stats": "Uptime: {uptime}\nGebruik: {usage}",
        "total_users": "Totaal aantal gebruikers: {count}",
        "active_users": "Actieve gebruikers: {count}",
    }
}
