# Plugins/language_select.py
language_select_strings = {
    "en": {
        "select_language": "🌐 **Select a Language**",
        "selected": "Selected:",
        "already_selected": "⚠️ This language is already selected.",
        "save_failed": "⚠️ Could not save the language setting.",
        "new_language_selected": "🌐 Language changed successfully.",
        "error_in_language_selection": "⚠️ An error occurred during language selection.",
        "database_error": "A database error occurred. Please try again.",
        "language_clear_success": "Language preference cleared. The bot will now use your client's language.",
        "language_clear_failed": "No language preference was set.",
        "back_button": "🔙 Go Back",
        "clear_button": "🧹 Clear Selection"
    },
    "tr": {
        "select_language": "🌐 **Bir Dil Seçin**",
        "selected": "Seçili:",
        "already_selected": "⚠️ Bu dil zaten seçili.",
        "save_failed": "⚠️ Dil ayarı kaydedilemedi.",
        "new_language_selected": "🌐 Dil başarıyla değiştirildi.",
        "error_in_language_selection": "Dil seçimi sırasında bir hata oluştu.",
        "database_error": "Bir veritabanı hatası oluştu. Lütfen tekrar deneyin.",
        "language_clear_success": "Dil tercihi temizlendi. Bot artık istemci dilinizi kullanacak.",
        "language_clear_failed": "Ayarlanmış bir dil tercihi yoktu.",
        "back_button": "🔙 Geri Dön",
        "clear_button": "🧹 Seçimi Temizle"
    },
    "ru": {
        "select_language": "🌐 **Выберите язык**",
        "selected": "Выбрано:",
        "already_selected": "⚠️ Этот язык уже выбран.",
        "save_failed": "⚠️ Не удалось сохранить настройку языка.",
        "new_language_selected": "🌐 Язык успешно изменен.",
        "error_in_language_selection": "⚠️ Произошла ошибка при выборе языка.",
        "database_error": "Произошла ошибка базы данных. Пожалуйста, попробуйте еще раз.",
        "language_clear_success": "Языковые предпочтения сброшены. Бот теперь будет использовать язык вашего клиента.",
        "language_clear_failed": "Языковые предпочтения не были установлены.",
        "back_button": "🔙 Назад",
        "clear_button": "🧹 Очистить выбор",
    },
    "de": {
        "select_language": "🌐 **Sprache auswählen**",
        "selected": "Ausgewählt:",
        "already_selected": "⚠️ Diese Sprache ist bereits ausgewählt.",
        "save_failed": "⚠️ Spracheinstellung konnte nicht gespeichert werden.",
        "new_language_selected": "🌐 Sprache erfolgreich geändert.",
        "error_in_language_selection": "Bei der Sprachauswahl ist ein Fehler aufgetreten.",
        "database_error": "Ein Datenbankfehler ist aufgetreten. Bitte versuche es erneut.",
        "language_clear_success": "Spracheinstellung gelöscht. Der Bot verwendet nun die Sprache deines Clients.",
        "language_clear_failed": "Es war keine Spracheinstellung festgelegt.",
        "back_button": "🔙 Zurück",
        "clear_button": "🧹 Auswahl löschen",
    },
    "es": {
        "select_language": "🌐 **Seleccionar un idioma**",
        "selected": "Seleccionado:",
        "already_selected": "⚠️ Este idioma ya está seleccionado.",
        "save_failed": "⚠️ No se pudo guardar la configuración de idioma.",
        "new_language_selected": "🌐 Idioma cambiado exitosamente.",
        "error_in_language_selection": "⚠️ Ocurrió un error durante la selección de idioma.",
        "database_error": "Ocurrió un error en la base de datos. Por favor, inténtalo de nuevo.",
        "language_clear_success": "Preferencia de idioma borrada. El bot ahora usará el idioma de tu cliente.",
        "language_clear_failed": "No se estableció ninguna preferencia de idioma.",
        "back_button": "🔙 Volver",
        "clear_button": "🧹 Borrar selección"
    },
    "fr": {
        "select_language": "🌐 **Sélectionner une langue**",
        "selected": "Sélectionné:",
        "already_selected": "⚠️ Cette langue est déjà sélectionnée.",
        "save_failed": "⚠️ Impossible d'enregistrer le paramètre de langue.",
        "new_language_selected": "🌐 Langue changée avec succès.",
        "error_in_language_selection": "⚠️ Une erreur est survenue lors de la sélection de la langue.",
        "database_error": "Une erreur de base de données est survenue. Veuillez réessayer.",
        "language_clear_success": "Préférence linguistique effacée. Le bot utilisera maintenant la langue de votre client.",
        "language_clear_failed": "Aucune préférence linguistique n'a été définie.",
        "back_button": "🔙 Retour",
        "clear_button": "🧹 Effacer la sélection"
    },
    "zh-cn": {
        "select_language": "🌐 **选择语言**",
        "selected": "已选择:",
        "already_selected": "⚠️ 此语言已被选中。",
        "save_failed": "⚠️ 无法保存语言设置。",
        "new_language_selected": "🌐 语言已成功更改。",
        "error_in_language_selection": "⚠️ 语言选择过程中发生错误。",
        "database_error": "发生数据库错误。请重试。",
        "language_clear_success": "语言偏好已清除。机器人现在将使用您客户端的语言。",
        "language_clear_failed": "未设置语言偏好。",
        "back_button": "🔙 返回",
        "clear_button": "🧹 清除选择"
    },
    "ar": {
        "select_language": "🌐 **اختر لغة**",
        "selected": "المحدد:",
        "already_selected": "⚠️ هذه اللغة محددة بالفعل.",
        "save_failed": "⚠️ تعذر حفظ إعداد اللغة.",
        "new_language_selected": "🌐 تم تغيير اللغة بنجاح.",
        "error_in_language_selection": "⚠️ حدث خطأ أثناء اختيار اللغة.",
        "database_error": "حدث خطأ في قاعدة البيانات. الرجاء المحاولة مرة أخرى.",
        "language_clear_success": "تم مسح تفضيل اللغة. سيستخدم البوت الآن لغة عميلك.",
        "language_clear_failed": "لم يتم تعيين تفضيل اللغة.",
        "back_button": "🔙 رجوع",
        "clear_button": "🧹 مسح التحديد"
    },
    "pt": {
        "select_language": "🌐 **Selecionar um idioma**",
        "selected": "Selecionado:",
        "already_selected": "⚠️ Este idioma já está selecionado.",
        "save_failed": "⚠️ Não foi possível salvar a configuração de idioma.",
        "new_language_selected": "🌐 Idioma alterado com sucesso.",
        "error_in_language_selection": "⚠️ Ocorreu um erro durante a seleção do idioma.",
        "database_error": "Ocorreu um erro no banco de dados. Por favor, tente novamente.",
        "language_clear_success": "Preferência de idioma limpa. O bot agora usará o idioma do seu cliente.",
        "language_clear_failed": "Nenhuma preferência de idioma foi definida.",
        "back_button": "🔙 Voltar",
        "clear_button": "🧹 Limpar Seleção"
    },
    "it": {
        "select_language": "🌐 **Seleziona una lingua**",
        "selected": "Selezionato:",
        "already_selected": "⚠️ Questa lingua è già selezionata.",
        "save_failed": "⚠️ Impossibile salvare l'impostazione della lingua.",
        "new_language_selected": "🌐 Lingua cambiata con successo.",
        "error_in_language_selection": "⚠️ Si è verificato un errore durante la selezione della lingua.",
        "database_error": "Si è verificato un errore nel database. Si prega di riprovare.",
        "language_clear_success": "Preferenza lingua cancellata. Il bot ora userà la lingua del tuo client.",
        "language_clear_failed": "Nessuna preferenza di lingua è stata impostata.",
        "back_button": "🔙 Indietro",
        "clear_button": "🧹 Cancella Selezione"
    },
    "ja": {
        "select_language": "🌐 **言語を選択**",
        "selected": "選択済み:",
        "already_selected": "⚠️ この言語はすでに選択されています。",
        "save_failed": "⚠️ 言語設定を保存できませんでした。",
        "new_language_selected": "🌐 言語が正常に変更されました。",
        "error_in_language_selection": "⚠️ 言語選択中にエラーが発生しました。",
        "database_error": "データベースエラーが発生しました。もう一度お試しください。",
        "language_clear_success": "言語設定がクリアされました。ボットはクライアントの言語を使用します。",
        "language_clear_failed": "言語設定がされていませんでした。",
        "back_button": "🔙 戻る",
        "clear_button": "🧹 選択をクリア"
    },
    "ko": {
        "select_language": "🌐 **언어 선택**",
        "selected": "선택됨:",
        "already_selected": "⚠️ 이 언어는 이미 선택되었습니다.",
        "save_failed": "⚠️ 언어 설정을 저장할 수 없습니다.",
        "new_language_selected": "🌐 언어가 성공적으로 변경되었습니다.",
        "error_in_language_selection": "⚠️ 언어 선택 중 오류가 발생했습니다.",
        "database_error": "데이터베이스 오류가 발생했습니다. 다시 시도하십시오.",
        "language_clear_success": "언어 기본 설정이 지워졌습니다. 이제 봇이 클라이언트의 언어를 사용합니다.",
        "language_clear_failed": "언어 기본 설정이 지정되지 않았습니다.",
        "back_button": "🔙 뒤로",
        "clear_button": "🧹 선택 지우기"
    },
    "hi": {
        "select_language": "🌐 **एक भाषा चुनें**",
        "selected": "चयनित:",
        "already_selected": "⚠️ यह भाषा पहले से ही चयनित है।",
        "save_failed": "⚠️ भाषा सेटिंग सहेजी नहीं जा सकी।",
        "new_language_selected": "🌐 भाषा सफलतापूर्वक बदल दी गई।",
        "error_in_language_selection": "⚠️ भाषा चयन के दौरान एक त्रुटि हुई।",
        "database_error": "एक डेटाबेस त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "language_clear_success": "भाषा वरीयता साफ़ कर दी गई। बॉट अब आपके क्लाइंट की भाषा का उपयोग करेगा।",
        "language_clear_failed": "कोई भाषा वरीयता सेट नहीं की गई थी।",
        "back_button": "🔙 वापस जाएं",
        "clear_button": "🧹 चयन साफ़ करें"
    },
    "vi": {
        "select_language": "🌐 **Chọn ngôn ngữ**",
        "selected": "Đã chọn:",
        "already_selected": "⚠️ Ngôn ngữ này đã được chọn.",
        "save_failed": "⚠️ Không thể lưu cài đặt ngôn ngữ.",
        "new_language_selected": "🌐 Ngôn ngữ đã được thay đổi thành công.",
        "error_in_language_selection": "⚠️ Đã xảy ra lỗi trong quá trình chọn ngôn ngữ.",
        "database_error": "Đã xảy ra lỗi cơ sở dữ liệu. Vui lòng thử lại.",
        "language_clear_success": "Tùy chọn ngôn ngữ đã được xóa. Bot bây giờ sẽ sử dụng ngôn ngữ của máy khách của bạn.",
        "language_clear_failed": "Không có tùy chọn ngôn ngữ nào được đặt.",
        "back_button": "🔙 Quay lại",
        "clear_button": "🧹 Xóa lựa chọn"
    },
    "id": {
        "select_language": "🌐 **Pilih Bahasa**",
        "selected": "Terpilih:",
        "already_selected": "⚠️ Bahasa ini sudah dipilih.",
        "save_failed": "⚠️ Tidak dapat menyimpan pengaturan bahasa.",
        "new_language_selected": "🌐 Bahasa berhasil diubah.",
        "error_in_language_selection": "⚠️ Terjadi kesalahan selama pemilihan bahasa.",
        "database_error": "Terjadi kesalahan database. Silakan coba lagi.",
        "language_clear_success": "Preferensi bahasa dihapus. Bot sekarang akan menggunakan bahasa klien Anda.",
        "language_clear_failed": "Tidak ada preferensi bahasa yang ditetapkan.",
        "back_button": "🔙 Kembali",
        "clear_button": "🧹 Hapus Pilihan"
    },
    "pl": {
        "select_language": "🌐 **Wybierz język**",
        "selected": "Wybrano:",
        "already_selected": "⚠️ Ten język jest już wybrany.",
        "save_failed": "⚠️ Nie można zapisać ustawień języka.",
        "new_language_selected": "🌐 Język zmieniono pomyślnie.",
        "error_in_language_selection": "⚠️ Wystąpił błąd podczas wyboru języka.",
        "database_error": "Wystąpił błąd bazy danych. Proszę spróbować ponownie.",
        "language_clear_success": "Preferencje językowe zostały wyczyszczone. Bot będzie teraz używał języka Twojego klienta.",
        "language_clear_failed": "Nie ustawiono preferencji językowych.",
        "back_button": "🔙 Wróć",
        "clear_button": "🧹 Wyczyść zaznaczenie"
    },
    "nl": {
        "select_language": "🌐 **Selecteer een taal**",
        "selected": "Geselecteerd:",
        "already_selected": "⚠️ Deze taal is al geselecteerd.",
        "save_failed": "⚠️ Kon de taalinstelling niet opslaan.",
        "new_language_selected": "🌐 Taal succesvol gewijzigd.",
        "error_in_language_selection": "⚠️ Er is een fout opgetreden tijdens de taalkeuze.",
        "database_error": "Er is een databasefout opgetreden. Probeer het opnieuw.",
        "language_clear_success": "Taalvoorkeur gewist. De bot zal nu de taal van uw client gebruiken.",
        "language_clear_failed": "Er was geen taalvoorkeur ingesteld.",
        "back_button": "🔙 Terug",
        "clear_button": "🧹 Selectie wissen"
    }
}
