# Plugins/modifier.py
modifier_strings = {
    "en": {
        "save_error": "Could not save {options}. Error: {error}.",
        "update_error": "Could not update {options}. Error: {error}.",
        "app_name_usage": "Usage: /name [new app name]",
        "unset_app_name": "App name modification has been reset.",
        "set_app_name": "App name will be changed to **{name}**.",
        "app_version_usage": "Usage: /version [new version]",
        "invalid_app_version": "Invalid version format. Please use numbers and dots only (e.g., 1.2.3).",
        "unset_app_version": "App version modification has been reset.",
        "set_app_version": "App version will be changed to **{version}**.",
        "app_id_usage": "Usage: /id [new bundle ID]",
        "unset_app_id": "Bundle ID modification has been reset.",
        "set_app_id": "Bundle ID will be changed to **{id}**.",
        "min_os_usage": "Usage: /minos [version]",
        "invalid_min_os": "Invalid OS version format. Please use numbers and dots only (e.g., 15.0).",
        "unset_min_os": "Minimum OS version modification has been reset.",
        "set_min_os": "Minimum OS version will be set to **{os_version}**.",
        "unset_profile_removal": "Embedded profile will no longer be removed.",
        "set_profile_removal": "Embedded profile will be removed.",
        "tweak_added_expecting_ipa": "Tweak added: {file_name}. Now send the IPA file to apply it.",
        "error_while_resetting": "An error occurred while resetting options: {error}."
    },
    "tr": {
        "save_error": "{options} kaydedilemedi. Hata: {error}.",
        "update_error": "{options} güncellenemedi. Hata: {error}.",
        "app_name_usage": "Kullanım: /name [yeni uygulama adı]",
        "unset_app_name": "Uygulama adı değişikliği sıfırlandı.",
        "set_app_name": "Uygulama adı **{name}** olarak değiştirilecek.",
        "app_version_usage": "Kullanım: /version [yeni sürüm]",
        "invalid_app_version": "Geçersiz sürüm formatı. Lütfen sadece rakam ve nokta kullanın (örn. 1.2.3).",
        "unset_app_version": "Uygulama sürümü değişikliği sıfırlandı.",
        "set_app_version": "Uygulama sürümü **{version}** olarak değiştirilecek.",
        "app_id_usage": "Kullanım: /id [yeni paket kimliği]",
        "unset_app_id": "Paket kimliği değişikliği sıfırlandı.",
        "set_app_id": "Paket kimliği **{id}** olarak değiştirilecek.",
        "min_os_usage": "Kullanım: /minos [sürüm]",
        "invalid_min_os": "Geçersiz işletim sistemi sürüm formatı. Lütfen sadece rakam ve nokta kullanın (örn. 15.0).",
        "unset_min_os": "Minimum işletim sistemi sürümü değişikliği sıfırlandı.",
        "set_min_os": "Minimum işletim sistemi sürümü **{os_version}** olarak ayarlanacak.",
        "unset_profile_removal": "Gömülü profil artık kaldırılmayacak.",
        "set_profile_removal": "Gömülü profil kaldırılacak.",
        "tweak_added_expecting_ipa": "Tweak eklendi: {file_name}. Şimdi uygulamak için IPA dosyasını gönderin.",
        "error_while_resetting": "Seçenekler sıfırlanırken bir hata oluştu: {error}."
    },
    "ru": {
        "save_error": "Не удалось сохранить {options}. Ошибка: {error}.",
        "update_error": "Не удалось обновить {options}. Ошибка: {error}.",
        "app_name_usage": "Использование: /name [новое название приложения]",
        "unset_app_name": "Изменение названия приложения сброшено.",
        "set_app_name": "Название приложения будет изменено на **{name}**.",
        "app_version_usage": "Использование: /version [новая версия]",
        "invalid_app_version": "Неверный формат версии. Используйте только цифры и точки (например, 1.2.3).",
        "unset_app_version": "Изменение версии приложения сброшено.",
        "set_app_version": "Версия приложения будет изменена на **{version}**.",
        "app_id_usage": "Использование: /id [новый идентификатор пакета]",
        "unset_app_id": "Изменение идентификатора пакета сброшено.",
        "set_app_id": "Идентификатор пакета будет изменен на **{id}**.",
        "min_os_usage": "Использование: /minos [версия]",
        "invalid_min_os": "Неверный формат версии ОС. Используйте только цифры и точки (например, 15.0).",
        "unset_min_os": "Изменение минимальной версии ОС сброшено.",
        "set_min_os": "Минимальная версия ОС будет установлена на **{os_version}**.",
        "unset_profile_removal": "Встроенный профиль больше не будет удаляться.",
        "set_profile_removal": "Встроенный профиль будет удален.",
        "tweak_added_expecting_ipa": "Твик добавлен: {file_name}. Теперь отправьте IPA-файл, чтобы применить его.",
        "error_while_resetting": "Произошла ошибка при сбросе настроек: {error}."
    },
    "de": {
        "save_error": "Konnte {options} nicht speichern. Fehler: {error}.",
        "update_error": "Konnte {options} nicht aktualisieren. Fehler: {error}.",
        "app_name_usage": "Verwendung: /name [neuer App-Name]",
        "unset_app_name": "Änderung des App-Namens wurde zurückgesetzt.",
        "set_app_name": "Der App-Name wird in **{name}** geändert.",
        "app_version_usage": "Verwendung: /version [neue Version]",
        "invalid_app_version": "Ungültiges Versionsformat. Bitte nur Zahlen und Punkte verwenden (z.B. 1.2.3).",
        "unset_app_version": "Änderung der App-Version wurde zurückgesetzt.",
        "set_app_version": "Die App-Version wird in **{version}** geändert.",
        "app_id_usage": "Verwendung: /id [neue Bundle-ID]",
        "unset_app_id": "Änderung der Bundle-ID wurde zurückgesetzt.",
        "set_app_id": "Die Bundle-ID wird in **{id}** geändert.",
        "min_os_usage": "Verwendung: /minos [Version]",
        "invalid_min_os": "Ungültiges Betriebssystem-Versionsformat. Bitte nur Zahlen und Punkte verwenden (z.B. 15.0).",
        "unset_min_os": "Änderung der Mindest-Betriebssystemversion wurde zurückgesetzt.",
        "set_min_os": "Die Mindest-Betriebssystemversion wird auf **{os_version}** gesetzt.",
        "unset_profile_removal": "Eingebettetes Profil wird nicht mehr entfernt.",
        "set_profile_removal": "Eingebettetes Profil wird entfernt.",
        "tweak_added_expecting_ipa": "Tweak hinzugefügt: {file_name}. Senden Sie jetzt die IPA-Datei, um ihn anzuwenden.",
        "error_while_resetting": "Beim Zurücksetzen der Optionen ist ein Fehler aufgetreten: {error}."
    },
    "es": {
        "save_error": "No se pudo guardar {options}. Error: {error}.",
        "update_error": "No se pudo actualizar {options}. Error: {error}.",
        "app_name_usage": "Uso: /name [nuevo nombre de la aplicación]",
        "unset_app_name": "La modificación del nombre de la aplicación ha sido restablecida.",
        "set_app_name": "El nombre de la aplicación se cambiará a **{name}**.",
        "app_version_usage": "Uso: /version [nueva versión]",
        "invalid_app_version": "Formato de versión no válido. Utilice solo números y puntos (por ejemplo, 1.2.3).",
        "unset_app_version": "La modificación de la versión de la aplicación ha sido restablecida.",
        "set_app_version": "La versión de la aplicación se cambiará a **{version}**.",
        "app_id_usage": "Uso: /id [nuevo ID de paquete]",
        "unset_app_id": "La modificación del ID de paquete ha sido restablecida.",
        "set_app_id": "El ID de paquete se cambiará a **{id}**.",
        "min_os_usage": "Uso: /minos [versión]",
        "invalid_min_os": "Formato de versión de SO no válido. Utilice solo números y puntos (por ejemplo, 15.0).",
        "unset_min_os": "La modificación de la versión mínima de SO ha sido restablecida.",
        "set_min_os": "La versión mínima de SO se establecerá en **{os_version}**.",
        "unset_profile_removal": "El perfil incrustado ya no se eliminará.",
        "set_profile_removal": "El perfil incrustado se eliminará.",
        "tweak_added_expecting_ipa": "Tweak añadido: {file_name}. Ahora envía el archivo IPA para aplicarlo.",
        "error_while_resetting": "Ocurrió un error al restablecer las opciones: {error}."
    },
    "fr": {
        "save_error": "Impossible d'enregistrer {options}. Erreur: {error}.",
        "update_error": "Impossible de mettre à jour {options}. Erreur: {error}.",
        "app_name_usage": "Utilisation: /name [nouveau nom d'application]",
        "unset_app_name": "La modification du nom de l'application a été réinitialisée.",
        "set_app_name": "Le nom de l'application sera changé en **{name}**.",
        "app_version_usage": "Utilisation: /version [nouvelle version]",
        "invalid_app_version": "Format de version invalide. Veuillez utiliser uniquement des chiffres et des points (par exemple, 1.2.3).",
        "unset_app_version": "La modification de la version de l'application a été réinitialisée.",
        "set_app_version": "La version de l'application sera changée en **{version}**.",
        "app_id_usage": "Utilisation: /id [nouvel ID de bundle]",
        "unset_app_id": "La modification de l'ID de bundle a été réinitialisée.",
        "set_app_id": "L'ID de bundle sera changé en **{id}**.",
        "min_os_usage": "Utilisation: /minos [version]",
        "invalid_min_os": "Format de version OS invalide. Veuillez utiliser uniquement des chiffres et des points (par exemple, 15.0).",
        "unset_min_os": "La modification de la version minimale de l'OS a été réinitialisée.",
        "set_min_os": "La version minimale de l'OS sera définie sur **{os_version}**.",
        "unset_profile_removal": "Le profil intégré ne sera plus supprimé.",
        "set_profile_removal": "Le profil intégré sera supprimé.",
        "tweak_added_expecting_ipa": "Tweak ajouté: {file_name}. Envoyez maintenant le fichier IPA pour l'appliquer.",
        "error_while_resetting": "Une erreur est survenue lors de la réinitialisation des options: {error}."
    },
    "zh-cn": {
        "save_error": "无法保存 {options}。错误: {error}。",
        "update_error": "无法更新 {options}。错误: {error}。",
        "app_name_usage": "用法: /name [新应用名称]",
        "unset_app_name": "应用名称修改已重置。",
        "set_app_name": "应用名称将更改为 **{name}**。",
        "app_version_usage": "用法: /version [新版本]",
        "invalid_app_version": "版本格式无效。请仅使用数字和点（例如，1.2.3）。",
        "unset_app_version": "应用版本修改已重置。",
        "set_app_version": "应用版本将更改为 **{version}**。",
        "app_id_usage": "用法: /id [新 Bundle ID]",
        "unset_app_id": "Bundle ID 修改已重置。",
        "set_app_id": "Bundle ID 将更改为 **{id}**。",
        "min_os_usage": "用法: /minos [版本]",
        "invalid_min_os": "操作系统版本格式无效。请仅使用数字和点（例如，15.0）。",
        "unset_min_os": "最低操作系统版本修改已重置。",
        "set_min_os": "最低操作系统版本将设置为 **{os_version}**。",
        "unset_profile_removal": "嵌入式配置文件将不再被移除。",
        "set_profile_removal": "嵌入式配置文件将被移除。",
        "tweak_added_expecting_ipa": "已添加 Tweak: {file_name}。现在发送 IPA 文件以应用它。",
        "error_while_resetting": "重置选项时发生错误: {error}。"
    },
    "ar": {
        "save_error": "تعذر حفظ {options}. خطأ: {error}.",
        "update_error": "تعذر تحديث {options}. خطأ: {error}.",
        "app_name_usage": "الاستخدام: /name [اسم التطبيق الجديد]",
        "unset_app_name": "تمت إعادة تعيين تعديل اسم التطبيق.",
        "set_app_name": "سيتم تغيير اسم التطبيق إلى **{name}**.",
        "app_version_usage": "الاستخدام: /version [الإصدار الجديد]",
        "invalid_app_version": "تنسيق الإصدار غير صالح. الرجاء استخدام الأرقام والنقاط فقط (مثال: 1.2.3).",
        "unset_app_version": "تمت إعادة تعيين تعديل إصدار التطبيق.",
        "set_app_version": "سيتم تغيير إصدار التطبيق إلى **{version}**.",
        "app_id_usage": "الاستخدام: /id [معرف الحزمة الجديد]",
        "unset_app_id": "تمت إعادة تعيين تعديل معرف الحزمة.",
        "set_app_id": "سيتم تغيير معرف الحزمة إلى **{id}**.",
        "min_os_usage": "الاستخدام: /minos [الإصدار]",
        "invalid_min_os": "تنسيق إصدار نظام التشغيل غير صالح. الرجاء استخدام الأرقام والنقاط فقط (مثال: 15.0).",
        "unset_min_os": "تمت إعادة تعيين تعديل الحد الأدنى لإصدار نظام التشغيل.",
        "set_min_os": "سيتم تعيين الحد الأدنى لإصدار نظام التشغيل إلى **{os_version}**.",
        "unset_profile_removal": "لن يتم إزالة ملف التعريف المضمن بعد الآن.",
        "set_profile_removal": "سيتم إزالة ملف التعريف المضمن.",
        "tweak_added_expecting_ipa": "تمت إضافة التعديل: {file_name}. الآن أرسل ملف IPA لتطبيقه.",
        "error_while_resetting": "حدث خطأ أثناء إعادة تعيين الخيارات: {error}."
    },
    "pt": {
        "save_error": "Não foi possível salvar {options}. Erro: {error}.",
        "update_error": "Não foi possível atualizar {options}. Erro: {error}.",
        "app_name_usage": "Uso: /name [novo nome do aplicativo]",
        "unset_app_name": "A modificação do nome do aplicativo foi redefinida.",
        "set_app_name": "O nome do aplicativo será alterado para **{name}**.",
        "app_version_usage": "Uso: /version [nova versão]",
        "invalid_app_version": "Formato de versão inválido. Por favor, use apenas números e pontos (ex: 1.2.3).",
        "unset_app_version": "A modificação da versão do aplicativo foi redefinida.",
        "set_app_version": "A versão do aplicativo será alterada para **{version}**.",
        "app_id_usage": "Uso: /id [novo ID do pacote]",
        "unset_app_id": "A modificação do ID do pacote foi redefinida.",
        "set_app_id": "O ID do pacote será alterado para **{id}**.",
        "min_os_usage": "Uso: /minos [versão]",
        "invalid_min_os": "Formato de versão do SO inválido. Por favor, use apenas números e pontos (ex: 15.0).",
        "unset_min_os": "A modificação da versão mínima do SO foi redefinida.",
        "set_min_os": "A versão mínima do SO será definida como **{os_version}**.",
        "unset_profile_removal": "O perfil incorporado não será mais removido.",
        "set_profile_removal": "O perfil incorporado será removido.",
        "tweak_added_expecting_ipa": "Tweak adicionado: {file_name}. Agora envie o arquivo IPA para aplicá-lo.",
        "error_while_resetting": "Ocorreu um erro ao redefinir as opções: {error}."
    },
    "it": {
        "save_error": "Impossibile salvare {options}. Errore: {error}.",
        "update_error": "Impossibile aggiornare {options}. Errore: {error}.",
        "app_name_usage": "Uso: /name [nuovo nome app]",
        "unset_app_name": "La modifica del nome dell'app è stata reimpostata.",
        "set_app_name": "Il nome dell'app verrà cambiato in **{name}**.",
        "app_version_usage": "Uso: /version [nuova versione]",
        "invalid_app_version": "Formato versione non valido. Utilizzare solo numeri e punti (es. 1.2.3).",
        "unset_app_version": "La modifica della versione dell'app è stata reimpostata.",
        "set_app_version": "La versione dell'app verrà cambiata in **{version}**.",
        "app_id_usage": "Uso: /id [nuovo ID bundle]",
        "unset_app_id": "La modifica dell'ID bundle è stata reimpostata.",
        "set_app_id": "L'ID bundle verrà cambiato in **{id}**.",
        "min_os_usage": "Uso: /minos [versione]",
        "invalid_min_os": "Formato versione OS non valido. Utilizzare solo numeri e punti (es. 15.0).",
        "unset_min_os": "La modifica della versione minima del sistema operativo è stata reimpostata.",
        "set_min_os": "La versione minima del sistema operativo verrà impostata su **{os_version}**.",
        "unset_profile_removal": "Il profilo incorporato non verrà più rimosso.",
        "set_profile_removal": "Il profilo incorporato verrà rimosso.",
        "tweak_added_expecting_ipa": "Tweak aggiunto: {file_name}. Ora invia il file IPA per applicarlo.",
        "error_while_resetting": "Si è verificato un errore durante il ripristino delle opzioni: {error}."
    },
    "ja": {
        "save_error": "{options} を保存できませんでした。エラー: {error}。",
        "update_error": "{options} を更新できませんでした。エラー: {error}。",
        "app_name_usage": "使用法: /name [新しいアプリ名]",
        "unset_app_name": "アプリ名の変更がリセットされました。",
        "set_app_name": "アプリ名は **{name}** に変更されます。",
        "app_version_usage": "使用法: /version [新しいバージョン]",
        "invalid_app_version": "無効なバージョン形式です。数字とドットのみを使用してください (例: 1.2.3)。",
        "unset_app_version": "アプリのバージョン変更がリセットされました。",
        "set_app_version": "アプリのバージョンは **{version}** に変更されます。",
        "app_id_usage": "使用法: /id [新しいバンドルID]",
        "unset_app_id": "バンドルIDの変更がリセットされました。",
        "set_app_id": "バンドルIDは **{id}** に変更されます。",
        "min_os_usage": "使用法: /minos [バージョン]",
        "invalid_min_os": "無効なOSバージョン形式です。数字とドットのみを使用してください (例: 15.0)。",
        "unset_min_os": "最小OSバージョンの変更がリセットされました。",
        "set_min_os": "最小OSバージョンは **{os_version}** に設定されます。",
        "unset_profile_removal": "埋め込みプロファイルは削除されなくなります。",
        "set_profile_removal": "埋め込みプロファイルは削除されます。",
        "tweak_added_expecting_ipa": "Tweak が追加されました: {file_name}。IPA ファイルを送信して適用してください。",
        "error_while_resetting": "オプションのリセット中にエラーが発生しました: {error}。"
    },
    "ko": {
        "save_error": "{options}을(를) 저장할 수 없습니다. 오류: {error}.",
        "update_error": "{options}을(를) 업데이트할 수 없습니다. 오류: {error}.",
        "app_name_usage": "사용법: /name [새 앱 이름]",
        "unset_app_name": "앱 이름 수정이 초기화되었습니다.",
        "set_app_name": "앱 이름이 **{name}**(으)로 변경됩니다.",
        "app_version_usage": "사용법: /version [새 버전]",
        "invalid_app_version": "잘못된 버전 형식입니다. 숫자와 점만 사용하십시오 (예: 1.2.3).",
        "unset_app_version": "앱 버전 수정이 초기화되었습니다.",
        "set_app_version": "앱 버전이 **{version}**(으)로 변경됩니다.",
        "app_id_usage": "사용법: /id [새 번들 ID]",
        "unset_app_id": "번들 ID 수정이 초기화되었습니다.",
        "set_app_id": "번들 ID가 **{id}**(으)로 변경됩니다.",
        "min_os_usage": "사용법: /minos [버전]",
        "invalid_min_os": "잘못된 OS 버전 형식입니다. 숫자와 점만 사용하십시오 (예: 15.0).",
        "unset_min_os": "최소 OS 버전 수정이 초기화되었습니다.",
        "set_min_os": "최소 OS 버전이 **{os_version}**(으)로 설정됩니다.",
        "unset_profile_removal": "내장 프로필이 더 이상 제거되지 않습니다.",
        "set_profile_removal": "내장 프로필이 제거됩니다.",
        "tweak_added_expecting_ipa": "트윅 추가됨: {file_name}. 이제 IPA 파일을 보내 적용하십시오.",
        "error_while_resetting": "옵션 초기화 중 오류가 발생했습니다: {error}."
    },
    "hi": {
        "save_error": "{options} को सहेजा नहीं जा सका। त्रुटि: {error}.",
        "update_error": "{options} को अपडेट नहीं किया जा सका। त्रुटि: {error}.",
        "app_name_usage": "उपयोग: /name [नया ऐप नाम]",
        "unset_app_name": "ऐप नाम संशोधन रीसेट कर दिया गया है।",
        "set_app_name": "ऐप नाम **{name}** में बदल दिया जाएगा।",
        "app_version_usage": "उपयोग: /version [नया संस्करण]",
        "invalid_app_version": "अमान्य संस्करण प्रारूप। कृपया केवल संख्याएँ और बिंदु उपयोग करें (उदाहरण: 1.2.3)।",
        "unset_app_version": "ऐप संस्करण संशोधन रीसेट कर दिया गया है।",
        "set_app_version": "ऐप संस्करण **{version}** में बदल दिया जाएगा।",
        "app_id_usage": "उपयोग: /id [नया बंडल आईडी]",
        "unset_app_id": "बंडल आईडी संशोधन रीसेट कर दिया गया है।",
        "set_app_id": "बंडल आईडी **{id}** में बदल दिया जाएगा।",
        "min_os_usage": "उपयोग: /minos [संस्करण]",
        "invalid_min_os": "अमान्य OS संस्करण प्रारूप। कृपया केवल संख्याएँ और बिंदु उपयोग करें (उदाहरण: 15.0)।",
        "unset_min_os": "न्यूनतम OS संस्करण संशोधन रीसेट कर दिया गया है।",
        "set_min_os": "न्यूनतम OS संस्करण **{os_version}** पर सेट किया जाएगा।",
        "unset_profile_removal": "एम्बेडेड प्रोफ़ाइल अब नहीं हटाई जाएगी।",
        "set_profile_removal": "एम्बेडेड प्रोफ़ाइल हटा दी जाएगी।",
        "tweak_added_expecting_ipa": "ट्वीक जोड़ा गया: {file_name}. अब इसे लागू करने के लिए IPA फ़ाइल भेजें।",
        "error_while_resetting": "विकल्पों को रीसेट करते समय एक त्रुटि हुई: {error}."
    },
    "vi": {
        "save_error": "Không thể lưu {options}. Lỗi: {error}.",
        "update_error": "Không thể cập nhật {options}. Lỗi: {error}.",
        "app_name_usage": "Cách dùng: /name [tên ứng dụng mới]",
        "unset_app_name": "Việc sửa đổi tên ứng dụng đã được đặt lại.",
        "set_app_name": "Tên ứng dụng sẽ được thay đổi thành **{name}**.",
        "app_version_usage": "Cách dùng: /version [phiên bản mới]",
        "invalid_app_version": "Định dạng phiên bản không hợp lệ. Vui lòng chỉ sử dụng số và dấu chấm (ví dụ: 1.2.3).",
        "unset_app_version": "Việc sửa đổi phiên bản ứng dụng đã được đặt lại.",
        "set_app_version": "Phiên bản ứng dụng sẽ được thay đổi thành **{version}**.",
        "app_id_usage": "Cách dùng: /id [ID gói mới]",
        "unset_app_id": "Việc sửa đổi ID gói đã được đặt lại.",
        "set_app_id": "ID gói sẽ được thay đổi thành **{id}**.",
        "min_os_usage": "Cách dùng: /minos [phiên bản]",
        "invalid_min_os": "Định dạng phiên bản hệ điều hành không hợp lệ. Vui lòng chỉ sử dụng số và dấu chấm (ví dụ: 15.0).",
        "unset_min_os": "Việc sửa đổi phiên bản hệ điều hành tối thiểu đã được đặt lại.",
        "set_min_os": "Phiên bản hệ điều hành tối thiểu sẽ được đặt thành **{os_version}**.",
        "unset_profile_removal": "Hồ sơ nhúng sẽ không còn bị xóa.",
        "set_profile_removal": "Hồ sơ nhúng sẽ bị xóa.",
        "tweak_added_expecting_ipa": "Đã thêm Tweak: {file_name}. Bây giờ hãy gửi tệp IPA để áp dụng.",
        "error_while_resetting": "Đã xảy ra lỗi khi đặt lại các tùy chọn: {error}."
    },
    "id": {
        "save_error": "Tidak dapat menyimpan {options}. Kesalahan: {error}.",
        "update_error": "Tidak dapat memperbarui {options}. Kesalahan: {error}.",
        "app_name_usage": "Penggunaan: /name [nama aplikasi baru]",
        "unset_app_name": "Modifikasi nama aplikasi telah diatur ulang.",
        "set_app_name": "Nama aplikasi akan diubah menjadi **{name}**.",
        "app_version_usage": "Penggunaan: /version [versi baru]",
        "invalid_app_version": "Format versi tidak valid. Harap gunakan angka dan titik saja (misalnya, 1.2.3).",
        "unset_app_version": "Modifikasi versi aplikasi telah diatur ulang.",
        "set_app_version": "Versi aplikasi akan diubah menjadi **{version}**.",
        "app_id_usage": "Penggunaan: /id [ID bundel baru]",
        "unset_app_id": "Modifikasi ID bundel telah diatur ulang.",
        "set_app_id": "ID bundel akan diubah menjadi **{id}**.",
        "min_os_usage": "Penggunaan: /minos [versi]",
        "invalid_min_os": "Format versi OS tidak valid. Harap gunakan angka dan titik saja (misalnya, 15.0).",
        "unset_min_os": "Modifikasi versi OS minimum telah diatur ulang.",
        "set_min_os": "Versi OS minimum akan diatur ke **{os_version}**.",
        "unset_profile_removal": "Profil tertanam tidak akan lagi dihapus.",
        "set_profile_removal": "Profil tertanam akan dihapus.",
        "tweak_added_expecting_ipa": "Tweak ditambahkan: {file_name}. Sekarang kirim file IPA untuk menerapkannya.",
        "error_while_resetting": "Terjadi kesalahan saat mengatur ulang opsi: {error}."
    },
    "pl": {
        "save_error": "Nie można zapisać {options}. Błąd: {error}.",
        "update_error": "Nie można zaktualizować {options}. Błąd: {error}.",
        "app_name_usage": "Użycie: /name [nowa nazwa aplikacji]",
        "unset_app_name": "Modyfikacja nazwy aplikacji została zresetowana.",
        "set_app_name": "Nazwa aplikacji zostanie zmieniona na **{name}**.",
        "app_version_usage": "Użycie: /version [nowa wersja]",
        "invalid_app_version": "Nieprawidłowy format wersji. Proszę używać tylko cyfr i kropek (np. 1.2.3).",
        "unset_app_version": "Modyfikacja wersji aplikacji została zresetowana.",
        "set_app_version": "Wersja aplikacji zostanie zmieniona na **{version}**.",
        "app_id_usage": "Użycie: /id [nowy identyfikator pakietu]",
        "unset_app_id": "Modyfikacja identyfikatora pakietu została zresetowana.",
        "set_app_id": "Identyfikator pakietu zostanie zmieniony na **{id}**.",
        "min_os_usage": "Użycie: /minos [wersja]",
        "invalid_min_os": "Nieprawidłowy format wersji systemu operacyjnego. Proszę używać tylko cyfr i kropek (np. 15.0).",
        "unset_min_os": "Modyfikacja minimalnej wersji systemu operacyjnego została zresetowana.",
        "set_min_os": "Minimalna wersja systemu operacyjnego zostanie ustawiona na **{os_version}**.",
        "unset_profile_removal": "Osadzony profil nie będzie już usuwany.",
        "set_profile_removal": "Osadzony profil zostanie usunięty.",
        "tweak_added_expecting_ipa": "Dodano Tweak: {file_name}. Teraz wyślij plik IPA, aby go zastosować.",
        "error_while_resetting": "Wystąpił błąd podczas resetowania opcji: {error}."
    },
    "nl": {
        "save_error": "Kon {options} niet opslaan. Fout: {error}.",
        "update_error": "Kon {options} niet bijwerken. Fout: {error}.",
        "app_name_usage": "Gebruik: /name [nieuwe appnaam]",
        "unset_app_name": "Appnaamwijziging is gereset.",
        "set_app_name": "Appnaam wordt gewijzigd naar **{name}**.",
        "app_version_usage": "Gebruik: /version [nieuwe versie]",
        "invalid_app_version": "Ongeldig versieformaat. Gebruik alleen cijfers en punten (bijv. 1.2.3).",
        "unset_app_version": "Appversiewijziging is gereset.",
        "set_app_version": "Appversie wordt gewijzigd naar **{version}**.",
        "app_id_usage": "Gebruik: /id [nieuwe bundel-ID]",
        "unset_app_id": "Bundel-ID wijziging is gereset.",
        "set_app_id": "Bundel-ID wordt gewijzigd naar **{id}**.",
        "min_os_usage": "Gebruik: /minos [versie]",
        "invalid_min_os": "Ongeldig OS-versieformaat. Gebruik alleen cijfers en punten (bijv. 15.0).",
        "unset_min_os": "Minimale OS-versiewijziging is gereset.",
        "set_min_os": "Minimale OS-versie wordt ingesteld op **{os_version}**.",
        "unset_profile_removal": "Ingebed profiel wordt niet langer verwijderd.",
        "set_profile_removal": "Ingebed profiel wordt verwijderd.",
        "tweak_added_expecting_ipa": "Tweak toegevoegd: {file_name}. Stuur nu het IPA-bestand om het toe te passen.",
        "error_while_resetting": "Er is een fout opgetreden bij het resetten van opties: {error}."
    }
}
