# utils/power_manager.py
power_manager_strings = {
    "en": {
        "restart_requested": "🔄 **Restart Requested** by {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Restart has been canceled.",
        "restart_aborted": "❌ Restart aborted.",
        "restart_awaiting": "⏳ Waiting for active tasks to finish...\nElapsed: {time_elapsed}",
        "restart_in_progress": "♻️ Restarting now... ({time_elapsed})",
        "restart_declined": "⛔ You are not authorized to restart the bot.",
        "shutdown_requested": "🛑 **Shutdown Requested** by {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Shutdown aborted.",
        "shutdown_awaiting": "⏳ Shutdown can be canceled within the next 10 seconds...\nElapsed: {time_elapsed}",
        "shutdown_in_progress": "♻️ Shutting down now... ({time_elapsed})",
        "shutdown_declined": "⛔ You are not authorized to shut down the bot.",
        "permission_declined": "⛔ Permission denied."
    },
    "tr": {
        "restart_requested": "🔄 **Yeniden Başlatma İstendi** bởi {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Yeniden başlatma iptal edildi.",
        "restart_aborted": "❌ Yeniden başlatma iptal edildi.",
        "restart_awaiting": "⏳ Aktif görevlerin bitmesi bekleniyor...\nGeçen süre: {time_elapsed}",
        "restart_in_progress": "♻️ Şimdi yeniden başlatılıyor... ({time_elapsed})",
        "restart_declined": "⛔ Botu yeniden başlatma yetkiniz yok.",
        "shutdown_requested": "🛑 **Kapatma İstendi** bởi {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Kapatma iptal edildi.",
        "shutdown_awaiting": "⏳ Kapatma önümüzdeki 10 saniye içinde iptal edilebilir...\nGeçen süre: {time_elapsed}",
        "shutdown_in_progress": "♻️ Şimdi kapatılıyor... ({time_elapsed})",
        "shutdown_declined": "⛔ Botu kapatma yetkiniz yok.",
        "permission_declined": "⛔ İzin reddedildi."
    },
    "ru": {
        "restart_requested": "🔄 **Запрошен перезапуск** от {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Перезапуск отменен.",
        "restart_aborted": "❌ Перезапуск прерван.",
        "restart_awaiting": "⏳ Ожидание завершения активных задач...\nПрошло: {time_elapsed}",
        "restart_in_progress": "♻️ Перезапускаюсь... ({time_elapsed})",
        "restart_declined": "⛔ У вас нет прав на перезапуск бота.",
        "shutdown_requested": "🛑 **Запрошено выключение** от {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Выключение прервано.",
        "shutdown_awaiting": "⏳ Выключение можно отменить в течение следующих 10 секунд...\nПрошло: {time_elapsed}",
        "shutdown_in_progress": "♻️ Выключаюсь... ({time_elapsed})",
        "shutdown_declined": "⛔ У вас нет прав на выключение бота.",
        "permission_declined": "⛔ Доступ запрещен."
    },
    "de": {
        "restart_requested": "🔄 **Neustart angefordert** von {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Neustart wurde abgebrochen.",
        "restart_aborted": "❌ Neustart abgebrochen.",
        "restart_awaiting": "⏳ Warte auf den Abschluss aktiver Aufgaben...\nVerstrichen: {time_elapsed}",
        "restart_in_progress": "♻️ Starte jetzt neu... ({time_elapsed})",
        "restart_declined": "⛔ Du bist nicht berechtigt, den Bot neu zu starten.",
        "shutdown_requested": "🛑 **Herunterfahren angefordert** von {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Herunterfahren abgebrochen.",
        "shutdown_awaiting": "⏳ Das Herunterfahren kann innerhalb der nächsten 10 Sekunden abgebrochen werden...\nVerstrichen: {time_elapsed}",
        "shutdown_in_progress": "♻️ Fahre jetzt herunter... ({time_elapsed})",
        "shutdown_declined": "⛔ Du bist nicht berechtigt, den Bot herunterzufahren.",
        "permission_declined": "⛔ Zugriff verweigert."
    },
    "es": {
        "restart_requested": "🔄 **Reinicio solicitado** por {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 El reinicio ha sido cancelado.",
        "restart_aborted": "❌ Reinicio abortado.",
        "restart_awaiting": "⏳ Esperando que terminen las tareas activas...\nTiempo transcurrido: {time_elapsed}",
        "restart_in_progress": "♻️ Reiniciando ahora... ({time_elapsed})",
        "restart_declined": "⛔ No estás autorizado para reiniciar el bot.",
        "shutdown_requested": "🛑 **Apagado solicitado** por {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Apagado abortado.",
        "shutdown_awaiting": "⏳ El apagado se puede cancelar en los próximos 10 segundos...\nTiempo transcurrido: {time_elapsed}",
        "shutdown_in_progress": "♻️ Apagando ahora... ({time_elapsed})",
        "shutdown_declined": "⛔ No estás autorizado para apagar el bot.",
        "permission_declined": "⛔ Permiso denegado."
    },
    "fr": {
        "restart_requested": "🔄 **Redémarrage demandé** par {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Le redémarrage a été annulé.",
        "restart_aborted": "❌ Redémarrage annulé.",
        "restart_awaiting": "⏳ En attente de la fin des tâches activas...\nTemps écoulé: {time_elapsed}",
        "restart_in_progress": "♻️ Redémarrage en cours... ({time_elapsed})",
        "restart_declined": "⛔ Vous n'êtes pas autorisé à redémarrer le bot.",
        "shutdown_requested": "🛑 **Arrêt demandé** par {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Arrêt annulé.",
        "shutdown_awaiting": "⏳ L'arrêt peut être annulé dans les 10 prochaines secondes...\nTemps écoulé: {time_elapsed}",
        "shutdown_in_progress": "♻️ Arrêt en cours... ({time_elapsed})",
        "shutdown_declined": "⛔ Vous n'êtes pas autorisé à arrêter le bot.",
        "permission_declined": "⛔ Permission refusée."
    },
    "zh-cn": {
        "restart_requested": "🔄 **重启请求** 由 {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 重启已取消。",
        "restart_aborted": "❌ 重启中止。",
        "restart_awaiting": "⏳ 正在等待活动任务完成...\n已用时间: {time_elapsed}",
        "restart_in_progress": "♻️ 正在重启... ({time_elapsed})",
        "restart_declined": "⛔ 您无权重启机器人。",
        "shutdown_requested": "🛑 **关机请求** 由 {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 关机中止。",
        "shutdown_awaiting": "⏳ 关机可在接下来的 10 秒内取消...\n已用时间: {time_elapsed}",
        "shutdown_in_progress": "♻️ 正在关机... ({time_elapsed})",
        "shutdown_declined": "⛔ 您无权关闭机器人。",
        "permission_declined": "⛔ 权限被拒绝。"
    },
    "ar": {
        "restart_requested": "🔄 **طلب إعادة تشغيل** بواسطة {user_first_name} (@{username})\nمعرف العملية: `{process_id}`",
        "restart_canceled": "🔄 تم إلغاء إعادة التشغيل.",
        "restart_aborted": "❌ تم إجهاض إعادة التشغيل.",
        "restart_awaiting": "⏳ في انتظار انتهاء المهام النشطة...\nالوقت المنقضي: {time_elapsed}",
        "restart_in_progress": "♻️ جاري إعادة التشغيل الآن... ({time_elapsed})",
        "restart_declined": "⛔ غير مصرح لك بإعادة تشغيل البوت.",
        "shutdown_requested": "🛑 **طلب إيقاف تشغيل** بواسطة {user_first_name} (@{username})\nمعرف العملية: `{process_id}`",
        "shutdown_aborted": "🛑 تم إجهاض إيقاف التشغيل.",
        "shutdown_awaiting": "⏳ يمكن إلغاء إيقاف التشغيل خلال الـ 10 ثواني القادمة...\nالوقت المنقضي: {time_elapsed}",
        "shutdown_in_progress": "♻️ جاري إيقاف التشغيل الآن... ({time_elapsed})",
        "shutdown_declined": "⛔ غير مصرح لك بإيقاف تشغيل البوت.",
        "permission_declined": "⛔ تم رفض الإذن."
    },
    "pt": {
        "restart_requested": "🔄 **Reinicialização Solicitada** por {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Reinicialização foi cancelada.",
        "restart_aborted": "❌ Reinicialização abortada.",
        "restart_awaiting": "⏳ Aguardando a conclusão das tarefas ativas...\nTempo decorrido: {time_elapsed}",
        "restart_in_progress": "♻️ Reiniciando agora... ({time_elapsed})",
        "restart_declined": "⛔ Você não está autorizado a reiniciar o bot.",
        "shutdown_requested": "🛑 **Desligamento Solicitado** por {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Desligamento abortado.",
        "shutdown_awaiting": "⏳ O desligamento pode ser cancelado nos próximos 10 segundos...\nTempo decorrido: {time_elapsed}",
        "shutdown_in_progress": "♻️ Desligando agora... ({time_elapsed})",
        "shutdown_declined": "⛔ Você não está autorizado a desligar o bot.",
        "permission_declined": "⛔ Permissão negada."
    },
    "it": {
        "restart_requested": "🔄 **Riavvio richiesto** da {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Riavvio annullato.",
        "restart_aborted": "❌ Riavvio interrotto.",
        "restart_awaiting": "⏳ In attesa del completamento delle attività attive...\nTempo trascorso: {time_elapsed}",
        "restart_in_progress": "♻️ Riavvio in corso... ({time_elapsed})",
        "restart_declined": "⛔ Non sei autorizzato a riavviare il bot.",
        "shutdown_requested": "🛑 **Spegnimento richiesto** da {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Spegnimento interrotto.",
        "shutdown_awaiting": "⏳ Lo spegnimento può essere annullato entro i prossimi 10 secondi...\nTempo trascorso: {time_elapsed}",
        "shutdown_in_progress": "♻️ Spegnimento in corso... ({time_elapsed})",
        "shutdown_declined": "⛔ Non sei autorizzato a spegnere il bot.",
        "permission_declined": "⛔ Permesso negato."
    },
    "ja": {
        "restart_requested": "🔄 **再起動要求** {user_first_name} (@{username})より\nPID: `{process_id}`",
        "restart_canceled": "🔄 再起動はキャンセルされました。",
        "restart_aborted": "❌ 再起動は中止されました。",
        "restart_awaiting": "⏳ アクティブなタスクの終了を待機中...\n経過時間: {time_elapsed}",
        "restart_in_progress": "♻️ 今すぐ再起動中... ({time_elapsed})",
        "restart_declined": "⛔ ボットを再起動する権限がありません。",
        "shutdown_requested": "🛑 **シャットダウン要求** {user_first_name} (@{username})より\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 シャットダウンは中止されました。",
        "shutdown_awaiting": "⏳ シャットダウンは次の10秒以内にキャンセルできます...\n経過時間: {time_elapsed}",
        "shutdown_in_progress": "♻️ 今すぐシャットダウン中... ({time_elapsed})",
        "shutdown_declined": "⛔ ボットをシャットダウンする権限がありません。",
        "permission_declined": "⛔ 権限が拒否されました。"
    },
    "ko": {
        "restart_requested": "🔄 **재시작 요청** {user_first_name} (@{username})님으로부터\nPID: `{process_id}`",
        "restart_canceled": "🔄 재시작이 취소되었습니다.",
        "restart_aborted": "❌ 재시작이 중단되었습니다.",
        "restart_awaiting": "⏳ 활성 작업 완료 대기 중...\n경과 시간: {time_elapsed}",
        "restart_in_progress": "♻️ 지금 재시작 중... ({time_elapsed})",
        "restart_declined": "⛔ 봇을 재시작할 권한이 없습니다.",
        "shutdown_requested": "🛑 **종료 요청** {user_first_name} (@{username})님으로부터\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 종료가 중단되었습니다.",
        "shutdown_awaiting": "⏳ 종료는 다음 10초 이내에 취소할 수 있습니다...\n경과 시간: {time_elapsed}",
        "shutdown_in_progress": "♻️ 지금 종료 중... ({time_elapsed})",
        "shutdown_declined": "⛔ 봇을 종료할 권한이 없습니다.",
        "permission_declined": "⛔ 권한이 거부되었습니다."
    },
    "hi": {
        "restart_requested": "🔄 **पुनरारंभ का अनुरोध** {user_first_name} (@{username}) द्वारा\nPID: `{process_id}`",
        "restart_canceled": "🔄 पुनरारंभ रद्द कर दिया गया है।",
        "restart_aborted": "❌ पुनरारंभ रद्द कर दिया गया।",
        "restart_awaiting": "⏳ सक्रिय कार्यों के समाप्त होने की प्रतीक्षा कर रहा है...\nबीता हुआ समय: {time_elapsed}",
        "restart_in_progress": "♻️ अब पुनरारंभ हो रहा है... ({time_elapsed})",
        "restart_declined": "⛔ आपको बॉट को पुनरारंभ करने की अनुमति नहीं है।",
        "shutdown_requested": "🛑 **शटडाउन का अनुरोध** {user_first_name} (@{username}) द्वारा\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 शटडाउन रद्द कर दिया गया।",
        "shutdown_awaiting": "⏳ शटडाउन अगले 10 सेकंड के भीतर रद्द किया जा सकता है...\nबीता हुआ समय: {time_elapsed}",
        "shutdown_in_progress": "♻️ अब शटडाउन हो रहा है... ({time_elapsed})",
        "shutdown_declined": "⛔ आपको बॉट को बंद करने की अनुमति नहीं है।",
        "permission_declined": "⛔ अनुमति अस्वीकृत।"
    },
    "vi": {
        "restart_requested": "🔄 **Yêu cầu khởi động lại** bởi {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Khởi động lại đã bị hủy.",
        "restart_aborted": "❌ Khởi động lại bị hủy bỏ.",
        "restart_awaiting": "⏳ Đang chờ các tác vụ hoạt động hoàn tất...\nThời gian đã trôi qua: {time_elapsed}",
        "restart_in_progress": "♻️ Đang khởi động lại... ({time_elapsed})",
        "restart_declined": "⛔ Bạn không được phép khởi động lại bot.",
        "shutdown_requested": "🛑 **Yêu cầu tắt máy** bởi {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Tắt máy bị hủy bỏ.",
        "shutdown_awaiting": "⏳ Tắt máy có thể bị hủy trong vòng 10 giây tới...\nThời gian đã trôi qua: {time_elapsed}",
        "shutdown_in_progress": "♻️ Đang tắt máy... ({time_elapsed})",
        "shutdown_declined": "⛔ Bạn không được phép tắt bot.",
        "permission_declined": "⛔ Quyền bị từ chối."
    },
    "id": {
        "restart_requested": "🔄 **Permintaan Mulai Ulang** oleh {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Mulai ulang telah dibatalkan.",
        "restart_aborted": "❌ Mulai ulang dibatalkan.",
        "restart_awaiting": "⏳ Menunggu tugas aktif selesai...\nWaktu berlalu: {time_elapsed}",
        "restart_in_progress": "♻️ Memulai ulang sekarang... ({time_elapsed})",
        "restart_declined": "⛔ Anda tidak diizinkan untuk memulai ulang bot.",
        "shutdown_requested": "🛑 **Permintaan Mati** oleh {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Mati dibatalkan.",
        "shutdown_awaiting": "⏳ Mati dapat dibatalkan dalam 10 detik berikutnya...\nWaktu berlalu: {time_elapsed}",
        "shutdown_in_progress": "♻️ Mematikan sekarang... ({time_elapsed})",
        "shutdown_declined": "⛔ Anda tidak diizinkan untuk mematikan bot.",
        "permission_declined": "⛔ Izin ditolak."
    },
    "pl": {
        "restart_requested": "🔄 **Żądanie ponownego uruchomienia** przez {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Ponowne uruchomienie zostało anulowane.",
        "restart_aborted": "❌ Ponowne uruchomienie przerwane.",
        "restart_awaiting": "⏳ Oczekiwanie na zakończenie aktywnych zadań...\nUpłynęło: {time_elapsed}",
        "restart_in_progress": "♻️ Ponowne uruchamianie... ({time_elapsed})",
        "restart_declined": "⛔ Nie masz uprawnień do ponownego uruchomienia bota.",
        "shutdown_requested": "🛑 **Żądanie wyłączenia** przez {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Wyłączenie przerwane.",
        "shutdown_awaiting": "⏳ Wyłączenie można anulować w ciągu następnych 10 sekund...\nUpłynęło: {time_elapsed}",
        "shutdown_in_progress": "♻️ Wyłączanie... ({time_elapsed})",
        "shutdown_declined": "⛔ Nie masz uprawnień do wyłączenia bota.",
        "permission_declined": "⛔ Odmowa dostępu."
    },
    "nl": {
        "restart_requested": "🔄 **Herstart aangevraagd** door {user_first_name} (@{username})\nPID: `{process_id}`",
        "restart_canceled": "🔄 Herstart is geannuleerd.",
        "restart_aborted": "❌ Herstart afgebroken.",
        "restart_awaiting": "⏳ Wachten op actieve taken om te voltooien...\nVerstreken: {time_elapsed}",
        "restart_in_progress": "♻️ Nu opnieuw opstarten... ({time_elapsed})",
        "restart_declined": "⛔ U bent niet gemachtigd om de bot opnieuw te starten.",
        "shutdown_requested": "🛑 **Afsluiten aangevraagd** door {user_first_name} (@{username})\nPID: `{process_id}`",
        "shutdown_aborted": "🛑 Afsluiten afgebroken.",
        "shutdown_awaiting": "⏳ Afsluiten kan binnen de volgende 10 seconden worden geannuleerd...\nVerstreken: {time_elapsed}",
        "shutdown_in_progress": "♻️ Nu afsluiten... ({time_elapsed})",
        "shutdown_declined": "⛔ U bent niet gemachtigd om de bot af te sluiten.",
        "permission_declined": "⛔ Toegang geweigerd."
    }
}
