# Plugins/sign.py
sign_strings = {
    "en": {
        "no_cert_selected": "Hello, {user_first_name}! Please select a certificate from the /start menu and try again. 🚀",
        "sign_error_retry": "An error occurred during signing, retrying... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Signing failed for {file_name}.",
        "unexpected_error": "An unexpected error occurred. If this issue persists, please contact support.",
        "ipa_ready": "✅ Your IPA has been signed and is ready.",
        "forgot_choice": "It seems you forgot to select a certificate. Please go to the /start menu to choose one.",
        "file_lost": "The file was lost during the signing process.",
        "value_error": "A value error occurred during the signing process.",
        "permission_error": "A permission error occurred during the signing process.",
        "signing_error": "The signing operation failed.",
        "unknown_error": "An unexpected error occurred during the signing process.",
        "select_certificate_button": "📝️ Select Certificate",
        "signing_in_progress": "📝 Signing...",
        "modifying_in_progress": "🔧 Modifying...",
        "executing_command": "Executing: {command}",
        "modify_retry_error": "An error occurred while modifying, retrying... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "The file could not be found during the signing process.",
        "ve_err": "A value error occurred during the signing process.",
        "pe_err": "A permission error occurred during the signing process.",
        "unknown_sign_err": "An unknown error occurred during the signing process."
    },
    "tr": {
        "no_cert_selected": "Merhaba, {user_first_name}! Lütfen /start menüsünden bir sertifika seçin ve tekrar deneyin. 🚀",
        "sign_error_retry": "İmzalama sırasında bir hata oluştu, yeniden deneniyor... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ {file_name} için imzalama başarısız oldu.",
        "unexpected_error": "Beklenmedik bir hata oluştu. Bu sorun devam ederse, lütfen destek ile iletişime geçin.",
        "ipa_ready": "✅ IPA'nız imzalandı ve hazır.",
        "forgot_choice": "Görünüşe göre bir sertifika seçmeyi unuttunuz. Lütfen bir tane seçmek için /start menüsüne gidin.",
        "file_lost": "Dosya imzalama işlemi sırasında kayboldu.",
        "value_error": "İmzalama işlemi sırasında bir değer hatası oluştu.",
        "permission_error": "İmzalama işlemi sırasında bir izin hatası oluştu.",
        "signing_error": "İmzalama işlemi başarısız oldu.",
        "unknown_error": "İmzalama işlemi sırasında beklenmedik bir hata oluştu.",
        "select_certificate_button": "📝️ Sertifika Seç",
        "signing_in_progress": "📝 İmzalanıyor...",
        "modifying_in_progress": "🔧 Düzenleniyor...",
        "executing_command": "Çalıştırılıyor: {command}",
        "modify_retry_error": "Düzenleme sırasında bir hata oluştu, yeniden deneniyor... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "İmzalama işlemi sırasında dosya bulunamadı.",
        "ve_err": "İmzalama işlemi sırasında bir değer hatası oluştu.",
        "pe_err": "İmzalama işlemi sırasında bir izin hatası oluştu.",
        "unknown_sign_err": "İmzalama işlemi sırasında bilinmeyen bir hata oluştu."
    },
    "ru": {
        "no_cert_selected": "Здравствуйте, {user_first_name}! Пожалуйста, выберите сертификат в меню /start и попробуйте снова. 🚀",
        "sign_error_retry": "Произошла ошибка при подписании, повторная попытка... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Не удалось подписать {file_name}.",
        "unexpected_error": "Произошла непредвиденная ошибка. Если проблема не исчезнет, обратитесь в службу поддержки.",
        "ipa_ready": "✅ Ваш IPA подписан и готов.",
        "forgot_choice": "Кажется, вы забыли выбрать сертификат. Пожалуйста, перейдите в меню /start, чтобы выбрать его.",
        "file_lost": "Файл был утерян в процессе подписания.",
        "value_error": "В процессе подписания произошла ошибка значения.",
        "permission_error": "В процессе подписания произошла ошибка разрешений.",
        "signing_error": "Операция подписания не удалась.",
        "unknown_error": "В процессе подписания произошла непредвиденная ошибка.",
        "select_certificate_button": "📝️ Выбрать сертификат",
        "signing_in_progress": "📝 Подписание...",
        "modifying_in_progress": "🔧 Изменение...",
        "executing_command": "Выполнение: {command}",
        "modify_retry_error": "Произошла ошибка при изменении, повторная попытка... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Файл не найден в процессе подписания.",
        "ve_err": "В процессе подписания произошла ошибка значения.",
        "pe_err": "В процессе подписания произошла ошибка разрешений.",
        "unknown_sign_err": "В процессе подписания произошла неизвестная ошибка."
    },
    "de": {
        "no_cert_selected": "Hallo, {user_first_name}! Bitte wähle ein Zertifikat aus dem /start-Menü und versuche es erneut. 🚀",
        "sign_error_retry": "Beim Signieren ist ein Fehler aufgetreten, versuche erneut... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Signieren für {file_name} fehlgeschlagen.",
        "unexpected_error": "Ein unerwarteter Fehler ist aufgetreten. Wenn dieses Problem weiterhin besteht, wende dich bitte an den Support.",
        "ipa_ready": "✅ Deine IPA wurde signiert und ist fertig.",
        "forgot_choice": "Es scheint, du hast vergessen, ein Zertifikat auszuwählen. Bitte gehe zum /start-Menü, um eines auszuwählen.",
        "file_lost": "Die Datei ging während des Signiervorgangs verloren.",
        "value_error": "Während des Signiervorgangs ist ein Wertfehler aufgetreten.",
        "permission_error": "Während des Signiervorgangs ist ein Berechtigungsfehler aufgetreten.",
        "signing_error": "Der Signiervorgang ist fehlgeschlagen.",
        "unknown_error": "Während des Signiervorgangs ist ein unerwarteter Fehler aufgetreten.",
        "select_certificate_button": "📝️ Zertifikat auswählen",
        "signing_in_progress": "📝 Signiere...",
        "modifying_in_progress": "🔧 Ändere...",
        "executing_command": "Führe aus: {command}",
        "modify_retry_error": "Beim Ändern ist ein Fehler aufgetreten, versuche erneut... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Die Datei konnte während des Signiervorgangs nicht gefunden werden.",
        "ve_err": "Während des Signiervorgangs ist ein Wertfehler aufgetreten.",
        "pe_err": "Während des Signiervorgangs ist ein Berechtigungsfehler aufgetreten.",
        "unknown_sign_err": "Während des Signiervorgangs ist ein unbekannter Fehler aufgetreten."
    },
    "es": {
        "no_cert_selected": "¡Hola, {user_first_name}! Por favor, selecciona un certificado del menú /start e inténtalo de nuevo. 🚀",
        "sign_error_retry": "Ocurrió un error durante la firma, reintentando... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Falló la firma para {file_name}.",
        "unexpected_error": "Ocurrió un error inesperado. Si este problema persiste, por favor contacta a soporte.",
        "ipa_ready": "✅ Tu IPA ha sido firmada y está lista.",
        "forgot_choice": "Parece que olvidaste seleccionar un certificado. Por favor, ve al menú /start para elegir uno.",
        "file_lost": "El archivo se perdió durante el proceso de firma.",
        "value_error": "Ocurrió un error de valor durante el proceso de firma.",
        "permission_error": "Ocurrió un error de permiso durante el proceso de firma.",
        "signing_error": "La operación de firma falló.",
        "unknown_error": "Ocurrió un error inesperado durante el proceso de firma.",
        "select_certificate_button": "📝️ Seleccionar certificado",
        "signing_in_progress": "📝 Firmando...",
        "modifying_in_progress": "🔧 Modificando...",
        "executing_command": "Ejecutando: {command}",
        "modify_retry_error": "Ocurrió un error al modificar, reintentando... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "No se pudo encontrar el archivo durante el proceso de firma.",
        "ve_err": "Ocurrió un error de valor durante el proceso de firma.",
        "pe_err": "Ocurrió un error de permiso durante el proceso de firma.",
        "unknown_sign_err": "Ocurrió un error desconocido durante el proceso de firma."
    },
    "fr": {
        "no_cert_selected": "Bonjour, {user_first_name}! Veuillez sélectionner un certificat dans le menu /start et réessayer. 🚀",
        "sign_error_retry": "Une erreur est survenue lors de la signature, nouvelle tentative... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Échec de la signature pour {file_name}.",
        "unexpected_error": "Une erreur inattendue est survenue. Si ce problème persiste, veuillez contacter le support.",
        "ipa_ready": "✅ Votre IPA a été signé et est prêt.",
        "forgot_choice": "Il semble que vous ayez oublié de sélectionner un certificat. Veuillez aller dans le menu /start pour en choisir un.",
        "file_lost": "Le fichier a été perdu pendant le processus de signature.",
        "value_error": "Une erreur de valeur est survenue pendant le processus de signature.",
        "permission_error": "Une erreur d'autorisation est survenue pendant le processus de signature.",
        "signing_error": "L'opération de signature a échoué.",
        "unknown_error": "Une erreur inattendue est survenue pendant le processus de signature.",
        "select_certificate_button": "📝️ Sélectionner un certificat",
        "signing_in_progress": "📝 Signature...",
        "modifying_in_progress": "🔧 Modification...",
        "executing_command": "Exécution: {command}",
        "modify_retry_error": "Une erreur est survenue lors de la modification, nouvelle tentative... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Le fichier n'a pas pu être trouvé pendant le processus de signature.",
        "ve_err": "Une erreur de valeur est survenue pendant le processus de signature.",
        "pe_err": "Une erreur d'autorisation est survenue pendant le processus de signature.",
        "unknown_sign_err": "Une erreur inconnue est survenue pendant le processus de signature."
    },
    "zh-cn": {
        "no_cert_selected": "您好, {user_first_name}! 请从 /start 菜单选择一个证书，然后重试。🚀",
        "sign_error_retry": "签名过程中发生错误，正在重试... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ {file_name} 签名失败。",
        "unexpected_error": "发生未知错误。如果此问题仍然存在，请联系支持。",
        "ipa_ready": "✅ 您的 IPA 已签名并准备就绪。",
        "forgot_choice": "您似乎忘记选择证书了。请前往 /start 菜单选择一个。",
        "file_lost": "文件在签名过程中丢失。",
        "value_error": "签名过程中发生值错误。",
        "permission_error": "签名过程中发生权限错误。",
        "signing_error": "签名操作失败。",
        "unknown_error": "签名过程中发生未知错误。",
        "select_certificate_button": "📝️ 选择证书",
        "signing_in_progress": "📝 正在签名...",
        "modifying_in_progress": "🔧 正在修改...",
        "executing_command": "正在执行: {command}",
        "modify_retry_error": "修改过程中发生错误，正在重试... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "签名过程中找不到文件。",
        "ve_err": "签名过程中发生值错误。",
        "pe_err": "签名过程中发生权限错误。",
        "unknown_sign_err": "签名过程中发生未知错误。"
    },
    "ar": {
        "no_cert_selected": "مرحباً، {user_first_name}! الرجاء تحديد شهادة من قائمة /start والمحاولة مرة أخرى. 🚀",
        "sign_error_retry": "حدث خطأ أثناء التوقيع، إعادة المحاولة... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ فشل التوقيع لـ {file_name}.",
        "unexpected_error": "حدث خطأ غير متوقع. إذا استمرت هذه المشكلة، يرجى الاتصال بالدعم.",
        "ipa_ready": "✅ تم توقيع ملف IPA الخاص بك وهو جاهز.",
        "forgot_choice": "يبدو أنك نسيت تحديد شهادة. الرجاء الانتقال إلى قائمة /start لاختيار واحدة.",
        "file_lost": "فقد الملف أثناء عملية التوقيع.",
        "value_error": "حدث خطأ في القيمة أثناء عملية التوقيع.",
        "permission_error": "حدث خطأ في الإذن أثناء عملية التوقيع.",
        "signing_error": "فشلت عملية التوقيع.",
        "unknown_error": "حدث خطأ غير متوقع أثناء عملية التوقيع.",
        "select_certificate_button": "📝️ تحديد الشهادة",
        "signing_in_progress": "📝 جاري التوقيع...",
        "modifying_in_progress": "🔧 جاري التعديل...",
        "executing_command": "تنفيذ: {command}",
        "modify_retry_error": "حدث خطأ أثناء التعديل، إعادة المحاولة... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "تعذر العثور على الملف أثناء عملية التوقيع.",
        "ve_err": "حدث خطأ في القيمة أثناء عملية التوقيع.",
        "pe_err": "حدث خطأ في الإذن أثناء عملية التوقيع.",
        "unknown_sign_err": "حدث خطأ غير معروف أثناء عملية التوقيع."
    },
    "pt": {
        "no_cert_selected": "Olá, {user_first_name}! Por favor, selecione um certificado no menu /start e tente novamente. 🚀",
        "sign_error_retry": "Ocorreu um erro durante a assinatura, tentando novamente... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Falha na assinatura para {file_name}.",
        "unexpected_error": "Ocorreu um erro inesperado. Se o problema persistir, entre em contato com o suporte.",
        "ipa_ready": "✅ Seu IPA foi assinado e está pronto.",
        "forgot_choice": "Parece que você esqueceu de selecionar um certificado. Por favor, vá para o menu /start para escolher um.",
        "file_lost": "O arquivo foi perdido durante o processo de assinatura.",
        "value_error": "Ocorreu um erro de valor durante o processo de assinatura.",
        "permission_error": "Ocorreu um erro de permissão durante o processo de assinatura.",
        "signing_error": "A operação de assinatura falhou.",
        "unknown_error": "Ocorreu um erro inesperado durante o processo de assinatura.",
        "select_certificate_button": "📝️ Selecionar Certificado",
        "signing_in_progress": "📝 Assinando...",
        "modifying_in_progress": "🔧 Modificando...",
        "executing_command": "Executando: {command}",
        "modify_retry_error": "Ocorreu um erro ao modificar, tentando novamente... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "O arquivo não pôde ser encontrado durante o processo de assinatura.",
        "ve_err": "Ocorreu um erro de valor durante o processo de assinatura.",
        "pe_err": "Ocorreu um erro de permissão durante o processo de assinatura.",
        "unknown_sign_err": "Ocorreu um erro desconhecido durante o processo de assinatura."
    },
    "it": {
        "no_cert_selected": "Ciao, {user_first_name}! Seleziona un certificato dal menu /start e riprova. 🚀",
        "sign_error_retry": "Si è verificato un errore durante la firma, riprovo... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Firma fallita per {file_name}.",
        "unexpected_error": "Si è verificato un errore imprevisto. Se il problema persiste, contatta il supporto.",
        "ipa_ready": "✅ Il tuo IPA è stato firmato ed è pronto.",
        "forgot_choice": "Sembra che tu abbia dimenticato di selezionare un certificato. Vai al menu /start per sceglierne uno.",
        "file_lost": "Il file è andato perso durante il processo di firma.",
        "value_error": "Si è verificato un errore di valore durante il processo di firma.",
        "permission_error": "Si è verificato un errore di autorizzazione durante il processo di firma.",
        "signing_error": "L'operazione di firma è fallita.",
        "unknown_error": "Si è verificato un errore imprevisto durante il processo di firma.",
        "select_certificate_button": "📝️ Seleziona Certificato",
        "signing_in_progress": "📝 Firma in corso...",
        "modifying_in_progress": "🔧 Modifica in corso...",
        "executing_command": "Esecuzione: {command}",
        "modify_retry_error": "Si è verificato un errore durante la modifica, riprovo... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Il file non è stato trovato durante il processo di firma.",
        "ve_err": "Si è verificato un errore di valore durante il processo di firma.",
        "pe_err": "Si è verificato un errore di autorizzazione durante il processo di firma.",
        "unknown_sign_err": "Si è verificato un errore sconosciuto durante il processo di firma."
    },
    "ja": {
        "no_cert_selected": "こんにちは、{user_first_name}さん！ /startメニューから証明書を選択して、もう一度お試しください。🚀",
        "sign_error_retry": "署名中にエラーが発生しました。再試行中... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ {file_name} の署名に失敗しました。",
        "unexpected_error": "予期しないエラーが発生しました。この問題が解決しない場合は、サポートにお問い合わせください。",
        "ipa_ready": "✅ IPAが署名され、準備ができました。",
        "forgot_choice": "証明書を選択し忘れたようです。/startメニューから選択してください。",
        "file_lost": "署名プロセス中にファイルが失われました。",
        "value_error": "署名プロセス中に値エラーが発生しました。",
        "permission_error": "署名プロセス中に権限エラーが発生しました。",
        "signing_error": "署名操作が失敗しました。",
        "unknown_error": "署名プロセス中に予期しないエラーが発生しました。",
        "select_certificate_button": "📝️ 証明書を選択",
        "signing_in_progress": "📝 署名中...",
        "modifying_in_progress": "🔧 変更中...",
        "executing_command": "実行中: {command}",
        "modify_retry_error": "変更中にエラーが発生しました。再試行中... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "署名プロセス中にファイルが見つかりませんでした。",
        "ve_err": "署名プロセス中に値エラーが発生しました。",
        "pe_err": "署名プロセス中に権限エラーが発生しました。",
        "unknown_sign_err": "署名プロセス中に不明なエラーが発生しました。"
    },
    "ko": {
        "no_cert_selected": "안녕하세요, {user_first_name}님! /start 메뉴에서 인증서를 선택하고 다시 시도하십시오. 🚀",
        "sign_error_retry": "서명 중 오류가 발생하여 다시 시도 중입니다... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ {file_name} 서명 실패.",
        "unexpected_error": "예기치 않은 오류가 발생했습니다. 이 문제가 지속되면 지원팀에 문의하십시오.",
        "ipa_ready": "✅ IPA가 서명되어 준비되었습니다.",
        "forgot_choice": "인증서를 선택하는 것을 잊은 것 같습니다. /start 메뉴로 이동하여 선택하십시오.",
        "file_lost": "서명 과정에서 파일이 손실되었습니다.",
        "value_error": "서명 과정에서 값 오류가 발생했습니다.",
        "permission_error": "서명 과정에서 권한 오류가 발생했습니다.",
        "signing_error": "서명 작업이 실패했습니다.",
        "unknown_error": "서명 과정에서 예기치 않은 오류가 발생했습니다.",
        "select_certificate_button": "📝️ 인증서 선택",
        "signing_in_progress": "📝 서명 중...",
        "modifying_in_progress": "🔧 수정 중...",
        "executing_command": "실행 중: {command}",
        "modify_retry_error": "수정 중 오류가 발생하여 다시 시도 중입니다... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "서명 과정에서 파일을 찾을 수 없습니다.",
        "ve_err": "서명 과정에서 값 오류가 발생했습니다.",
        "pe_err": "서명 과정에서 권한 오류가 발생했습니다.",
        "unknown_sign_err": "서명 과정에서 알 수 없는 오류가 발생했습니다."
    },
    "hi": {
        "no_cert_selected": "नमस्ते, {user_first_name}! कृपया /start मेनू से एक प्रमाणपत्र चुनें और पुनः प्रयास करें। 🚀",
        "sign_error_retry": "हस्ताक्षर के दौरान एक त्रुटि हुई, पुनः प्रयास कर रहा है... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ {file_name} के लिए हस्ताक्षर विफल।",
        "unexpected_error": "एक अप्रत्याशित त्रुटि हुई। यदि यह समस्या बनी रहती है, तो कृपया सहायता से संपर्क करें।",
        "ipa_ready": "✅ आपका IPA हस्ताक्षरित और तैयार है।",
        "forgot_choice": "ऐसा लगता है कि आप एक प्रमाणपत्र चुनना भूल गए हैं। कृपया एक चुनने के लिए /start मेनू पर जाएं।",
        "file_lost": "हस्ताक्षर प्रक्रिया के दौरान फ़ाइल खो गई थी।",
        "value_error": "हस्ताक्षर प्रक्रिया के दौरान एक मान त्रुटि हुई।",
        "permission_error": "हस्ताक्षर प्रक्रिया के दौरान एक अनुमति त्रुटि हुई।",
        "signing_error": "हस्ताक्षर ऑपरेशन विफल रहा।",
        "unknown_error": "हस्ताक्षर प्रक्रिया के दौरान एक अप्रत्याशित त्रुटि हुई।",
        "select_certificate_button": "📝️ प्रमाणपत्र चुनें",
        "signing_in_progress": "📝 हस्ताक्षर कर रहा है...",
        "modifying_in_progress": "🔧 संशोधित कर रहा है...",
        "executing_command": "निष्पादित कर रहा है: {command}",
        "modify_retry_error": "संशोधित करते समय एक त्रुटि हुई, पुनः प्रयास कर रहा है... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "हस्ताक्षर प्रक्रिया के दौरान फ़ाइल नहीं मिल सकी।",
        "ve_err": "हस्ताक्षर प्रक्रिया के दौरान एक मान त्रुटि हुई।",
        "pe_err": "हस्ताक्षर प्रक्रिया के दौरान एक अनुमति त्रुटि हुई।",
        "unknown_sign_err": "हस्ताक्षर प्रक्रिया के दौरान एक अज्ञात त्रुटि हुई।"
    },
    "vi": {
        "no_cert_selected": "Xin chào, {user_first_name}! Vui lòng chọn chứng chỉ từ menu /start và thử lại. 🚀",
        "sign_error_retry": "Đã xảy ra lỗi trong quá trình ký, đang thử lại... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Ký {file_name} thất bại.",
        "unexpected_error": "Đã xảy ra lỗi không mong muốn. Nếu vấn đề này vẫn tiếp diễn, vui lòng liên hệ hỗ trợ.",
        "ipa_ready": "✅ IPA của bạn đã được ký và sẵn sàng.",
        "forgot_choice": "Có vẻ như bạn đã quên chọn chứng chỉ. Vui lòng vào menu /start để chọn một.",
        "file_lost": "Tệp đã bị mất trong quá trình ký.",
        "value_error": "Đã xảy ra lỗi giá trị trong quá trình ký.",
        "permission_error": "Đã xảy ra lỗi quyền trong quá trình ký.",
        "signing_error": "Thao tác ký thất bại.",
        "unknown_error": "Đã xảy ra lỗi không mong muốn trong quá trình ký.",
        "select_certificate_button": "📝️ Chọn Chứng chỉ",
        "signing_in_progress": "📝 Đang ký...",
        "modifying_in_progress": "🔧 Đang sửa đổi...",
        "executing_command": "Đang thực thi: {command}",
        "modify_retry_error": "Đã xảy ra lỗi khi sửa đổi, đang thử lại... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Không tìm thấy tệp trong quá trình ký.",
        "ve_err": "Đã xảy ra lỗi giá trị trong quá trình ký.",
        "pe_err": "Đã xảy ra lỗi quyền trong quá trình ký.",
        "unknown_sign_err": "Đã xảy ra lỗi không xác định trong quá trình ký."
    },
    "id": {
        "no_cert_selected": "Halo, {user_first_name}! Silakan pilih sertifikat dari menu /start dan coba lagi. 🚀",
        "sign_error_retry": "Terjadi kesalahan selama penandatanganan, mencoba lagi... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Penandatanganan gagal untuk {file_name}.",
        "unexpected_error": "Terjadi kesalahan tak terduga. Jika masalah ini terus berlanjut, silakan hubungi dukungan.",
        "ipa_ready": "✅ IPA Anda telah ditandatangani dan siap.",
        "forgot_choice": "Sepertinya Anda lupa memilih sertifikat. Silakan buka menu /start untuk memilihnya.",
        "file_lost": "File hilang selama proses penandatanganan.",
        "value_error": "Terjadi kesalahan nilai selama proses penandatanganan.",
        "permission_error": "Terjadi kesalahan izin selama proses penandatanganan.",
        "signing_error": "Operasi penandatanganan gagal.",
        "unknown_error": "Terjadi kesalahan tak terduga selama proses penandatanganan.",
        "select_certificate_button": "📝️ Pilih Sertifikat",
        "signing_in_progress": "📝 Menandatangani...",
        "modifying_in_progress": "🔧 Memodifikasi...",
        "executing_command": "Mengeksekusi: {command}",
        "modify_retry_error": "Terjadi kesalahan saat memodifikasi, mencoba lagi... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "File tidak dapat ditemukan selama proses penandatanganan.",
        "ve_err": "Terjadi kesalahan nilai selama proses penandatanganan.",
        "pe_err": "Terjadi kesalahan izin selama proses penandatanganan.",
        "unknown_sign_err": "Terjadi kesalahan yang tidak diketahui selama proses penandatanganan."
    },
    "pl": {
        "no_cert_selected": "Witaj, {user_first_name}! Proszę wybrać certyfikat z menu /start i spróbować ponownie. 🚀",
        "sign_error_retry": "Wystąpił błąd podczas podpisywania, ponawianie... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Podpisywanie {file_name} nie powiodło się.",
        "unexpected_error": "Wystąpił nieoczekiwany błąd. Jeśli problem będzie się powtarzał, skontaktuj się z pomocą techniczną.",
        "ipa_ready": "✅ Twój plik IPA został podpisany i jest gotowy.",
        "forgot_choice": "Wygląda na to, że zapomniałeś wybrać certyfikat. Przejdź do menu /start, aby go wybrać.",
        "file_lost": "Plik został utracony podczas procesu podpisywania.",
        "value_error": "Wystąpił błąd wartości podczas procesu podpisywania.",
        "permission_error": "Wystąpił błąd uprawnień podczas procesu podpisywania.",
        "signing_error": "Operacja podpisywania nie powiodła się.",
        "unknown_error": "Wystąpił nieoczekiwany błąd podczas procesu podpisywania.",
        "select_certificate_button": "📝️ Wybierz certyfikat",
        "signing_in_progress": "📝 Podpisywanie...",
        "modifying_in_progress": "🔧 Modyfikowanie...",
        "executing_command": "Wykonywanie: {command}",
        "modify_retry_error": "Wystąpił błąd podczas modyfikacji, ponawianie... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Nie można było znaleźć pliku podczas procesu podpisywania.",
        "ve_err": "Wystąpił błąd wartości podczas procesu podpisywania.",
        "pe_err": "Wystąpił błąd uprawnień podczas procesu podpisywania.",
        "unknown_sign_err": "Wystąpił nieznany błąd podczas procesu podpisywania."
    },
    "nl": {
        "no_cert_selected": "Hallo, {user_first_name}! Selecteer een certificaat uit het /start menu en probeer het opnieuw. 🚀",
        "sign_error_retry": "Er is een fout opgetreden tijdens het ondertekenen, opnieuw proberen... ({failed_sign_attempt}/{max_sign_attempt})",
        "signing_failed": "❌ Ondertekenen mislukt voor {file_name}.",
        "unexpected_error": "Er is een onverwachte fout opgetreden. Als dit probleem aanhoudt, neem dan contact op met de ondersteuning.",
        "ipa_ready": "✅ Uw IPA is ondertekend en klaar.",
        "forgot_choice": "Het lijkt erop dat u bent vergeten een certificaat te selecteren. Ga naar het /start menu om er een te kiezen.",
        "file_lost": "Het bestand is verloren gegaan tijdens het ondertekeningsproces.",
        "value_error": "Er is een waardefout opgetreden tijdens het ondertekeningsproces.",
        "permission_error": "Er is een toestemmingsfout opgetreden tijdens het ondertekeningsproces.",
        "signing_error": "De ondertekeningsbewerking is mislukt.",
        "unknown_error": "Er is een onverwachte fout opgetreden tijdens het ondertekeningsproces.",
        "select_certificate_button": "📝️ Certificaat selecteren",
        "signing_in_progress": "📝 Ondertekenen...",
        "modifying_in_progress": "🔧 Wijzigen...",
        "executing_command": "Uitvoeren: {command}",
        "modify_retry_error": "Er is een fout opgetreden tijdens het wijzigen, opnieuw proberen... ({failed_modify_attempt}/{max_modify_attempt})",
        "fnfe_err": "Het bestand kon niet worden gevonden tijdens het ondertekeningsproces.",
        "ve_err": "Er is een waardefout opgetreden tijdens het ondertekeningsproces.",
        "pe_err": "Er is een toestemmingsfout opgetreden tijdens het ondertekeningsproces.",
        "unknown_sign_err": "Er is een onbekende fout opgetreden tijdens het ondertekeningsproces."
    }
}
