# Plugins/start.py
start_strings = {
    "en": {
        "welcome_registered": "Hello, {name}!\nWelcome back. You can now send an IPA file to be signed.",
        "welcome_unregistered": "Hello, {name}!\nTo use this bot, you need to be a registered user. Please contact the administrator for access.",
        "select_certificate": "📝️ Select Certificate",
        "select_compression": "📚 Select Compression",
        "select_language": "🌐 Select Language",
        "approval_purchase": "Contact for Approval / Purchase",
        "settings_button": "⚙️ Settings",
        "settings_text": "Please choose a setting to configure:",
        "back_button": "🔙 Go Back",
    },
    "tr": {
        "welcome_registered": "Merhaba, {name}!\nTekrar hoş geldiniz. Şimdi imzalanacak bir IPA dosyası gönderebilirsiniz.",
        "welcome_unregistered": "Merhaba, {name}!\nBu botu kullanmak için kayıtlı bir kullanıcı olmanız gerekir. Erişim için lütfen yöneticiyle iletişime geçin.",
        "select_certificate": "📝️ Sertifika Seç",
        "select_compression": "📚 Sıkıştırma Seç",
        "select_language": "🌐 Dil Seç",
        "approval_purchase": "Onay / Satın Alma için İletişime Geçin",
        "settings_button": "⚙️ Ayarlar",
        "settings_text": "Lütfen yapılandırmak için bir ayar seçin:",
        "back_button": "🔙 Geri Dön",
    },
    "ru": {
        "welcome_registered": "Здравствуйте, {name}!\nС возвращением. Теперь вы можете отправить IPA-файл для подписи.",
        "welcome_unregistered": "Здравствуйте, {name}!\nЧтобы использовать этого бота, вам необходимо быть зарегистрированным пользователем. Пожалуйста, свяжитесь с администратором для получения доступа.",
        "select_certificate": "📝️ Выбрать сертификат",
        "select_compression": "📚 Выбрать сжатие",
        "select_language": "🌐 Выбрать язык",
        "approval_purchase": "Связаться для одобрения / покупки",
        "settings_button": "⚙️ Настройки",
        "settings_text": "Пожалуйста, выберите параметр для настройки:",
        "back_button": "🔙 Назад",
    },
    "de": {
        "welcome_registered": "Hallo, {name}!\nWillkommen zurück. Du kannst jetzt eine IPA-Datei zum Signieren senden.",
        "welcome_unregistered": "Hallo, {name}!\nUm diesen Bot zu verwenden, musst du ein registrierter Benutzer sein. Bitte kontaktiere den Administrator für den Zugriff.",
        "select_certificate": "📝️ Zertifikat auswählen",
        "select_compression": "📚 Komprimierung auswählen",
        "select_language": "🌐 Sprache auswählen",
        "approval_purchase": "Kontakt für Genehmigung / Kauf",
        "settings_button": "⚙️ Einstellungen",
        "settings_text": "Bitte wähle eine Einstellung zum Konfigurieren aus:",
        "back_button": "🔙 Zurück",
    },
    "es": {
        "welcome_registered": "¡Hola, {name}!\nBienvenido de nuevo. Ahora puedes enviar un archivo IPA para firmar.",
        "welcome_unregistered": "¡Hola, {name}!\nPara usar este bot, debes ser un usuario registrado. Por favor, contacta al administrador para obtener acceso.",
        "select_certificate": "📝️ Seleccionar certificado",
        "select_compression": "📚 Seleccionar compresión",
        "select_language": "🌐 Seleccionar idioma",
        "approval_purchase": "Contactar para aprobación / compra",
        "settings_button": "⚙️ Ajustes",
        "settings_text": "Por favor, elige una configuración para configurar:",
        "back_button": "🔙 Volver",
    },
    "fr": {
        "welcome_registered": "Bonjour, {name}!\nBienvenue de retour. Vous pouvez maintenant envoyer un fichier IPA à signer.",
        "welcome_unregistered": "Bonjour, {name}!\nPour utiliser ce bot, vous devez être un utilisateur enregistré. Veuillez contacter l'administrateur pour l'accès.",
        "select_certificate": "📝️ Sélectionner un certificat",
        "select_compression": "📚 Sélectionner la compression",
        "select_language": "🌐 Sélectionner la langue",
        "approval_purchase": "Contacter pour approbation / achat",
        "settings_button": "⚙️ Paramètres",
        "settings_text": "Veuillez choisir un paramètre à configurer:",
        "back_button": "🔙 Retour",
    },
    "zh-cn": {
        "welcome_registered": "您好, {name}!\n欢迎回来。您现在可以发送 IPA 文件进行签名。",
        "welcome_unregistered": "您好, {name}!\n要使用此机器人，您需要成为注册用户。请联系管理员获取访问权限。",
        "select_certificate": "📝️ 选择证书",
        "select_compression": "📚 选择压缩",
        "select_language": "🌐 选择语言",
        "approval_purchase": "联系以获取批准/购买",
        "settings_button": "⚙️ 设置",
        "settings_text": "请选择要配置的设置:",
        "back_button": "🔙 返回",
    },
    "ar": {
        "welcome_registered": "مرحباً، {name}!\nأهلاً بك مرة أخرى. يمكنك الآن إرسال ملف IPA لتوقيعه.",
        "welcome_unregistered": "مرحباً، {name}!\nلاستخدام هذا البوت، يجب أن تكون مستخدمًا مسجلاً. يرجى الاتصال بالمسؤول للوصول.",
        "select_certificate": "📝️ تحديد الشهادة",
        "select_compression": "📚 تحديد الضغط",
        "select_language": "🌐 تحديد اللغة",
        "approval_purchase": "اتصل للموافقة / الشراء",
        "settings_button": "⚙️ الإعدادات",
        "settings_text": "الرجاء اختيار إعداد للتكوين:",
        "back_button": "🔙 رجوع"
    },
    "pt": {
        "welcome_registered": "Olá, {name}!\nBem-vindo de volta. Agora você pode enviar um arquivo IPA para ser assinado.",
        "welcome_unregistered": "Olá, {name}!\nPara usar este bot, você precisa ser um usuário registrado. Por favor, entre em contato com o administrador para acesso.",
        "select_certificate": "📝️ Selecionar Certificado",
        "select_compression": "📚 Selecionar Compressão",
        "select_language": "🌐 Selecionar Idioma",
        "approval_purchase": "Contato para Aprovação / Compra",
        "settings_button": "⚙️ Configurações",
        "settings_text": "Por favor, escolha uma configuração para configurar:",
        "back_button": "🔙 Voltar"
    },
    "it": {
        "welcome_registered": "Ciao, {name}!\nBentornato. Ora puoi inviare un file IPA da firmare.",
        "welcome_unregistered": "Ciao, {name}!\nPer usare questo bot, devi essere un utente registrato. Contatta l'amministratore per l'accesso.",
        "select_certificate": "📝️ Seleziona Certificato",
        "select_compression": "📚 Seleziona Compressione",
        "select_language": "🌐 Seleziona Lingua",
        "approval_purchase": "Contatta per Approvazione / Acquisto",
        "settings_button": "⚙️ Impostazioni",
        "settings_text": "Scegli un'impostazione da configurare:",
        "back_button": "🔙 Indietro"
    },
    "ja": {
        "welcome_registered": "こんにちは、{name}さん！\nおかえりなさい。署名するIPAファイルを送信できるようになりました。",
        "welcome_unregistered": "こんにちは、{name}さん！\nこのボットを使用するには、登録ユーザーである必要があります。アクセスするには管理者にお問い合わせください。",
        "select_certificate": "📝️ 証明書を選択",
        "select_compression": "📚 圧縮を選択",
        "select_language": "🌐 言語を選択",
        "approval_purchase": "承認/購入について問い合わせる",
        "settings_button": "⚙️ 設定",
        "settings_text": "設定する項目を選択してください:",
        "back_button": "🔙 戻る"
    },
    "ko": {
        "welcome_registered": "안녕하세요, {name}님!\n다시 오신 것을 환영합니다. 이제 서명할 IPA 파일을 보낼 수 있습니다.",
        "welcome_unregistered": "안녕하세요, {name}님!\n이 봇을 사용하려면 등록된 사용자여야 합니다. 액세스하려면 관리자에게 문의하십시오.",
        "select_certificate": "📝️ 인증서 선택",
        "select_compression": "📚 압축 선택",
        "select_language": "🌐 언어 선택",
        "approval_purchase": "승인/구매 문의",
        "settings_button": "⚙️ 설정",
        "settings_text": "구성할 설정을 선택하십시오:",
        "back_button": "🔙 뒤로"
    },
    "hi": {
        "welcome_registered": "नमस्ते, {name}!\nवापस स्वागत है। अब आप हस्ताक्षर करने के लिए एक IPA फ़ाइल भेज सकते हैं।",
        "welcome_unregistered": "नमस्ते, {name}!\nइस बॉट का उपयोग करने के लिए, आपको एक पंजीकृत उपयोगकर्ता होना चाहिए। पहुँच के लिए कृपया व्यवस्थापक से संपर्क करें।",
        "select_certificate": "📝️ प्रमाणपत्र चुनें",
        "select_compression": "📚 संपीड़न चुनें",
        "select_language": "🌐 भाषा चुनें",
        "approval_purchase": "अनुमोदन / खरीद के लिए संपर्क करें",
        "settings_button": "⚙️ सेटिंग्स",
        "settings_text": "कृपया कॉन्फ़िगर करने के लिए एक सेटिंग चुनें:",
        "back_button": "🔙 वापस जाएं"
    },
    "vi": {
        "welcome_registered": "Xin chào, {name}!\nChào mừng trở lại. Bây giờ bạn có thể gửi tệp IPA để ký.",
        "welcome_unregistered": "Xin chào, {name}!\nĐể sử dụng bot này, bạn cần phải là người dùng đã đăng ký. Vui lòng liên hệ quản trị viên để được cấp quyền truy cập.",
        "select_certificate": "📝️ Chọn Chứng chỉ",
        "select_compression": "📚 Chọn Nén",
        "select_language": "🌐 Chọn Ngôn ngữ",
        "approval_purchase": "Liên hệ để Phê duyệt / Mua hàng",
        "settings_button": "⚙️ Cài đặt",
        "settings_text": "Vui lòng chọn một cài đặt để cấu hình:",
        "back_button": "🔙 Quay lại"
    },
    "id": {
        "welcome_registered": "Halo, {name}!\nSelamat datang kembali. Sekarang Anda dapat mengirim file IPA untuk ditandatangani.",
        "welcome_unregistered": "Halo, {name}!\nUntuk menggunakan bot ini, Anda harus menjadi pengguna terdaftar. Silakan hubungi administrator untuk akses.",
        "select_certificate": "📝️ Pilih Sertifikat",
        "select_compression": "📚 Pilih Kompresi",
        "select_language": "🌐 Pilih Bahasa",
        "approval_purchase": "Hubungi untuk Persetujuan / Pembelian",
        "settings_button": "⚙️ Pengaturan",
        "settings_text": "Silakan pilih pengaturan untuk dikonfigurasi:",
        "back_button": "🔙 Kembali"
    },
    "pl": {
        "welcome_registered": "Witaj, {name}!\nWitamy ponownie. Możesz teraz wysłać plik IPA do podpisania.",
        "welcome_unregistered": "Witaj, {name}!\nAby korzystać z tego bota, musisz być zarejestrowanym użytkownikiem. Skontaktuj się z administratorem w celu uzyskania dostępu.",
        "select_certificate": "📝️ Wybierz certyfikat",
        "select_compression": "📚 Wybierz kompresję",
        "select_language": "🌐 Wybierz język",
        "approval_purchase": "Kontakt w sprawie zatwierdzenia / zakupu",
        "settings_button": "⚙️ Ustawienia",
        "settings_text": "Proszę wybrać ustawienie do konfiguracji:",
        "back_button": "🔙 Wróć"
    },
    "nl": {
        "welcome_registered": "Hallo, {name}!\nWelkom terug. U kunt nu een IPA-bestand ter ondertekening verzenden.",
        "welcome_unregistered": "Hallo, {name}!\nOm deze bot te gebruiken, moet u een geregistreerde gebruiker zijn. Neem contact op met de beheerder voor toegang.",
        "select_certificate": "📝️ Certificaat selecteren",
        "select_compression": "📚 Compressie selecteren",
        "select_language": "🌐 Taal selecteren",
        "approval_purchase": "Contact opnemen voor goedkeuring / aankoop",
        "settings_button": "⚙️ Instellingen",
        "settings_text": "Kies een instelling om te configureren:",
        "back_button": "🔙 Terug"
    }
}
