# Plugins/user_management.py
user_management_strings = {
    "en": {
        "admin_only": "This command is for administrators only.",
        "invalid_command": "Invalid command format. Use /user [ID] or /premium [ID].",
        "user_not_found": "User with ID `{user_id}` was not found.",
        "user_added": "User `{user_id}` has been registered.",
        "user_removed": "User `{user_id}` has been unregistered.",
        "premium_added": "User `{user_id}` has been upgraded to premium. Expires on {expiry_date}.",
        "premium_removed": "Premium status has been removed for user `{user_id}`.",
        "premium_error": "An error occurred during the premium operation.",
        "premium_reg_error": "An error occurred while registering the premium user.",
        "premium_unreg_error": "An error occurred while unregistering the premium user.",
        "not_enough_arguments": "Please provide at least one user ID."
    },
    "tr": {
        "admin_only": "Bu komut sadece yöneticiler içindir.",
        "invalid_command": "Geçersiz komut formatı. /user [ID] veya /premium [ID] kullanın.",
        "user_not_found": "`{user_id}` ID'li kullanıcı bulunamadı.",
        "user_added": "`{user_id}` kullanıcısı kaydedildi.",
        "user_removed": "`{user_id}` kullanıcısının kaydı silindi.",
        "premium_added": "`{user_id}` kullanıcısı premium'a yükseltildi. Bitiş tarihi: {expiry_date}.",
        "premium_removed": "`{user_id}` kullanıcısının premium durumu kaldırıldı.",
        "premium_error": "Premium işlemi sırasında bir hata oluştu.",
        "premium_reg_error": "Premium kullanıcı kaydedilirken bir hata oluştu.",
        "premium_unreg_error": "Premium kullanıcının kaydı silinirken bir hata oluştu.",
        "not_enough_arguments": "Lütfen en az bir kullanıcı ID'si belirtin."
    },
    "ru": {
        "admin_only": "Эта команда только для администраторов.",
        "invalid_command": "Неверный формат команды. Используйте /user [ID] или /premium [ID].",
        "user_not_found": "Пользователь с ID `{user_id}` не найден.",
        "user_added": "Пользователь `{user_id}` зарегистрирован.",
        "user_removed": "Пользователь `{user_id}` снят с регистрации.",
        "premium_added": "Пользователь `{user_id}` повышен до премиума. Истекает {expiry_date}.",
        "premium_removed": "Статус премиум для пользователя `{user_id}` удален.",
        "premium_error": "Произошла ошибка во время операции с премиум.",
        "premium_reg_error": "Произошла ошибка при регистрации премиум-пользователя.",
        "premium_unreg_error": "Произошла ошибка при снятии с регистрации премиум-пользователя.",
        "not_enough_arguments": "Пожалуйста, укажите хотя бы один идентификатор пользователя."
    },
    "de": {
        "admin_only": "Dieser Befehl ist nur für Administratoren.",
        "invalid_command": "Ungültiges Befehlsformat. Verwende /user [ID] oder /premium [ID].",
        "user_not_found": "Benutzer mit ID `{user_id}` wurde nicht gefunden.",
        "user_added": "Benutzer `{user_id}` wurde registriert.",
        "user_removed": "Benutzer `{user_id}` wurde deregistriert.",
        "premium_added": "Benutzer `{user_id}` wurde auf Premium hochgestuft. Läuft am {expiry_date} ab.",
        "premium_removed": "Premium-Status für Benutzer `{user_id}` wurde entfernt.",
        "premium_error": "Bei der Premium-Operation ist ein Fehler aufgetreten.",
        "premium_reg_error": "Beim Registrieren des Premium-Benutzers ist ein Fehler aufgetreten.",
        "premium_unreg_error": "Beim Deregistrieren des Premium-Benutzers ist ein Fehler aufgetreten.",
        "not_enough_arguments": "Bitte gib mindestens eine Benutzer-ID an."
    },
    "es": {
        "admin_only": "Este comando es solo para administradores.",
        "invalid_command": "Formato de comando no válido. Usa /user [ID] o /premium [ID].",
        "user_not_found": "No se encontró el usuario con ID `{user_id}`.",
        "user_added": "El usuario `{user_id}` ha sido registrado.",
        "user_removed": "El usuario `{user_id}` ha sido dado de baja.",
        "premium_added": "El usuario `{user_id}` ha sido actualizado a premium. Expira el {expiry_date}.",
        "premium_removed": "El estado premium ha sido eliminado para el usuario `{user_id}`.",
        "premium_error": "Ocurrió un error durante la operación premium.",
        "premium_reg_error": "Ocurrió un error al registrar el usuario premium.",
        "premium_unreg_error": "Ocurrió un error al dar de baja al usuario premium.",
        "not_enough_arguments": "Por favor, proporciona al menos un ID de usuario."
    },
    "fr": {
        "admin_only": "Cette commande est réservée aux administrateurs.",
        "invalid_command": "Format de commande invalide. Utilisez /user [ID] ou /premium [ID].",
        "user_not_found": "Utilisateur avec l'ID `{user_id}` introuvable.",
        "user_added": "L'utilisateur `{user_id}` a été enregistré.",
        "user_removed": "L'utilisateur `{user_id}` a été désenregistré.",
        "premium_added": "L'utilisateur `{user_id}` a été mis à niveau vers premium. Expire le {expiry_date}.",
        "premium_removed": "Le statut premium a été supprimé pour l'utilisateur `{user_id}`.",
        "premium_error": "Une erreur est survenue lors de l'opération premium.",
        "premium_reg_error": "Une erreur est survenue lors de l'enregistrement de l'utilisateur premium.",
        "premium_unreg_error": "Une erreur est survenue lors de la désinscription de l'utilisateur premium.",
        "not_enough_arguments": "Veuillez fournir au moins un ID utilisateur."
    },
    "zh-cn": {
        "admin_only": "此命令仅供管理员使用。",
        "invalid_command": "无效的命令格式。使用 /user [ID] 或 /premium [ID]。",
        "user_not_found": "找不到 ID 为 `{user_id}` 的用户。",
        "user_added": "用户 `{user_id}` 已注册。",
        "user_removed": "用户 `{user_id}` 已注销。",
        "premium_added": "用户 `{user_id}` 已升级为高级用户。{expiry_date} 到期。",
        "premium_removed": "用户 `{user_id}` 的高级状态已移除。",
        "premium_error": "高级操作期间发生错误。",
        "premium_reg_error": "注册高级用户时发生错误。",
        "premium_unreg_error": "注销高级用户时发生错误。",
        "not_enough_arguments": "请提供至少一个用户 ID。"
    },
    "ar": {
        "admin_only": "هذا الأمر للمسؤولين فقط.",
        "invalid_command": "تنسيق الأمر غير صالح. استخدم /user [ID] أو /premium [ID].",
        "user_not_found": "لم يتم العثور على المستخدم بالمعرف `{user_id}`.",
        "user_added": "تم تسجيل المستخدم `{user_id}`.",
        "user_removed": "تم إلغاء تسجيل المستخدم `{user_id}`.",
        "premium_added": "تمت ترقية المستخدم `{user_id}` إلى بريميوم. ينتهي في {expiry_date}.",
        "premium_removed": "تمت إزالة حالة البريميوم للمستخدم `{user_id}`.",
        "premium_error": "حدث خطأ أثناء عملية البريميوم.",
        "premium_reg_error": "حدث خطأ أثناء تسجيل المستخدم البريميوم.",
        "premium_unreg_error": "حدث خطأ أثناء إلغاء تسجيل المستخدم البريميوم.",
        "not_enough_arguments": "الرجاء تقديم معرف مستخدم واحد على الأقل."
    },
    "pt": {
        "admin_only": "Este comando é apenas para administradores.",
        "invalid_command": "Formato de comando inválido. Use /user [ID] ou /premium [ID].",
        "user_not_found": "Usuário com ID `{user_id}` não encontrado.",
        "user_added": "Usuário `{user_id}` foi registrado.",
        "user_removed": "Usuário `{user_id}` foi desregistrado.",
        "premium_added": "Usuário `{user_id}` foi atualizado para premium. Expira em {expiry_date}.",
        "premium_removed": "Status premium foi removido para o usuário `{user_id}`.",
        "premium_error": "Ocorreu um erro durante a operação premium.",
        "premium_reg_error": "Ocorreu um erro ao registrar o usuário premium.",
        "premium_unreg_error": "Ocorreu um erro ao desregistrar o usuário premium.",
        "not_enough_arguments": "Por favor, forneça pelo menos um ID de usuário."
    },
    "it": {
        "admin_only": "Questo comando è solo per gli amministratori.",
        "invalid_command": "Formato comando non valido. Usa /user [ID] o /premium [ID].",
        "user_not_found": "Utente con ID `{user_id}` non trovato.",
        "user_added": "Utente `{user_id}` è stato registrato.",
        "user_removed": "Utente `{user_id}` è stato deregistrato.",
        "premium_added": "Utente `{user_id}` è stato aggiornato a premium. Scade il {expiry_date}.",
        "premium_removed": "Lo stato premium è stato rimosso per l'utente `{user_id}`.",
        "premium_error": "Si è verificato un errore durante l'operazione premium.",
        "premium_reg_error": "Si è verificato un errore durante la registrazione dell'utente premium.",
        "premium_unreg_error": "Si è verificato un errore durante la deregistrazione dell'utente premium.",
        "not_enough_arguments": "Fornisci almeno un ID utente."
    },
    "ja": {
        "admin_only": "このコマンドは管理者専用です。",
        "invalid_command": "無効なコマンド形式です。/user [ID] または /premium [ID] を使用してください。",
        "user_not_found": "ID `{user_id}` のユーザーは見つかりませんでした。",
        "user_added": "ユーザー `{user_id}` が登録されました。",
        "user_removed": "ユーザー `{user_id}` の登録が解除されました。",
        "premium_added": "ユーザー `{user_id}` はプレミアムにアップグレードされました。{expiry_date} に期限切れになります。",
        "premium_removed": "ユーザー `{user_id}` のプレミアムステータスが削除されました。",
        "premium_error": "プレミアム操作中にエラーが発生しました。",
        "premium_reg_error": "プレミアムユーザーの登録中にエラーが発生しました。",
        "premium_unreg_error": "プレミアムユーザーの登録解除中にエラーが発生しました。",
        "not_enough_arguments": "少なくとも1つのユーザーIDを指定してください。"
    },
    "ko": {
        "admin_only": "이 명령은 관리자 전용입니다.",
        "invalid_command": "잘못된 명령 형식입니다. /user [ID] 또는 /premium [ID]를 사용하십시오.",
        "user_not_found": "ID `{user_id}`를 가진 사용자를 찾을 수 없습니다.",
        "user_added": "사용자 `{user_id}`가 등록되었습니다.",
        "user_removed": "사용자 `{user_id}`가 등록 해제되었습니다.",
        "premium_added": "사용자 `{user_id}`가 프리미엄으로 업그레이드되었습니다. {expiry_date}에 만료됩니다.",
        "premium_removed": "사용자 `{user_id}`의 프리미엄 상태가 제거되었습니다.",
        "premium_error": "프리미엄 작업 중 오류가 발생했습니다.",
        "premium_reg_error": "프리미엄 사용자 등록 중 오류가 발생했습니다.",
        "premium_unreg_error": "프리미엄 사용자 등록 해제 중 오류가 발생했습니다.",
        "not_enough_arguments": "하나 이상의 사용자 ID를 제공하십시오."
    },
    "hi": {
        "admin_only": "यह कमांड केवल प्रशासकों के लिए है।",
        "invalid_command": "अमान्य कमांड प्रारूप। /user [ID] या /premium [ID] का उपयोग करें।",
        "user_not_found": "ID `{user_id}` वाला उपयोगकर्ता नहीं मिला।",
        "user_added": "उपयोगकर्ता `{user_id}` पंजीकृत हो गया है।",
        "user_removed": "उपयोगकर्ता `{user_id}` अपंजीकृत हो गया है।",
        "premium_added": "उपयोगकर्ता `{user_id}` को प्रीमियम में अपग्रेड कर दिया गया है। {expiry_date} को समाप्त होता है।",
        "premium_removed": "उपयोगकर्ता `{user_id}` के लिए प्रीमियम स्थिति हटा दी गई है।",
        "premium_error": "प्रीमियम ऑपरेशन के दौरान एक त्रुटि हुई।",
        "premium_reg_error": "प्रीमियम उपयोगकर्ता को पंजीकृत करते समय एक त्रुटि हुई।",
        "premium_unreg_error": "प्रीमियम उपयोगकर्ता को अपंजीकृत करते समय एक त्रुटि हुई।",
        "not_enough_arguments": "कृपया कम से कम एक उपयोगकर्ता आईडी प्रदान करें।"
    },
    "vi": {
        "admin_only": "Lệnh này chỉ dành cho quản trị viên.",
        "invalid_command": "Định dạng lệnh không hợp lệ. Sử dụng /user [ID] hoặc /premium [ID].",
        "user_not_found": "Không tìm thấy người dùng có ID `{user_id}`.",
        "user_added": "Người dùng `{user_id}` đã được đăng ký.",
        "user_removed": "Người dùng `{user_id}` đã bị hủy đăng ký.",
        "premium_added": "Người dùng `{user_id}` đã được nâng cấp lên premium. Hết hạn vào {expiry_date}.",
        "premium_removed": "Trạng thái premium đã bị xóa đối với người dùng `{user_id}`.",
        "premium_error": "Đã xảy ra lỗi trong quá trình hoạt động premium.",
        "premium_reg_error": "Đã xảy ra lỗi khi đăng ký người dùng premium.",
        "premium_unreg_error": "Đã xảy ra lỗi khi hủy đăng ký người dùng premium.",
        "not_enough_arguments": "Vui lòng cung cấp ít nhất một ID người dùng."
    },
    "id": {
        "admin_only": "Perintah ini hanya untuk administrator.",
        "invalid_command": "Format perintah tidak valid. Gunakan /user [ID] atau /premium [ID].",
        "user_not_found": "Pengguna dengan ID `{user_id}` tidak ditemukan.",
        "user_added": "Pengguna `{user_id}` telah terdaftar.",
        "user_removed": "Pengguna `{user_id}` telah dibatalkan pendaftarannya.",
        "premium_added": "Pengguna `{user_id}` telah ditingkatkan ke premium. Kedaluwarsa pada {expiry_date}.",
        "premium_removed": "Status premium telah dihapus untuk pengguna `{user_id}`.",
        "premium_error": "Terjadi kesalahan selama operasi premium.",
        "premium_reg_error": "Terjadi kesalahan saat mendaftarkan pengguna premium.",
        "premium_unreg_error": "Terjadi kesalahan saat membatalkan pendaftaran pengguna premium.",
        "not_enough_arguments": "Harap berikan setidaknya satu ID pengguna."
    },
    "pl": {
        "admin_only": "To polecenie jest tylko dla administratorów.",
        "invalid_command": "Nieprawidłowy format polecenia. Użyj /user [ID] lub /premium [ID].",
        "user_not_found": "Użytkownik o identyfikatorze `{user_id}` nie został znaleziony.",
        "user_added": "Użytkownik `{user_id}` został zarejestrowany.",
        "user_removed": "Użytkownik `{user_id}` został wyrejestrowany.",
        "premium_added": "Użytkownik `{user_id}` został ulepszony do wersji premium. Wygasa dnia {expiry_date}.",
        "premium_removed": "Status premium został usunięty dla użytkownika `{user_id}`.",
        "premium_error": "Wystąpił błąd podczas operacji premium.",
        "premium_reg_error": "Wystąpił błąd podczas rejestracji użytkownika premium.",
        "premium_unreg_error": "Wystąpił błąd podczas wyrejestrowywania użytkownika premium.",
        "not_enough_arguments": "Proszę podać co najmniej jeden identyfikator użytkownika."
    },
    "nl": {
        "admin_only": "Dit commando is alleen voor beheerders.",
        "invalid_command": "Ongeldig commandoformaat. Gebruik /user [ID] of /premium [ID].",
        "user_not_found": "Gebruiker met ID `{user_id}` is niet gevonden.",
        "user_added": "Gebruiker `{user_id}` is geregistreerd.",
        "user_removed": "Gebruiker `{user_id}` is uitgeschreven.",
        "premium_added": "Gebruiker `{user_id}` is geüpgraded naar premium. Verloopt op {expiry_date}.",
        "premium_removed": "Premiumstatus is verwijderd voor gebruiker `{user_id}`.",
        "premium_error": "Er is een fout opgetreden tijdens de premium-bewerking.",
        "premium_reg_error": "Er is een fout opgetreden bij het registreren van de premium-gebruiker.",
        "premium_unreg_error": "Er is een fout opgetreden bij het uitschrijven van de premium-gebruiker.",
        "not_enough_arguments": "Geef ten minste één gebruikers-ID op."
    }
}
