class Chinese:
    strings = {
        "save_error": "无法保存 {options}。错误: {error}。",
        "update_error": "无法更新 {options}。错误: {error}。",
        "app_name_usage": "用法: /name [新应用名称]",
        "unset_app_name": "应用名称修改已重置。",
        "set_app_name": "应用名称将更改为 **{name}**。",
        "app_version_usage": "用法: /version [新版本]",
        "invalid_app_version": "版本格式无效。请仅使用数字和点（例如，1.2.3）。",
        "unset_app_version": "应用版本修改已重置。",
        "set_app_version": "应用版本将更改为 **{version}**。",
        "app_id_usage": "用法: /id [新 Bundle ID]",
        "unset_app_id": "Bundle ID 修改已重置。",
        "set_app_id": "Bundle ID 将更改为 **{id}**。",
        "min_os_usage": "用法: /minos [版本]",
        "invalid_min_os": "操作系统版本格式无效。请仅使用数字和点（例如，15.0）。",
        "unset_min_os": "最低操作系统版本修改已重置。",
        "set_min_os": "最低操作系统版本将设置为 **{os_version}**。",
        "unset_profile_removal": "嵌入式配置文件将不再被移除。",
        "set_profile_removal": "嵌入式配置文件将被移除。",
        "tweak_added_expecting_ipa": "已添加 Tweak: {file_name}。现在发送 IPA 文件以应用它。",
        "unset_remove_watch": "移除 Watch Bundle 修改已重置。",
        "set_remove_watch": "将设置移除 Watch Bundle。",
        "error_while_resetting": "重置选项时发生错误: {error}。"
    }
