class German:
    strings = {
        "save_error": "Konnte {options} nicht speichern. Fehler: {error}.",
        "update_error": "Konnte {options} nicht aktualisieren. Fehler: {error}.",
        "app_name_usage": "Verwendung: /name [neuer App-Name]",
        "unset_app_name": "Änderung des App-Namens wurde zurückgesetzt.",
        "set_app_name": "Der App-Name wird in **{name}** geändert.",
        "app_version_usage": "Verwendung: /version [neue Version]",
        "invalid_app_version": "Ungültiges Versionsformat. Bitte nur Zahlen und Punkte verwenden (z.B. 1.2.3).",
        "unset_app_version": "Änderung der App-Version wurde zurückgesetzt.",
        "set_app_version": "Die App-Version wird in **{version}** geändert.",
        "app_id_usage": "Verwendung: /id [neue Bundle-ID]",
        "unset_app_id": "Änderung der Bundle-ID wurde zurückgesetzt.",
        "set_app_id": "Die Bundle-ID wird in **{id}** geändert.",
        "min_os_usage": "Verwendung: /minos [Version]",
        "invalid_min_os": "Ungültiges Betriebssystem-Versionsformat. Bitte nur Zahlen und Punkte verwenden (z.B. 15.0).",
        "unset_min_os": "Änderung der Mindest-Betriebssystemversion wurde zurückgesetzt.",
        "set_min_os": "Die Mindest-Betriebssystemversion wird auf **{os_version}** gesetzt.",
        "unset_profile_removal": "Eingebettetes Profil wird nicht mehr entfernt.",
        "set_profile_removal": "Eingebettetes Profil wird entfernt.",
        "tweak_added_expecting_ipa": "Tweak hinzugefügt: {file_name}. Senden Sie jetzt die IPA-Datei, um ihn anzuwenden.",
        "unset_remove_watch": "Die Änderung des Watch-Bundles wurde zurückgesetzt.",
        "set_remove_watch": "Das Entfernen des Watch-Bundles wird eingestellt.",
        "error_while_resetting": "Beim Zurücksetzen der Optionen ist ein Fehler aufgetreten: {error}."
    }
