class French:
    strings = {
        "save_error": "Impossible d'enregistrer {options}. Erreur: {error}.",
        "update_error": "Impossible de mettre à jour {options}. Erreur: {error}.",
        "app_name_usage": "Utilisation: /name [nouveau nom d'application]",
        "unset_app_name": "La modification du nom de l'application a été réinitialisée.",
        "set_app_name": "Le nom de l'application sera changé en **{name}**.",
        "app_version_usage": "Utilisation: /version [nouvelle version]",
        "invalid_app_version": "Format de version invalide. Veuillez utiliser uniquement des chiffres et des points (par exemple, 1.2.3).",
        "unset_app_version": "La modification de la version de l'application a été réinitialisée.",
        "set_app_version": "La version de l'application sera changée en **{version}**.",
        "app_id_usage": "Utilisation: /id [nouvel ID de bundle]",
        "unset_app_id": "La modification de l'ID de bundle a été réinitialisée.",
        "set_app_id": "L'ID de bundle sera changé en **{id}**.",
        "min_os_usage": "Utilisation: /minos [version]",
        "invalid_min_os": "Format de version OS invalide. Veuillez utiliser uniquement des chiffres et des points (par exemple, 15.0).",
        "unset_min_os": "La modification de la version minimale de l'OS a été réinitialisée.",
        "set_min_os": "La version minimale de l'OS sera définie sur **{os_version}**.",
        "unset_profile_removal": "Le profil intégré ne sera plus supprimé.",
        "set_profile_removal": "Le profil intégré sera supprimé.",
        "tweak_added_expecting_ipa": "Tweak ajouté: {file_name}. Envoyez maintenant le fichier IPA pour l'appliquer.",
        "unset_remove_watch": "La modification du bundle Watch a été réinitialisée.",
        "set_remove_watch": "La suppression du bundle Watch sera définie.",
        "error_while_resetting": "Une erreur est survenue lors de la réinitialisation des options: {error}."
    }
