class Indonesian:
    strings = {
        "save_error": "Tidak dapat menyimpan {options}. Kesalahan: {error}.",
        "update_error": "Tidak dapat memperbarui {options}. Kesalahan: {error}.",
        "app_name_usage": "Penggunaan: /name [nama aplikasi baru]",
        "unset_app_name": "Modifikasi nama aplikasi telah diatur ulang.",
        "set_app_name": "Nama aplikasi akan diubah menjadi **{name}**.",
        "app_version_usage": "Penggunaan: /version [versi baru]",
        "invalid_app_version": "Format versi tidak valid. Harap gunakan angka dan titik saja (misalnya, 1.2.3).",
        "unset_app_version": "Modifikasi versi aplikasi telah diatur ulang.",
        "set_app_version": "Versi aplikasi akan diubah menjadi **{version}**.",
        "app_id_usage": "Penggunaan: /id [ID bundel baru]",
        "unset_app_id": "Modifikasi ID bundel telah diatur ulang.",
        "set_app_id": "ID bundel akan diubah menjadi **{id}**.",
        "min_os_usage": "Penggunaan: /minos [versi]",
        "invalid_min_os": "Format versi OS tidak valid. Harap gunakan angka dan titik saja (misalnya, 15.0).",
        "unset_min_os": "Modifikasi versi OS minimum telah diatur ulang.",
        "set_min_os": "Versi OS minimum akan diatur ke **{os_version}**.",
        "unset_profile_removal": "Profil tertanam tidak akan lagi dihapus.",
        "set_profile_removal": "Profil tertanam akan dihapus.",
        "tweak_added_expecting_ipa": "Tweak ditambahkan: {file_name}. Sekarang kirim file IPA untuk menerapkannya.",
        "unset_remove_watch": "Modifikasi Watch Bundle telah diatur ulang.",
        "set_remove_watch": "Watch Bundle akan diatur untuk dihapus.",
        "error_while_resetting": "Terjadi kesalahan saat mengatur ulang opsi: {error}."
    }
