class Italian:
    strings = {
        "save_error": "Impossibile salvare {options}. Errore: {error}.",
        "update_error": "Impossibile aggiornare {options}. Errore: {error}.",
        "app_name_usage": "Uso: /name [nuovo nome app]",
        "unset_app_name": "La modifica del nome dell'app è stata reimpostata.",
        "set_app_name": "Il nome dell'app verrà cambiato in **{name}**.",
        "app_version_usage": "Uso: /version [nuova versione]",
        "invalid_app_version": "Formato versione non valido. Utilizzare solo numeri e punti (es. 1.2.3).",
        "unset_app_version": "La modifica della versione dell'app è stata reimpostata.",
        "set_app_version": "La versione dell'app verrà cambiata in **{version}**.",
        "app_id_usage": "Uso: /id [nuovo ID bundle]",
        "unset_app_id": "La modifica dell'ID bundle è stata reimpostata.",
        "set_app_id": "L'ID bundle verrà cambiato in **{id}**.",
        "min_os_usage": "Uso: /minos [versione]",
        "invalid_min_os": "Formato versione OS non valido. Utilizzare solo numeri e punti (es. 15.0).",
        "unset_min_os": "La modifica della versione minima del sistema operativo è stata reimpostata.",
        "set_min_os": "La versione minima del sistema operativo verrà impostata su **{os_version}**.",
        "unset_profile_removal": "Il profilo incorporato non verrà più rimosso.",
        "set_profile_removal": "Il profilo incorporato verrà rimosso.",
        "tweak_added_expecting_ipa": "Tweak aggiunto: {file_name}. Ora invia il file IPA per applicarlo.",
        "unset_remove_watch": "La modifica del Watch Bundle è stata reimpostata.",
        "set_remove_watch": "La rimozione del Watch Bundle verrà impostata.",
        "error_while_resetting": "Si è verificato un errore durante il ripristino delle opzioni: {error}."
    }
