class Japanese:
    strings = {
        "update_error": "",
        "unset_min_os": "",
        "unset_app_version": "",
        "unset_app_name": "",
        "unset_app_id": "",
        "tweak_added_expecting_ipa": "",
        "set_min_os": "",
        "set_app_version": "",
        "set_app_name": "",
        "set_app_id": "",
        "min_os_usage": "",
        "invalid_min_os": "",
        "invalid_app_version": "",
        "error_while_resetting": "",
        "app_version_usage": "",
        "app_name_usage": "",
        "app_id_usage": "",
    }
