class Polish:
    strings = {
        "save_error": "Nie można zapisać {options}. Błąd: {error}.",
        "update_error": "Nie można zaktualizować {options}. Błąd: {error}.",
        "app_name_usage": "Użycie: /name [nowa nazwa aplikacji]",
        "unset_app_name": "Modyfikacja nazwy aplikacji została zresetowana.",
        "set_app_name": "Nazwa aplikacji zostanie zmieniona na **{name}**.",
        "app_version_usage": "Użycie: /version [nowa wersja]",
        "invalid_app_version": "Nieprawidłowy format wersji. Proszę używać tylko cyfr i kropek (np. 1.2.3).",
        "unset_app_version": "Modyfikacja wersji aplikacji została zresetowana.",
        "set_app_version": "Wersja aplikacji zostanie zmieniona na **{version}**.",
        "app_id_usage": "Użycie: /id [nowy identyfikator pakietu]",
        "unset_app_id": "Modyfikacja identyfikatora pakietu została zresetowana.",
        "set_app_id": "Identyfikator pakietu zostanie zmieniony na **{id}**.",
        "min_os_usage": "Użycie: /minos [wersja]",
        "invalid_min_os": "Nieprawidłowy format wersji systemu operacyjnego. Proszę używać tylko cyfr i kropek (np. 15.0).",
        "unset_min_os": "Modyfikacja minimalnej wersji systemu operacyjnego została zresetowana.",
        "set_min_os": "Minimalna wersja systemu operacyjnego zostanie ustawiona na **{os_version}**.",
        "unset_profile_removal": "Osadzony profil nie będzie już usuwany.",
        "set_profile_removal": "Osadzony profil zostanie usunięty.",
        "tweak_added_expecting_ipa": "Dodano Tweak: {file_name}. Teraz wyślij plik IPA, aby go zastosować.",
        "error_while_resetting": "Wystąpił błąd podczas resetowania opcji: {error}."
    },
    "nl": {
        "save_error": "Kon {options} niet opslaan. Fout: {error}.",
        "update_error": "Kon {options} niet bijwerken. Fout: {error}.",
        "app_name_usage": "Gebruik: /name [nieuwe appnaam]",
        "unset_app_name": "Appnaamwijziging is gereset.",
        "set_app_name": "Appnaam wordt gewijzigd naar **{name}**.",
        "app_version_usage": "Gebruik: /version [nieuwe versie]",
        "invalid_app_version": "Ongeldig versieformaat. Gebruik alleen cijfers en punten (bijv. 1.2.3).",
        "unset_app_version": "Appversiewijziging is gereset.",
        "set_app_version": "Appversie wordt gewijzigd naar **{version}**.",
        "app_id_usage": "Gebruik: /id [nieuwe bundel-ID]",
        "unset_app_id": "Bundel-ID wijziging is gereset.",
        "set_app_id": "Bundel-ID wordt gewijzigd naar **{id}**.",
        "min_os_usage": "Gebruik: /minos [versie]",
        "invalid_min_os": "Ongeldig OS-versieformaat. Gebruik alleen cijfers en punten (bijv. 15.0).",
        "unset_min_os": "Minimale OS-versiewijziging is gereset.",
        "set_min_os": "Minimale OS-versie wordt ingesteld op **{os_version}**.",
        "unset_profile_removal": "Ingebed profiel wordt niet langer verwijderd.",
        "set_profile_removal": "Ingebed profiel wordt verwijderd.",
        "tweak_added_expecting_ipa": "Tweak toegevoegd: {file_name}. Stuur nu het IPA-bestand om het toe te passen.",
        "error_while_resetting": "Er is een fout opgetreden bij het resetten van opties: {error}."
    }
}
