class Polish:
    strings = {
        "save_error": "Nie można było zapisać {options}. Błąd: {error}.",
        "update_error": "Nie można zaktualizować {options}. Błąd: {error}.",
        "app_name_usage": "Użycie: /nazwa [nowa nazwa aplikacji]",
        "unset_app_name": "Modyfikacja nazwy aplikacji została zresetowana.",
        "set_app_name": "Nazwa aplikacji zostanie zmieniona na **{name}**.",
        "app_version_usage": "Użycie: /version [nowa wersja]",
        "invalid_app_version": "Nieprawidłowy format wersji. Proszę używać tylko cyfr i kropek (np. 1.2.3).",
        "unset_app_version": "Modyfikacja wersji aplikacji została zresetowana.",
        "set_app_version": "Wersja aplikacji zostanie zmieniona na **{version}**.",
        "app_id_usage": "Użycie: /id [nowy identyfikator pakietu]",
        "unset_app_id": "Modyfikacja identyfikatora pakietu została zresetowana.",
        "set_app_id": "Identyfikator pakietu zostanie zmieniony na **{id}**.",
        "min_os_usage": "Użycie: /minos [wersja]",
        "invalid_min_os": "Nieprawidłowy format wersji systemu operacyjnego. Proszę używać tylko cyfr i kropek (np. 15.0).",
        "unset_min_os": "Modyfikacja minimalnej wersji systemu operacyjnego została zresetowana.",
        "set_min_os": "Minimalna wersja systemu operacyjnego zostanie ustawiona na **{os_version}**.",
        "unset_profile_removal": "Osadzony profil nie będzie już usuwany.",
        "set_profile_removal": "Osadzony profil zostanie usunięty.",
        "tweak_added_expecting_ipa": "Tweak dodany: {file_name}. Teraz wyślij plik IPA, aby go zastosować.",
        "unset_remove_watch": "Modyfikacja usunięcia pakietu Watch została zresetowana.",
        "set_remove_watch": "Usunięcie pakietu Watch Bundle zostanie ustawione.",
        "error_while_resetting": "Wystąpił błąd podczas resetowania opcji: {error}."
    }
