class Arabic:
    strings = {
        "permission_denied": "غير مصرح لك بإضافة شهادات جديدة.",
        "upload_certificate": "الرجاء البدء بتحميل ملف .mobileprovision أو .p12 الخاص بك.",
        "invalid_file_type": "نوع ملف غير صالح. الرجاء تحميل ملف .p12 أو .mobileprovision.",
        "upload_p12": "الرجاء تحميل ملف .p12 الخاص بك.",
        "invalid_mobileprovision": "ملف .mobileprovision غير صالح.",
        "upload_unexpected_error": "حدث خطأ غير متوقع أثناء عملية التحميل.",
        "cert_data_missing": "خطأ: بيانات الشهادة مفقودة. الرجاء إعادة التشغيل.",
        "cert_saved_success": "تم حفظ الشهادة بنجاح!",
        "cert_save_failed": "فشل حفظ الشهادة.",
        "saving_error": "حدث خطأ أثناء حفظ الشهادة.",
        "upload_mobileprovision": "الرجاء تحميل ملف .mobileprovision الخاص بك.",
        "no_password": "لا توجد كلمة مرور",
        "enter_password": "الرجاء إدخال كلمة المرور لملف .p12 الخاص بك. إذا لم يكن لشهادتك كلمة مرور، استخدم الزر أدناه.",
        "checking_revocation": "جاري التحقق من حالة الإلغاء الآن...",
        "ocsp_check_error": "حدث خطأ أثناء التحقق من OCSP: {e}",
        "ocsp_status": "حالة OCSP:\n{ocsp_status_result}",
        "ocsp_check_failed": "الشهادة غير صالحة (ملغاة أو حالة غير معروفة).",
        "password_correct": "كلمة المرور صحيحة!",
        "password_incorrect": "كلمة المرور غير صحيحة. الرجاء المحاولة مرة أخرى.",
        "p12_path_not_found": "خطأ: مسار ملف p12 غير موجود. الرجاء إعادة التشغيل.",
        "no_password_used": "لن يتم استخدام كلمة مرور.",
    }
