class Arabic:
    strings = {
        "permission_denied": "غير مصرح لك بإضافة شهادات جديدة.",
        "upload_certificate": "الرجاء البدء بتحميل ملف .mobileprovision أو .p12 الخاص بك.",
        "invalid_file_type": "نوع ملف غير صالح. الرجاء تحميل ملف .p12 أو .mobileprovision.",
        "upload_p12": "الرجاء تحميل ملف .p12 الخاص بك.",
        "invalid_mobileprovision": "ملف .mobileprovision غير صالح.",
        "upload_unexpected_error": "حدث خطأ غير متوقع أثناء عملية التحميل.",
        "cert_data_missing": "خطأ: بيانات الشهادة مفقودة. الرجاء إعادة التشغيل.",
        "cert_saved_success": "تم حفظ الشهادة بنجاح!",
        "cert_save_failed": "فشل حفظ الشهادة.",
        "saving_error": "حدث خطأ أثناء حفظ الشهادة.",
        "upload_mobileprovision": "الرجاء تحميل ملف .mobileprovision الخاص بك.",
        "no_password": "لا توجد كلمة مرور",
        "enter_password": "الرجاء إدخال كلمة المرور لملف .p12 الخاص بك. إذا لم يكن لشهادتك كلمة مرور، استخدم الزر أدناه.",
        "ocsp_check_error": "حدث خطأ أثناء التحقق من OCSP: {e}",
        "password_correct": "كلمة المرور صحيحة!",
        "password_incorrect": "كلمة المرور غير صحيحة. الرجاء المحاولة مرة أخرى.",
        "p12_path_not_found": "خطأ: مسار ملف p12 غير موجود. الرجاء إعادة التشغيل.",
        "no_password_used": "لن يتم استخدام كلمة مرور.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_title": "",
        "ocsp_reason": "",
        "certificate_status_label": "",
        "certificate_revoke_time": "",
        "certificate_is_valid": "",
    }
