class Arabic:
    strings = {
        "upload_unexpected_error": "",
        "upload_p12": "",
        "upload_mobileprovision": "",
        "upload_certificate": "",
        "saving_error": "",
        "permission_denied": "",
        "password_incorrect": "",
        "password_correct": "",
        "p12_path_not_found": "",
        "ocsp_status": "",
        "ocsp_check_failed": "",
        "ocsp_check_error": "",
        "no_password_used": "",
        "no_password": "",
        "invalid_mobileprovision": "",
        "invalid_file_type": "",
        "enter_password": "",
        "checking_revocation": "",
        "cert_saved_success": "",
        "cert_save_failed": "",
        "cert_data_missing": "",
    }
