class Chinese:
    strings = {
        "permission_denied": "您无权添加新证书。",
        "upload_certificate": "请上传您的 .mobileprovision 或 .p12 文件。",
        "invalid_file_type": "无效的文件类型。请上传 .p12 或 .mobileprovision 文件。",
        "upload_p12": "请上传您的 .p12 文件。",
        "invalid_mobileprovision": "无效的 .mobileprovision 文件。",
        "upload_unexpected_error": "上传过程中发生意外错误。",
        "cert_data_missing": "错误：证书数据丢失。请重新开始。",
        "cert_saved_success": "证书保存成功！",
        "cert_save_failed": "保存证书失败。",
        "saving_error": "保存证书时发生错误。",
        "upload_mobileprovision": "请上传您的 .mobileprovision 文件。",
        "no_password": "无密码",
        "enter_password": "请输入您的 .p12 文件的密码。如果您的证书没有密码，请使用下面的按钮。",
        "checking_revocation": "正在检查吊销状态...",
        "ocsp_check_error": "OCSP 检查期间发生错误：{e}",
        "ocsp_status": "OCSP 状态：\n{ocsp_status_result}",
        "ocsp_check_failed": "证书无效（已吊销或状态未知）。",
        "password_correct": "密码正确！",
        "password_incorrect": "密码不正确。请重试。",
        "p12_path_not_found": "错误：找不到 p12 文件路径。请重新开始。",
        "no_password_used": "不使用密码。",
    }
