class German:
    strings = {
        "permission_denied": "Du bist nicht berechtigt, neue Zertifikate hinzuzufügen.",
        "upload_certificate": "Bitte laden Sie zuerst Ihre .mobileprovision- oder .p12-Datei hoch.",
        "invalid_file_type": "Ungültiger Dateityp. Bitte laden Sie eine .p12- oder .mobileprovision-Datei hoch.",
        "upload_p12": "Bitte laden Sie Ihre .p12-Datei hoch.",
        "invalid_mobileprovision": "Ungültige .mobileprovision-Datei.",
        "upload_unexpected_error": "Während des Upload-Vorgangs ist ein unerwarteter Fehler aufgetreten.",
        "cert_data_missing": "Fehler: Zertifikatsdaten fehlen. Bitte neu starten.",
        "cert_saved_success": "Zertifikat erfolgreich gespeichert!",
        "cert_save_failed": "Speichern des Zertifikats fehlgeschlagen.",
        "saving_error": "Beim Speichern des Zertifikats ist ein Fehler aufgetreten.",
        "upload_mobileprovision": "Bitte laden Sie Ihre .mobileprovision-Datei hoch.",
        "no_password": "Kein Passwort",
        "enter_password": "Bitte geben Sie das Passwort für Ihre .p12-Datei ein. Wenn Ihr Zertifikat kein Passwort hat, verwenden Sie die Schaltfläche unten.",
        "checking_revocation": "Überprüfe jetzt den Widerrufsstatus...",
        "ocsp_check_error": "Ein Fehler ist während der OCSP-Prüfung aufgetreten: {e}",
        "ocsp_status": "OCSP-Status:\n{ocsp_status_result}",
        "ocsp_check_failed": "Zertifikat ist nicht gültig (widerrufen oder unbekannter Status).",
        "password_correct": "Passwort korrekt!",
        "password_incorrect": "Falsches Passwort. Bitte versuchen Sie es erneut.",
        "p12_path_not_found": "Fehler: p12-Dateipfad nicht gefunden. Bitte neu starten.",
        "no_password_used": "Es wird kein Passwort verwendet.",
    }
