class English:
    strings = {
        "permission_denied": "You are not authorized to add new certificates.",
        "upload_certificate": "Please start by uploading your .mobileprovision or .p12 file.",
        "invalid_file_type": "Invalid file type. Please upload a .p12 or .mobileprovision file.",
        "upload_p12": "Please upload your .p12 file.",
        "invalid_mobileprovision": "Invalid .mobileprovision file.",
        "upload_unexpected_error": "An unexpected error occurred during the upload process.",
        "cert_data_missing": "Error: Certificate data missing. Please restart.",
        "cert_saved_success": "Certificate saved successfully!",
        "cert_save_failed": "Failed to save certificate.",
        "saving_error": "An error occurred while saving the certificate.",
        "upload_mobileprovision": "Please upload your .mobileprovision file.",
        "no_password": "No Password",
        "enter_password": "Please enter the password for your .p12 file. If your certificate has no password, use the button below.",
        "ocsp_check_error": "An error occurred during OCSP check: {e}",
        "password_correct": "Password correct!",
        "password_incorrect": "Incorrect password. Please try again.",
        "p12_path_not_found": "Error: p12 file path not found. Please restart.",
        "no_password_used": "No password will be used.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_valid": "",
        "ocsp_status_unknown": "",
        "ocsp_status_title": "",
        "ocsp_status_revoked": "",
        "ocsp_status_label": "",
        "ocsp_reason": "",
    }
