class Spanish:
    strings = {
        "permission_denied": "No estás autorizado para añadir nuevos certificados.",
        "upload_certificate": "Por favor, comience subiendo su archivo .mobileprovision o .p12.",
        "invalid_file_type": "Tipo de archivo no válido. Por favor, suba un archivo .p12 o .mobileprovision.",
        "upload_p12": "Por favor, suba su archivo .p12.",
        "invalid_mobileprovision": "Archivo .mobileprovision no válido.",
        "upload_unexpected_error": "Ocurrió un error inesperado durante el proceso de carga.",
        "cert_data_missing": "Error: Faltan datos del certificado. Por favor, reinicie.",
        "cert_saved_success": "¡Certificado guardado exitosamente!",
        "cert_save_failed": "No se pudo guardar el certificado.",
        "saving_error": "Ocurrió un error al guardar el certificado.",
        "upload_mobileprovision": "Por favor, suba su archivo .mobileprovision.",
        "no_password": "Sin Contraseña",
        "enter_password": "Por favor, introduzca la contraseña de su archivo .p12. Si su certificado no tiene contraseña, use el botón de abajo.",
        "ocsp_check_error": "Ocurrió un error durante la comprobación OCSP: {e}",
        "ocsp_check_failed": "El certificado no es válido (revocado o estado desconocido).",
        "password_correct": "¡Contraseña correcta!",
        "password_incorrect": "Contraseña incorrecta. Por favor, inténtelo de nuevo.",
        "p12_path_not_found": "Error: No se encontró la ruta del archivo p12. Por favor, reinicie.",
        "no_password_used": "No se utilizará ninguna contraseña.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
    }
