class French:
    strings = {
        "permission_denied": "Vous n'êtes pas autorisé à ajouter de nouveaux certificats.",
        "upload_certificate": "Veuillez commencer par télécharger votre fichier .mobileprovision ou .p12.",
        "invalid_file_type": "Type de fichier invalide. Veuillez télécharger un fichier .p12 ou .mobileprovision.",
        "upload_p12": "Veuillez télécharger votre fichier .p12.",
        "invalid_mobileprovision": "Fichier .mobileprovision invalide.",
        "upload_unexpected_error": "Une erreur inattendue est survenue pendant le processus de téléchargement.",
        "cert_data_missing": "Erreur: Données de certificat manquantes. Veuillez redémarrer.",
        "cert_saved_success": "Certificat enregistré avec succès!",
        "cert_save_failed": "Échec de l'enregistrement du certificat.",
        "saving_error": "Une erreur est survenue lors de l'enregistrement du certificat.",
        "upload_mobileprovision": "Veuillez télécharger votre fichier .mobileprovision.",
        "no_password": "Pas de mot de passe",
        "enter_password": "Veuillez entrer le mot de passe de votre fichier .p12. Si votre certificat n'a pas de mot de passe, utilisez le bouton ci-dessous.",
        "checking_revocation": "Vérification du statut de révocation...",
        "ocsp_check_error": "Une erreur est survenue lors de la vérification OCSP: {e}",
        "ocsp_status": "Statut OCSP:\n{ocsp_status_result}",
        "ocsp_check_failed": "Le certificat n'est pas valide (révoqué ou statut inconnu).",
        "password_correct": "Mot de passe correct!",
        "password_incorrect": "Mot de passe incorrect. Veuillez réessayer.",
        "p12_path_not_found": "Erreur: Chemin du fichier p12 introuvable. Veuillez redémarrer.",
        "no_password_used": "Aucun mot de passe ne sera utilisé.",
    }
