class Indonesian:
    strings = {
        "permission_denied": "Anda tidak diizinkan untuk menambahkan sertifikat baru.",
        "upload_certificate": "Silakan mulai dengan mengunggah file .mobileprovision atau .p12 Anda.",
        "invalid_file_type": "Jenis file tidak valid. Silakan unggah file .p12 atau .mobileprovision.",
        "upload_p12": "Silakan unggah file .p12 Anda.",
        "invalid_mobileprovision": "File .mobileprovision tidak valid.",
        "upload_unexpected_error": "Terjadi kesalahan tak terduga selama proses pengunggahan.",
        "cert_data_missing": "Kesalahan: Data sertifikat hilang. Silakan mulai ulang.",
        "cert_saved_success": "Sertifikat berhasil disimpan!",
        "cert_save_failed": "Gagal menyimpan sertifikat.",
        "saving_error": "Terjadi kesalahan saat menyimpan sertifikat.",
        "upload_mobileprovision": "Silakan unggah file .mobileprovision Anda.",
        "no_password": "Tidak Ada Kata Sandi",
        "enter_password": "Silakan masukkan kata sandi untuk file .p12 Anda. Jika sertifikat Anda tidak memiliki kata sandi, gunakan tombol di bawah ini.",
        "ocsp_check_error": "Terjadi kesalahan selama pemeriksaan OCSP: {e}",
        "password_correct": "Kata sandi benar!",
        "password_incorrect": "Kata sandi salah. Silakan coba lagi.",
        "p12_path_not_found": "Kesalahan: Jalur file p12 tidak ditemukan. Silakan mulai ulang.",
        "no_password_used": "Tidak ada kata sandi yang akan digunakan.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_title": "**Status Sertifikat**",
        "certificate_status_label": "Status",
        "certificate_is_valid": "Sertifikat Valid",
        "ocsp_serial_label": "",
        "revoke_reason_seperator_string": "",
    }
