class Indonesian:
    strings = {
        "permission_denied": "Anda tidak diizinkan untuk menambahkan sertifikat baru.",
        "upload_certificate": "Silakan mulai dengan mengunggah file .mobileprovision atau .p12 Anda.",
        "invalid_file_type": "Jenis file tidak valid. Silakan unggah file .p12 atau .mobileprovision.",
        "upload_p12": "Silakan unggah file .p12 Anda.",
        "invalid_mobileprovision": "File .mobileprovision tidak valid.",
        "upload_unexpected_error": "Terjadi kesalahan tak terduga selama proses pengunggahan.",
        "cert_data_missing": "Kesalahan: Data sertifikat hilang. Silakan mulai ulang.",
        "cert_saved_success": "Sertifikat berhasil disimpan!",
        "cert_save_failed": "Gagal menyimpan sertifikat.",
        "saving_error": "Terjadi kesalahan saat menyimpan sertifikat.",
        "upload_mobileprovision": "Silakan unggah file .mobileprovision Anda.",
        "no_password": "Tidak Ada Kata Sandi",
        "enter_password": "Silakan masukkan kata sandi untuk file .p12 Anda. Jika sertifikat Anda tidak memiliki kata sandi, gunakan tombol di bawah ini.",
        "checking_revocation": "Sekarang memeriksa status pencabutan...",
        "ocsp_check_error": "Terjadi kesalahan selama pemeriksaan OCSP: {e}",
        "ocsp_status": "Status OCSP:\n{ocsp_status_result}",
        "ocsp_check_failed": "Sertifikat tidak valid (dicabut atau status tidak diketahui).",
        "password_correct": "Kata sandi benar!",
        "password_incorrect": "Kata sandi salah. Silakan coba lagi.",
        "p12_path_not_found": "Kesalahan: Jalur file p12 tidak ditemukan. Silakan mulai ulang.",
        "no_password_used": "Tidak ada kata sandi yang akan digunakan.",
    }
