class Italian:
    strings = {
        "permission_denied": "Non sei autorizzato ad aggiungere nuovi certificati.",
        "upload_certificate": "Si prega di iniziare caricando il file .mobileprovision o .p12.",
        "invalid_file_type": "Tipo di file non valido. Si prega di caricare un file .p12 o .mobileprovision.",
        "upload_p12": "Si prega di caricare il file .p12.",
        "invalid_mobileprovision": "File .mobileprovision non valido.",
        "upload_unexpected_error": "Si è verificato un errore imprevisto durante il processo di caricamento.",
        "cert_data_missing": "Errore: Dati del certificato mancanti. Si prega di riavviare.",
        "cert_saved_success": "Certificato salvato con successo!",
        "cert_save_failed": "Salvataggio del certificato fallito.",
        "saving_error": "Si è verificato un errore durante il salvataggio del certificato.",
        "upload_mobileprovision": "Si prega di caricare il file .mobileprovision.",
        "no_password": "Nessuna password",
        "enter_password": "Si prega di inserire la password per il file .p12. Se il certificato non ha password, utilizzare il pulsante sottostante.",
        "checking_revocation": "Controllo dello stato di revoca in corso...",
        "ocsp_check_error": "Si è verificato un errore durante il controllo OCSP: {e}",
        "ocsp_status": "Stato OCSP:\n{ocsp_status_result}",
        "ocsp_check_failed": "Il certificato non è valido (revocato o stato sconosciuto).",
        "password_correct": "Password corretta!",
        "password_incorrect": "Password errata. Si prega di riprovare.",
        "p12_path_not_found": "Errore: Percorso del file p12 non trovato. Si prega di riavviare.",
        "no_password_used": "Nessuna password verrà utilizzata.",
    }
