class Italian:
    strings = {
        "permission_denied": "Non sei autorizzato ad aggiungere nuovi certificati.",
        "upload_certificate": "Si prega di iniziare caricando il file .mobileprovision o .p12.",
        "invalid_file_type": "Tipo di file non valido. Si prega di caricare un file .p12 o .mobileprovision.",
        "upload_p12": "Si prega di caricare il file .p12.",
        "invalid_mobileprovision": "File .mobileprovision non valido.",
        "upload_unexpected_error": "Si è verificato un errore imprevisto durante il processo di caricamento.",
        "cert_data_missing": "Errore: Dati del certificato mancanti. Si prega di riavviare.",
        "cert_saved_success": "Certificato salvato con successo!",
        "cert_save_failed": "Salvataggio del certificato fallito.",
        "saving_error": "Si è verificato un errore durante il salvataggio del certificato.",
        "upload_mobileprovision": "Si prega di caricare il file .mobileprovision.",
        "no_password": "Nessuna password",
        "enter_password": "Si prega di inserire la password per il file .p12. Se il certificato non ha password, utilizzare il pulsante sottostante.",
        "ocsp_check_error": "Si è verificato un errore durante il controllo OCSP: {e}",
        "password_correct": "Password corretta!",
        "password_incorrect": "Password errata. Si prega di riprovare.",
        "p12_path_not_found": "Errore: Percorso del file p12 non trovato. Si prega di riavviare.",
        "no_password_used": "Nessuna password verrà utilizzata.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_valid": "",
        "ocsp_status_unknown": "",
        "ocsp_status_title": "",
        "ocsp_status_revoked": "",
        "ocsp_status_label": "",
        "ocsp_reason": "",
    }
