class Japanese:
    strings = {
        "permission_denied": "新しい証明書を追加する権限がありません。",
        "upload_certificate": ".mobileprovision または .p12 ファイルをアップロードしてください。",
        "invalid_file_type": "無効なファイルタイプです。.p12 または .mobileprovision ファイルをアップロードしてください。",
        "upload_p12": ".p12 ファイルをアップロードしてください。",
        "invalid_mobileprovision": "無効な .mobileprovision ファイルです。",
        "upload_unexpected_error": "アップロード中に予期せぬエラーが発生しました。",
        "cert_data_missing": "エラー: 証明書データがありません。再起動してください。",
        "cert_saved_success": "証明書が正常に保存されました！",
        "cert_save_failed": "証明書の保存に失敗しました。",
        "saving_error": "証明書の保存中にエラーが発生しました。",
        "upload_mobileprovision": ".mobileprovision ファイルをアップロードしてください。",
        "no_password": "パスワードなし",
        "enter_password": ".p12 ファイルのパスワードを入力してください。証明書にパスワードがない場合は、下のボタンを使用してください。",
        "ocsp_check_error": "OCSPチェック中にエラーが発生しました: {e}",
        "password_correct": "パスワードが正しいです！",
        "password_incorrect": "パスワードが間違っています。もう一度お試しください。",
        "p12_path_not_found": "エラー: p12ファイルパスが見つかりません。再起動してください。",
        "no_password_used": "パスワードは使用されません。",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_title": "**証明書ステータス**",
        "certificate_status_label": "ステータス",
        "certificate_is_valid": "証明書は有効です",
        "ocsp_serial_label": "",
        "revoke_reason_seperator_string": "",
    }
