class Japanese:
    strings = {
        "permission_denied": "新しい証明書を追加する権限がありません。",
        "upload_certificate": ".mobileprovision または .p12 ファイルをアップロードしてください。",
        "invalid_file_type": "無効なファイルタイプです。.p12 または .mobileprovision ファイルをアップロードしてください。",
        "upload_p12": ".p12 ファイルをアップロードしてください。",
        "invalid_mobileprovision": "無効な .mobileprovision ファイルです。",
        "upload_unexpected_error": "アップロード中に予期せぬエラーが発生しました。",
        "cert_data_missing": "エラー: 証明書データがありません。再起動してください。",
        "cert_saved_success": "証明書が正常に保存されました！",
        "cert_save_failed": "証明書の保存に失敗しました。",
        "saving_error": "証明書の保存中にエラーが発生しました。",
        "upload_mobileprovision": ".mobileprovision ファイルをアップロードしてください。",
        "no_password": "パスワードなし",
        "enter_password": ".p12 ファイルのパスワードを入力してください。証明書にパスワードがない場合は、下のボタンを使用してください。",
        "checking_revocation": "失効ステータスを確認中...",
        "ocsp_check_error": "OCSPチェック中にエラーが発生しました: {e}",
        "ocsp_status": "OCSPステータス:\n{ocsp_status_result}",
        "ocsp_check_failed": "証明書は無効です（失効または不明なステータス）。",
        "password_correct": "パスワードが正しいです！",
        "password_incorrect": "パスワードが間違っています。もう一度お試しください。",
        "p12_path_not_found": "エラー: p12ファイルパスが見つかりません。再起動してください。",
        "no_password_used": "パスワードは使用されません。",
    }
