class Dutch:
    strings = {
        "permission_denied": "U bent niet gemachtigd om nieuwe certificaten toe te voegen.",
        "upload_certificate": "Begin met het uploaden van uw .mobileprovision- of .p12-bestand.",
        "invalid_file_type": "Ongeldig bestandstype. Upload een .p12- of .mobileprovision-bestand.",
        "upload_p12": "Upload uw .p12-bestand.",
        "invalid_mobileprovision": "Ongeldig .mobileprovision-bestand.",
        "upload_unexpected_error": "Er is een onverwachte fout opgetreden tijdens het uploadproces.",
        "cert_data_missing": "Fout: Certificaatgegevens ontbreken. Start opnieuw.",
        "cert_saved_success": "Certificaat succesvol opgeslagen!",
        "cert_save_failed": "Kan certificaat niet opslaan.",
        "saving_error": "Er is een fout opgetreden bij het opslaan van het certificaat.",
        "upload_mobileprovision": "Upload uw .mobileprovision-bestand.",
        "no_password": "Geen wachtwoord",
        "enter_password": "Voer het wachtwoord voor uw .p12-bestand in. Als uw certificaat geen wachtwoord heeft, gebruik dan de onderstaande knop.",
        "checking_revocation": " intrekkingsstatus controleren...",
        "ocsp_check_error": "Er is een fout opgetreden tijdens de OCSP-controle: {e}",
        "ocsp_status": "OCSP-status:\n{ocsp_status_result}",
        "ocsp_check_failed": "Certificaat is niet geldig (ingetrokken of onbekende status).",
        "password_correct": "Wachtwoord correct!",
        "password_incorrect": "Onjuist wachtwoord. Probeer het opnieuw.",
        "p12_path_not_found": "Fout: p12-bestandspad niet gevonden. Start opnieuw.",
        "no_password_used": "Er wordt geen wachtwoord gebruikt.",
    }
