class Polish:
    strings = {
        "permission_denied": "Nie masz uprawnień do dodawania nowych certyfikatów.",
        "upload_certificate": "Rozpocznij od przesłania pliku .mobileprovision lub .p12.",
        "invalid_file_type": "Nieprawidłowy typ pliku. Prześlij plik .p12 lub .mobileprovision.",
        "upload_p12": "Prześlij plik .p12.",
        "invalid_mobileprovision": "Nieprawidłowy plik .mobileprovision.",
        "upload_unexpected_error": "Wystąpił nieoczekiwany błąd podczas przesyłania.",
        "cert_data_missing": "Błąd: Brak danych certyfikatu. Uruchom ponownie.",
        "cert_saved_success": "Certyfikat zapisany pomyślnie!",
        "cert_save_failed": "Nie udało się zapisać certyfikatu.",
        "saving_error": "Wystąpił błąd podczas zapisywania certyfikatu.",
        "upload_mobileprovision": "Prześlij plik .mobileprovision.",
        "no_password": "Brak hasła",
        "enter_password": "Wprowadź hasło do pliku .p12. Jeśli certyfikat nie ma hasła, użyj przycisku poniżej.",
        "checking_revocation": "Sprawdzanie stanu unieważnienia...",
        "ocsp_check_error": "Wystąpił błąd podczas sprawdzania OCSP: {e}",
        "ocsp_status": "Stan OCSP:\n{ocsp_status_result}",
        "ocsp_check_failed": "Certyfikat jest nieprawidłowy (unieważniony lub nieznany stan).",
        "password_correct": "Hasło prawidłowe!",
        "password_incorrect": "Nieprawidłowe hasło. Spróbuj ponownie.",
        "p12_path_not_found": "Błąd: Nie znaleziono ścieżki do pliku p12. Uruchom ponownie.",
        "no_password_used": "Hasło nie będzie używane.",
    }