class Portuguese:
    strings = {
        "permission_denied": "Você não está autorizado a adicionar novos certificados.",
        "upload_certificate": "Comece enviando seu arquivo .mobileprovision ou .p12.",
        "invalid_file_type": "Tipo de arquivo inválido. Envie um arquivo .p12 ou .mobileprovision.",
        "upload_p12": "Envie seu arquivo .p12.",
        "invalid_mobileprovision": "Arquivo .mobileprovision inválido.",
        "upload_unexpected_error": "Ocorreu um erro inesperado durante o processo de upload.",
        "cert_data_missing": "Erro: Faltam dados do certificado. Reinicie.",
        "cert_saved_success": "Certificado salvo com sucesso!",
        "cert_save_failed": "Falha ao salvar o certificado.",
        "saving_error": "Ocorreu um erro ao salvar o certificado.",
        "upload_mobileprovision": "Envie seu arquivo .mobileprovision.",
        "no_password": "Sem senha",
        "enter_password": "Digite a senha do seu arquivo .p12. Se o seu certificado não tiver senha, use o botão abaixo.",
        "ocsp_check_error": "Ocorreu um erro durante a verificação OCSP: {e}",
        "password_correct": "Senha correta!",
        "password_incorrect": "Senha incorreta. Tente novamente.",
        "p12_path_not_found": "Erro: Caminho do arquivo p12 não encontrado. Reinicie.",
        "no_password_used": "Nenhuma senha será usada.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_title": "",
        "ocsp_reason": "",
        "certificate_status_label": "",
        "certificate_revoke_time": "",
        "certificate_is_valid": "",
    }
