class Russian:
    strings = {
        "permission_denied": "У вас нет прав на добавление новых сертификатов.",
        "upload_certificate": "Начните с загрузки файла .mobileprovision или .p12.",
        "invalid_file_type": "Недопустимый тип файла. Загрузите файл .p12 или .mobileprovision.",
        "upload_p12": "Загрузите файл .p12.",
        "invalid_mobileprovision": "Недопустимый файл .mobileprovision.",
        "upload_unexpected_error": "Во время загрузки произошла непредвиденная ошибка.",
        "cert_data_missing": "Ошибка: Отсутствуют данные сертификата. Пожалуйста, перезапустите.",
        "cert_saved_success": "Сертификат успешно сохранен!",
        "cert_save_failed": "Не удалось сохранить сертификат.",
        "saving_error": "Произошла ошибка при сохранении сертификата.",
        "upload_mobileprovision": "Загрузите файл .mobileprovision.",
        "no_password": "Нет пароля",
        "enter_password": "Введите пароль для файла .p12. Если у вашего сертификата нет пароля, используйте кнопку ниже.",
        "checking_revocation": "Проверка статуса отзыва...",
        "ocsp_check_error": "Произошла ошибка во время проверки OCSP: {e}",
        "ocsp_status": "Статус OCSP:\n{ocsp_status_result}",
        "ocsp_check_failed": "Сертификат недействителен (отозван или неизвестен статус).",
        "password_correct": "Пароль верный!",
        "password_incorrect": "Неверный пароль. Попробуйте еще раз.",
        "p12_path_not_found": "Ошибка: не найден путь к файлу p12. Пожалуйста, перезапустите.",
        "no_password_used": "Пароль не будет использоваться.",
    }
