class Turkish:
    strings = {
        "permission_denied": "Yeni sertifika ekleme yetkiniz yok.",
        "upload_certificate": "Lütfen .mobileprovision veya .p12 dosyanızı yükleyerek başlayın.",
        "invalid_file_type": "Geçersiz dosya türü. Lütfen bir .p12 veya .mobileprovision dosyası yükleyin.",
        "upload_p12": "Lütfen .p12 dosyanızı yükleyin.",
        "invalid_mobileprovision": "Geçersiz .mobileprovision dosyası.",
        "upload_unexpected_error": "Yükleme işlemi sırasında beklenmedik bir hata oluştu.",
        "cert_data_missing": "Hata: Sertifika verileri eksik. Lütfen yeniden başlatın.",
        "cert_saved_success": "Sertifika başarıyla kaydedildi!",
        "cert_save_failed": "Sertifika kaydedilemedi.",
        "saving_error": "Sertifika kaydedilirken bir hata oluştu.",
        "upload_mobileprovision": "Lütfen .mobileprovision dosyanızı yükleyin.",
        "no_password": "Parola Yok",
        "enter_password": ".p12 dosyanızın parolasını girin. Sertifikanızın parolası yoksa, aşağıdaki düğmeyi kullanın.",
        "ocsp_check_error": "OCSP kontrolü sırasında bir hata oluştu: {e}",
        "password_correct": "Parola doğru!",
        "password_incorrect": "Yanlış parola. Lütfen tekrar deneyin.",
        "p12_path_not_found": "Hata: p12 dosya yolu bulunamadı. Lütfen yeniden başlatın.",
        "no_password_used": "Parola kullanılmayacak.",
        "updating_mobileprovision": "Existing certificate found. Updating mobileprovision file...",
        "update_mp_failed": "An error occurred while updating the mobileprovision file.",
        "mobileprovision_updated_success": "Mobileprovision file updated successfully for certificate '{cert_name}'!",
        "password_incorrect_repeated": "Incorrect password. Please try again. (Attempt: {attempts})",
        "ocsp_status_valid": "",
        "ocsp_status_unknown": "",
        "ocsp_status_title": "",
        "ocsp_status_revoked": "",
        "ocsp_status_label": "",
        "ocsp_reason": "",
    }
