class Korean:
    strings = {
        "permission_denied": "새 인증서를 추가할 권한이 없습니다.",
        "certificate_updated": "인증서가 성공적으로 업데이트되었습니다: {file_name}",
        "unexpected_git_error": "예기치 않은 Git 오류가 발생했습니다: {error}",
        "unexpected_error": "예기치 않은 오류가 발생했습니다: {error}",
        "upload_certificate": "Please start by uploading your .mobileprovision or .p12 file.",
        "invalid_file_type": "Invalid file type. Please upload a .p12 or .mobileprovision file.",
        "upload_p12": "Please upload your .p12 file.",
        "invalid_mobileprovision": "Invalid .mobileprovision file.",
        "upload_unexpected_error": "An unexpected error occurred during the upload process.",
        "cert_data_missing": "Error: Certificate data missing. Please restart.",
        "cert_saved_success": "Certificate saved successfully!",
        "cert_save_failed": "Failed to save certificate.",
        "saving_error": "An error occurred while saving the certificate.",
        "upload_mobileprovision": "Please upload your .mobileprovision file.",
        "no_password": "No Password",
        "enter_password": "Please enter the password for your .p12 file. If your certificate has no password, use the button below.",
        "checking_revocation": "Now checking revocation status...",
        "ocsp_check_error": "An error occurred during OCSP check: {e}",
        "ocsp_status": "OCSP Status:\n{ocsp_status_result}",
        "ocsp_check_failed": "Certificate is not valid (revoked or unknown status).",
        "password_correct": "Password correct!",
        "password_incorrect": "Incorrect password. Please try again.",
        "p12_path_not_found": "Error: p12 file path not found. Please restart.",
        "no_password_used": "No password will be used.",
    }
