class Turkish:
    strings = {
        "permission_denied": "Yeni sertifika ekleme yetkiniz yok.",
        "certificate_updated": "Sertifika başarıyla güncellendi: {file_name}",
        "unexpected_git_error": "Beklenmedik bir Git hatası oluştu: {error}",
        "unexpected_error": "Beklenmedik bir hata oluştu: {error}",
        "upload_certificate": "Lütfen .mobileprovision veya .p12 dosyanızı yükleyerek başlayın.",
        "invalid_file_type": "Geçersiz dosya türü. Lütfen bir .p12 veya .mobileprovision dosyası yükleyin.",
        "upload_p12": "Lütfen .p12 dosyanızı yükleyin.",
        "invalid_mobileprovision": "Geçersiz .mobileprovision dosyası.",
        "upload_unexpected_error": "Yükleme işlemi sırasında beklenmedik bir hata oluştu.",
        "cert_data_missing": "Hata: Sertifika verileri eksik. Lütfen yeniden başlatın.",
        "cert_saved_success": "Sertifika başarıyla kaydedildi!",
        "cert_save_failed": "Sertifika kaydedilemedi.",
        "saving_error": "Sertifika kaydedilirken bir hata oluştu.",
        "upload_mobileprovision": "Lütfen .mobileprovision dosyanızı yükleyin.",
        "no_password": "Parola Yok",
        "enter_password": ".p12 dosyanızın parolasını girin. Sertifikanızın parolası yoksa, aşağıdaki düğmeyi kullanın.",
        "checking_revocation": "İptal durumu şimdi kontrol ediliyor...",
        "ocsp_check_error": "OCSP kontrolü sırasında bir hata oluştu: {e}",
        "ocsp_status": "OCSP Durumu:\n{ocsp_status_result}",
        "ocsp_check_failed": "Sertifika geçerli değil (iptal edilmiş veya bilinmeyen durum).",
        "password_correct": "Parola doğru!",
        "password_incorrect": "Yanlış parola. Lütfen tekrar deneyin.",
        "p12_path_not_found": "Hata: p12 dosya yolu bulunamadı. Lütfen yeniden başlatın.",
        "no_password_used": "Parola kullanılmayacak.",
    }
