class Spanish:
    strings = {
        "user_not_registered": "No estás registrado para usar este bot.",
        "available_cmds": "**Comandos disponibles**",
        "user_cmds": "**Comandos de usuario**",
        "cmd_prefixes": "Prefijos de comando activos: {prefixes}",
        "admin_cmds": "**Comandos de administrador**",
        "help_cmd": "Muestra este mensaje de ayuda.",
        "speedtest_cmd": "Mide la velocidad de conexión.",
        "info_cmd": "Muestra información sobre el bot.",
        "sign_cmd": "Firma el archivo IPA respondido.",
        "clear_cmd": "Restablece todas las opciones de modificación.",
        "profile_cmd": "Elimina el archivo de aprovisionamiento móvil incrustado.",
        "minos_cmd": "Establece la versión mínima de SO requerida.",
        "id_cmd": "Cambia el ID de paquete de la aplicación.",
        "version_cmd": "Cambia la versión de la aplicación.",
        "name_cmd": "Cambia el nombre de la aplicación.",
        "update_cmd": "Actualiza el bot desde el repositorio.",
        "duyur_cmd": "Envía un anuncio a todos los usuarios.",
        "exec_cmd": "Ejecuta un comando de shell.",
        "restart_cmd": "Reinicia el bot.",
        "shutdown_cmd": "Apaga el bot.",
        "user_cmd": "Gestiona los registros de usuarios.",
        "premium_cmd": "Gestiona el estado de usuario premium.",
        "unknown_exception": "Ocurrió un error al procesar la solicitud de ayuda de @{username} ({userID}): {error}"
    }