class French:
    strings = {
        "user_not_registered": "Vous n'êtes pas enregistré pour utiliser ce bot.",
        "available_cmds": "**Commandes disponibles**",
        "user_cmds": "**Commandes utilisateur**",
        "cmd_prefixes": "Préfixes de commande actifs: {prefixes}",
        "admin_cmds": "**Commandes administrateur**",
        "help_cmd": "Affiche ce message d'aide.",
        "speedtest_cmd": "Mesure la vitesse de connexion.",
        "info_cmd": "Affiche des informations sur le bot.",
        "sign_cmd": "Signe le fichier IPA répondu.",
        "clear_cmd": "Réinitialise toutes les options de modification.",
        "profile_cmd": "Supprime le fichier de provisionnement mobile intégré.",
        "minos_cmd": "Définit la version minimale du système d'exploitation requise.",
        "id_cmd": "Modifie l'ID de bundle de l'application.",
        "version_cmd": "Modifie la version de l'application.",
        "name_cmd": "Modifie le nom de l'application.",
        "watch_cmd": "Supprime l'application Watch de l'iPA",
        "update_cmd": "Met à jour le bot depuis le dépôt.",
        "duyur_cmd": "Envoie une annonce à tous les utilisateurs.",
        "exec_cmd": "Exécute une commande shell.",
        "restart_cmd": "Redémarre le bot.",
        "shutdown_cmd": "Arrête le bot.",
        "user_cmd": "Gère les enregistrements d'utilisateurs.",
        "premium_cmd": "Gère le statut d'utilisateur premium.",
        "unknown_exception": "Une erreur est survenue lors du traitement de la demande d'aide de @{username} ({userID}): {error}"
    }
