class Korean:
    strings = {
        "user_not_registered": "이 봇을 사용할 권한이 없습니다.",
        "available_cmds": "**사용 가능한 명령**",
        "user_cmds": "**사용자 명령**",
        "cmd_prefixes": "활성 명령 접두사: {prefixes}",
        "admin_cmds": "**관리자 명령**",
        "help_cmd": "이 도움말 메시지를 표시합니다.",
        "speedtest_cmd": "연결 속도를 측정합니다.",
        "info_cmd": "봇에 대한 정보를 표시합니다.",
        "sign_cmd": "회신된 IPA 파일에 서명합니다.",
        "clear_cmd": "모든 수정 옵션을 재설정합니다.",
        "profile_cmd": "내장된 모바일 프로비저닝 파일을 제거합니다.",
        "minos_cmd": "필요한 최소 OS 버전을 설정합니다.",
        "id_cmd": "애플리케이션의 번들 ID를 변경합니다.",
        "version_cmd": "애플리케이션의 버전을 변경합니다.",
        "name_cmd": "애플리케이션의 이름을 변경합니다.",
        "watch_cmd": "iPA에서 Watch 앱을 제거합니다",
        "update_cmd": "저장소에서 봇을 업데이트합니다.",
        "duyur_cmd": "모든 사용자에게 공지를 보냅니다.",
        "exec_cmd": "셸 명령을 실행합니다.",
        "restart_cmd": "봇을 다시 시작합니다.",
        "shutdown_cmd": "봇을 종료합니다.",
        "user_cmd": "사용자 등록을 관리합니다.",
        "premium_cmd": "프리미엄 사용자 상태를 관리합니다.",
        "unknown_exception": "@{username} ({userID})의 도움말 요청을 처리하는 동안 오류가 발생했습니다: {error}"
    }
