class Dutch:
    strings = {
        "user_not_registered": "U bent niet geregistreerd om deze bot te gebruiken.",
        "available_cmds": "**Beschikbare commando's**",
        "user_cmds": "**Gebruikerscommando's**",
        "cmd_prefixes": "Actieve commandoprefixen: {prefixes}",
        "admin_cmds": "**Admin commando's**",
        "help_cmd": "Toont dit helpbericht.",
        "speedtest_cmd": "Meet de verbindingssnelheid.",
        "info_cmd": "Toont informatie over de bot.",
        "sign_cmd": "Ondertekent het beantwoorde IPA-bestand.",
        "clear_cmd": "Reset alle modificatie-opties.",
        "profile_cmd": "Verwijdert het ingebedde mobiele provisioneringsbestand.",
        "minos_cmd": "Stelt de minimaal vereiste OS-versie in.",
        "id_cmd": "Wijzigt de bundel-ID van de applicatie.",
        "version_cmd": "Wijzigt de versie van de applicatie.",
        "name_cmd": "Wijzigt de naam van de applicatie.",
        "update_cmd": "Werkt de bot bij vanuit de repository.",
        "duyur_cmd": "Verzendt een aankondiging naar alle gebruikers.",
        "exec_cmd": "Voert een shell-commando uit.",
        "restart_cmd": "Herstart de bot.",
        "shutdown_cmd": "Sluit de bot af.",
        "user_cmd": "Beheert gebruikersregistraties.",
        "premium_cmd": "Beheert de premium gebruikersstatus.",
        "unknown_exception": "Er is een fout opgetreden bij het verwerken van het helpverzoek van @{username} ({userID}): {error}"
    }
