class Portuguese:
    strings = {
        "user_not_registered": "You are not registered to use this bot.",
        "available_cmds": "**Available Commands**",
        "user_cmds": "**User Commands**",
        "cmd_prefixes": "Active command prefixes: {prefixes}",
        "admin_cmds": "**Admin Commands**",
        "help_cmd": "Shows this help message.",
        "speedtest_cmd": "Measures the connection speed.",
        "info_cmd": "Displays information about the bot.",
        "sign_cmd": "Signs the replied IPA file.",
        "clear_cmd": "Resets all modification options.",
        "profile_cmd": "Removes the embedded mobile provision file.",
        "minos_cmd": "Sets the minimum OS version required.",
        "id_cmd": "Changes the application's bundle ID.",
        "version_cmd": "Changes the application's version.",
        "name_cmd": "Changes the application's name.",
        "watch_cmd": "Remove o aplicativo de relógio do iPA",
        "update_cmd": "Updates the bot from the repository.",
        "duyur_cmd": "Sends an announcement to all users.",
        "exec_cmd": "Executes a shell command.",
        "restart_cmd": "Restarts the bot.",
        "shutdown_cmd": "Shuts down the bot.",
        "user_cmd": "Manages user registrations.",
        "premium_cmd": "Manages premium user status.",
        "unknown_exception": "An error occurred while processing the help request from @{username} ({userID}): {error}"
    }
