class Portuguese:
    strings = {
        "version_cmd": "",
        "user_not_registered": "",
        "user_cmds": "",
        "user_cmd": "",
        "update_cmd": "",
        "unknown_exception": "",
        "speedtest_cmd": "",
        "sign_cmd": "",
        "shutdown_cmd": "",
        "restart_cmd": "",
        "name_cmd": "",
        "minos_cmd": "",
        "info_cmd": "",
        "id_cmd": "",
        "help_cmd": "",
        "exec_cmd": "",
        "duyur_cmd": "",
        "cmd_prefixes": "",
        "clear_cmd": "",
        "available_cmds": "",
        "admin_cmds": "",
    }
