name: Test Languages
# This workflow runs tests on the language files to ensure they are functioning correctly.

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Run tests
      run: |
        cd ${{ github.workspace }}
        python test.py
